### ISSUE TITLE
Boxplot Y-axis Labels Incorrectly Scaled When Font Size Is Altered

### ISSUE THREAD

**Issue by richtertill** [mwaskom/seaborn#3570] opened 2023-11-23 15:36 UTC
**Description:**
When updating the y-axis tick labels' font size using Matplotlib and Seaborn, the y-axis labels (i.e. numbers at the y-axis) appear to be incorrectly scaled, showing smaller numerical values than the actual data points if the font size is decreased compared to default.

**Steps to Reproduce:**

1. Create a boxplot using Seaborn's sns.boxplot with a specific set of data.
2. Overlay individual data points using Seaborn's sns.swarmplot.
3. Set the y-axis tick labels with a custom font size using ax.set_yticklabels() and a font dictionary.

**Expected Behavior:**
The numerical values of the y-axis tick labels should accurately reflect the data's scale and not be altered by changes in font size. The numerical values should simply appear in the new font style.

**Actual Behavior:**
The numerical values of the y-axis tick labels are scaled down, not matching the actual data points, giving the impression that the median is lower than it should be.

**Additional Context:**
This behavior was observed when attempting to set the font size of the y-axis tick labels for consistency. The issue seems to occur when the ax.set_yticklabels() method is used with a font size defined in the font dictionary. It's unclear whether the problem lies in the font size scaling or the actual rendering of the labels on the y-axis.

`# Sample code to reproduce the issue:`
`import seaborn as sns`
`import matplotlib.pyplot as plt`

`# Example data and plotting code that causes the issue`
`# ...`

`ax.set_xticklabels(ax.get_xticklabels(), fontdict={'size': 5})`
`# Suspected problematic line`
`ax.set_yticklabels(ax.get_yticklabels(), fontdict={'size': 5})`
`plt.show()`

**Comment by mwaskom** [comment] 2023-11-23 16:18
Hi, please follow the instructions given [here](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) for composing a reproducible bug report. Otherwise I am forced to do a lot of extra work and guess whether I am successfully reproducing your issue — natural text is a very lossy medium when we are talking about using code to produce images.

**Comment by mwaskom** [comment] 2023-12-02 14:03
I'm going to close this issue for now because I am unable to understand or reproduce the problem with the information given here. Happy to re-open if you can provide a full example that demonstrates the problem. I'll note that, if there is a behavior along the lines of what you describe, it sounds like more of a question about the matplotlib API than seaborn per se. In any case, feel free to follow up...

**Closed by mwaskom** 2023-12-02 14:03 UTC
Labels: mod:categorical, needs-reprex
