### ISSUE TITLE
displot raises MemoryError with extreme outliers

### ISSUE THREAD

**Issue by mojones** [mwaskom/seaborn#2360] opened 2020-11-19 13:22 UTC
Not sure if this is a bug, intended behaviour or just a consequence of the binning logic, but I ran into this with a real dataset today:

```
# simplified for demo
sns.displot(
    [1e-10,2e-10,3e-10,4e-10,5e-10,10]
)
```
causes
```
MemoryError: Unable to allocate 271. GiB for an array with shape (36342411858,) and data type float64
```

with less extreme outliers it doesn't crash but runs for several minutes, presumably allocating memory, until I have to kill the process. Maybe this is just a pathological case for the bin boundary logic.

**Comment by mwaskom** [comment] 2020-11-19 13:33
Duplicate of #2325?

**Comment by mojones** [comment] 2020-11-19 13:56
Seems likely, setting either an explicit number of bins or a different heuristic fixes the issue. The error message suggests that the problem in this case is at the numpy layer i.e. not to do with drawing many rectangles as in #2325 . 

For what it's worth, as an end user of the package I'd favour a warning (maybe catch the MemoryError from numpy) as that would make it very easy to switch to explicitly controlling the bins.

**Comment by mwaskom** [comment] 2020-11-19 14:02
Perhaps you could show the full stack trace for the error?

**Comment by mojones** [comment] 2020-11-19 14:14
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-34-f6d14b6d35d9> in <module>
----> 1 sns.displot(
      2     [1e-10,2e-10,3e-10,4e-10,5e-10,10],
      3     #bins='sqrt'
      4 )

~/.virtualenvs/nlp/lib/python3.8/site-packages/seaborn/distributions.py in displot(data, x, y, hue, row, col, weights, kind, rug, rug_kws, log_scale, legend, palette, hue_order, hue_norm, color, col_wrap, row_order, col_order, height, aspect, facet_kws, **kwargs)
   2222 
   2223             _assign_default_kwargs(hist_kws, p.plot_univariate_histogram, histplot)
-> 2224             p.plot_univariate_histogram(**hist_kws)
   2225 
   2226         else:

~/.virtualenvs/nlp/lib/python3.8/site-packages/seaborn/distributions.py in plot_univariate_histogram(self, multiple, element, fill, common_norm, common_bins, shrink, kde, kde_kws, color, legend, line_kws, estimate_kws, **plot_kws)
    434 
    435             # Do the histogram computation
--> 436             heights, edges = estimator(observations, weights=weights)
    437 
    438             # Rescale the smoothed curve to match the histogram

~/.virtualenvs/nlp/lib/python3.8/site-packages/seaborn/_statistics.py in __call__(self, x1, x2, weights)
    369         """Count the occurrances in each bin, maybe normalize."""
    370         if x2 is None:
--> 371             return self._eval_univariate(x1, weights)
    372         else:
    373             return self._eval_bivariate(x1, x2, weights)

~/.virtualenvs/nlp/lib/python3.8/site-packages/seaborn/_statistics.py in _eval_univariate(self, x, weights)
    346         bin_edges = self.bin_edges
    347         if bin_edges is None:
--> 348             bin_edges = self.define_bin_edges(x, weights=weights, cache=False)
    349 
    350         density = self.stat == "density"

~/.virtualenvs/nlp/lib/python3.8/site-packages/seaborn/_statistics.py in define_bin_edges(self, x1, x2, weights, cache)
    263         if x2 is None:
    264 
--> 265             bin_edges = self._define_bin_edges(
    266                 x1, weights, self.bins, self.binwidth, self.binrange, self.discrete,
    267             )

~/.virtualenvs/nlp/lib/python3.8/site-packages/seaborn/_statistics.py in _define_bin_edges(self, x, weights, bins, binwidth, binrange, discrete)
    254             bin_edges = np.arange(start, stop + step, step)
    255         else:
--> 256             bin_edges = np.histogram_bin_edges(
    257                 x, bins, binrange, weights,
    258             )

<__array_function__ internals> in histogram_bin_edges(*args, **kwargs)

~/.virtualenvs/nlp/lib/python3.8/site-packages/numpy/lib/histograms.py in histogram_bin_edges(a, bins, range, weights)
    666     """
    667     a, weights = _ravel_and_check_weights(a, weights)
--> 668     bin_edges, _ = _get_bin_edges(a, bins, range, weights)
    669     return bin_edges
    670 

~/.virtualenvs/nlp/lib/python3.8/site-packages/numpy/lib/histograms.py in _get_bin_edges(a, bins, range, weights)
    444 
    445         # bin edges must be computed
--> 446         bin_edges = np.linspace(
    447             first_edge, last_edge, n_equal_bins + 1,
    448             endpoint=True, dtype=bin_type)

<__array_function__ internals> in linspace(*args, **kwargs)

~/.virtualenvs/nlp/lib/python3.8/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    126 
    127     delta = stop - start
--> 128     y = _nx.arange(0, num, dtype=dt).reshape((-1,) + (1,) * ndim(delta))
    129     # In-place multiplication y *= delta/div is faster, but prevents the multiplicant
    130     # from overriding what class is produced, and thus prevents, e.g. use of Quantities,

MemoryError: Unable to allocate 271. GiB for an array with shape (36342411858,) and data type float64
```

**Comment by mwaskom** [comment] 2020-11-19 14:30
And you get this error immediately? My laptop hangs while allocating huge amounts of memory, I guess to swap. I don't think that just catching a `MemoryError` from numpy is going to generically make this usable.

I'll close this in favor of #2325 as it's the same basic issue even though, different datasets seem to run into constraints at different parts of the figure-making process.

**Closed** 2020-11-19 14:34 UTC

**Comment by mojones** [comment] 2020-11-19 16:11
Thanks, I'll keep an eye on the other issue. I get slightly different behaviour depending on the exact values I use - with the ones in the code above it errors immediately, with slightly less extreme values e.g.

```
sns.displot(
    [1e-10,2e-10,3e-10,4e-10,5e-10,1],
    #bins='sqrt'
)
```

it hangs.
