### ISSUE TITLE
Allow for finer control of legend

### ISSUE THREAD

**Issue by moi90** [mwaskom/seaborn#2342] opened 2020-11-02 19:21 UTC
I have a use case where I only want to have a legend for the style (but not the hue).
Currently, the relational plotters `lineplot`, `scatterplot`, etc. only allow to switch on and off the entire legend.
What I would like to have is a possibility to control the display of the groups (style, hue, size) individually.

In my case, I would like to use something like `sns.lineplot(..., legend="style")`.
The parameter could also be a list to only show two groups: `sns.lineplot(..., legend=["style", "hue"])`.
`"brief"` could used like this: `sns.lineplot(..., legend=["style", "hue_brief"])`.
The old usage should also stay possible: `sns.lineplot(..., legend="brief")`.

What do you think? Would this be something that the community could find valuable?

**Comment by mwaskom** [comment] 2020-11-03 14:19
In general, something like this is clearly a good idea. The challenge is getting the right API. I'm -1 on your specific  porposal but do expect this to be somewhat easier in the future.

I'm going to consider this issue a duplicate of https://github.com/mwaskom/seaborn/issues/2231, which has a more comprehensive roadmap for areas where legends should be improved. Because there are a lot of interlocking challenges, I'd rather have a single coherent effort to overhaul how legends work rather than piecemeal fixes that might introduce constraints that aren't fully apparent until later.

**Closed by mwaskom** 2020-11-03 14:19 UTC
