### ISSUE TITLE
Hiding ticklabels on heatmap also hides annotations

### ISSUE THREAD

**Issue by NasaGeek** [mwaskom/seaborn#1214] opened 2017-06-30 05:33 UTC
Even when annot is set to True, setting x/yticklabels to [] causes annotations not to show. This behavior seems odd; if I don't want annotations, I won't set annot.

Code:
```
import seaborn as sns
sns.set()
flights_long = sns.load_dataset("flights")
flights = flights_long.pivot("month", "year", "passengers")
flights.index.name = flights.columns.name = ''
sns.heatmap(flights, annot=True, xticklabels=[], yticklabels=[], fmt="d", linewidths=.5)
```

What I get:
![image](https://user-images.githubusercontent.com/474937/27722171-772aa2e0-5d2b-11e7-914d-5ac660fc3cd0.png)

What I would like:
![image](https://user-images.githubusercontent.com/474937/27722166-6101027a-5d2b-11e7-9e91-f3f876c25067.png)

Does this seem like a reasonable use case?

**Comment by mwaskom** [comment] 2017-06-30 11:32
Duplicate of #837

**Closed by mwaskom** 2017-06-30 11:32 UTC
