### ISSUE TITLE
FacetGrid: dispine with offset resets titles and labels on axes

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [mwaskom/seaborn#1187] opened 2017-05-26 09:41 UTC
I wanted to make a FacetGrid plot with some offset.

Basic code:

```
import seaborn as sns
sns.set(style="ticks", color_codes=True)
tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col="time", row="smoker")
g = g.map(plt.hist, "total_bill")
```
![zero](https://cloud.githubusercontent.com/assets/10461030/26489001/dc480cb2-4205-11e7-9313-551d0ddd2549.png)

Now with offset:

```
tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col = 'time', row='sex')
g.despine(offset=10)
g = g.map(plt.hist, "tip")
```
![second](https://cloud.githubusercontent.com/assets/10461030/26489030/f5803dbc-4205-11e7-9b38-05626e7b5a88.png)

So the x- and y-label return in the inner axes, which is not what I want.
I looked in the code for the class definition of FacetGrid, and applied the same code to remove the labels on the inner axes.

The code I used as a base for my workaround:
[link to code](https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L327)
```
# Now we turn off labels on the inner axes
if sharex:
    for ax in self._not_bottom_axes:
        for label in ax.get_xticklabels():
            label.set_visible(False)
        ax.xaxis.offsetText.set_visible(False)
if sharey:
    for ax in self._not_left_axes:
        for label in ax.get_yticklabels():
            label.set_visible(False)
        ax.yaxis.offsetText.set_visible(False)
```

generate the figure:

```
tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col = 'time', row='sex')
g.despine(offset=10)
g = g.map(plt.hist, "tip")

for ax in g.axes[:, 1:].flat:
    for label in ax.get_yticklabels():
        label.set_visible(False)
    ax.yaxis.offsetText.set_visible(False)
    
for ax in g.axes[:-1, :].flat:
    for label in ax.get_xticklabels():
        label.set_visible(False)
    ax.xaxis.offsetText.set_visible(False)
```
![third](https://cloud.githubusercontent.com/assets/10461030/26489430/9cea7292-4207-11e7-9121-36ce4c88c01d.png)

My workaraound works, so no issues there. But I feel that this is not the behaviour you would expect from FacetGrid. I could not find the code in ```utils/despine``` which would be responsible for the behaviour.

[original stackoverflow post](https://stackoverflow.com/questions/37860163/seaborn-despine-brings-back-the-ytick-labels/44161447#44161447)

**Comment by mwaskom** [comment] 2017-05-26 11:38
Duplicate of #946

**Closed by mwaskom** 2017-05-26 11:38 UTC

**Comment by DaanVanHauwermeiren** [comment] 2017-05-26 16:38
@mwaskom Thanks for the reference, that explains a lot!

**Comment by mwaskom** [comment] 2017-05-26 17:20
I did try to solve this a while back and was not successful. Now that I say that I wonder why `despine` couldn't capture the tick visibility before moving spines and then apply it later. But I would be surprised if I hadn't considered that before...
