### ISSUE TITLE
sharex not working with displot?

### ISSUE THREAD

**Issue by RMeli** [mwaskom/seaborn#2557] opened 2021-04-16 12:57 UTC
I am trying to use `displot` to plot distributions of different variables in the same figure. I might be using `displot` incorrectly, but it seems to me that the `sharex` option passed to `facet_kws` is not working correctly (while `sharey` does work as expected).

Simple code snippet to reproduce:
```python
import pandas as pd

import seaborn as sns
from matplotlib import pyplot as plt

titanic = sns.load_dataset("titanic")
df = pd.melt(titanic, id_vars=["sex", "class"], value_vars=["fare", "age"])
sns.displot(
    data=df,
    x="value",
    col="variable",
    hue="sex",
    facet_kws={"sharex": False, "sharey": False},
)
plt.savefig("test.png")
```

The result is the following:

![test](https://user-images.githubusercontent.com/11348981/115027257-c6706c80-9ec3-11eb-95c1-19b27e0b0e46.png)

As you can see, the `y` axes have different values, while the `x` axes seem to be shared despite the `"sharex": False` keyword.

**Comment by mwaskom** [comment] 2021-04-16 13:52
Duplicate of #2553

**Closed by mwaskom** 2021-04-16 13:52 UTC

**Comment by RMeli** [comment] 2021-04-16 14:25
Thanks for pointing this out @mwaskom , sorry about that. 

However, the use of `common_bins=False` (suggested in #2472) does not seem to do the job here; `sharex=False` now seems to work, however the bin size is now different also across the `hue` (within the same graph).

And my situation is actually more similar to the following one, where I also have different rows:
```python
import pandas as pd

import seaborn as sns
from matplotlib import pyplot as plt

titanic = sns.load_dataset("titanic")
df = pd.melt(titanic, id_vars=["sex", "class"], value_vars=["fare", "age"])
sns.displot(
    data=df,
    x="value",
    col="variable",
    row="class",
    hue="sex",
    facet_kws={"sharex": False, "sharey": False},
    common_bins=False,
)
plt.savefig("test.png")
```

![test](https://user-images.githubusercontent.com/11348981/115038699-0f2e2280-9ed0-11eb-8dd1-25a8e5c6f431.png)

Is there a way to share bins across `hue` and `row`, but not across `col`?

**Comment by mwaskom** [comment] 2021-04-16 14:34
Well you can set the bin width you want to use, but for a deeper level of facet-specific parameterization you're going to need to use `FacetGrid` directly and loop over the facets while passing the specific kwargs you want to use for each one.

**Comment by RMeli** [comment] 2021-04-16 14:39
Ok, I'll try that. Thanks!

**Comment by RMeli** [comment] 2021-12-06 14:59
@mwaskom I've been using `FacetGrid` directly as you suggested above with some success, however I was not able to get a legend based on the `hue`. Essentially the same outcome described in #2472. Is there no way to get histograms that share axis across the different columns (i.e. same quantities plotted on a row, for different parameters) and have the same bin width, while also getting the legend according to the hue? I haven't been able to achieve this in any way so far. It's not possible at all because of the issues described in #2231?

**Comment by mwaskom** [comment] 2021-12-06 23:32
Hi @RMeli hard to advise without seeing code for your current solution. Could you make a reproducible example and ask on StackOverflow? It's an interesting task. Thanks.

**Comment by RMeli** [comment] 2021-12-07 08:08
I was about to post some code yesterday but realized it was quite similar to the code above, I think I'm running in circles... I'll post on StackOverflow, thanks.

**Comment by RMeli** [comment] 2021-12-07 11:06
For future reference: [share histogram bins across columns - StackOverflow](https://stackoverflow.com/questions/70259023/share-histogram-bins-across-columns)
