### ISSUE TITLE
Show two labels when only plot one-dimension array when using histplot

### ISSUE THREAD

**Issue by wzunknown** [mwaskom/seaborn#3260] opened 2023-02-15 10:36 UTC
```python
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Load example data
data = np.random.normal(size=100)

# Create histogram plot with legend label
sns.histplot(data, label='Total Bills')

# Add legend and set title
plt.legend(title="Legend Title")
plt.title("Histogram Plot with Single Legend Label")

# Show plot
plt.show()
```

The code gives me:
![image](https://user-images.githubusercontent.com/32328286/219003864-12eab7e3-71b9-4246-a70a-37e2a7a37b2b.png)

How can I let it show only one legend label? Thanks!

**Comment by mwaskom** [comment] 2023-02-15 11:53
Duplicate of https://github.com/mwaskom/seaborn/issues/3115

**Closed by mwaskom** 2023-02-15 11:53 UTC
