### ISSUE TITLE
Pairplot with diag_kind = "kde" worked with 0.9.0 but gives error in 0.10.0

### ISSUE THREAD

**Issue by PKHello** [mwaskom/seaborn#2037] opened 2020-04-22 20:55 UTC
Hi, 

Pairplot with diag_kind = "kde" used to work with version 0.9.0 but it fais with version 0.10.0.

Error message: RuntimeError: Selected KDE bandwidth is 0. Cannot estiamte density.

Current version: seaborn 0.10.0 ,  matplotlib 3.1.3

Dataset: Publicly available data of Wisconsin breast cancer
Dataset is attached. 
[breast-cancer-wisconsin.data.zip](https://github.com/mwaskom/seaborn/files/4518978/breast-cancer-wisconsin.data.zip)

Link to dataset: http://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Original)

Code Script:
 import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
col_names = ['id', 'Clump Thickness', 'Uniformity of Cell Size', 
       'Uniformity of Cell Shape', 'Marginal Adhesion', 
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class']
df = pd.read_csv("breast-cancer-wisconsin.data.csv", names=col_names,
                 header=None)
df['Bare Nuclei'].replace("?", np.NAN, inplace=True)
df = df.dropna()
import seaborn as sns
sns.pairplot(df , diag_kind = "kde", hue="Class")

Comment: The dataset contains discrete values with very less variation in values (but variation is not zero, the values vary from 1 to 10 though majority have repeating value hence Variance is low). Low variation is probably causing the error in KDE.

**Comment by mwaskom** [comment] 2020-04-22 21:00
This sounds like #1990 

I doubt there is a difference between seaborn versions, rather it is likely that you were not using statsmodels and now are.

**Comment by PKHello** [comment] 2020-04-23 20:22
I am not using statsmodel. The exact same code used to work before I did python upgrade. It now fails (I conduct trainings and I am using the same code before and after upgrade). 
To understand the reason better, (I suspected cause to be low variance), I manually changed values to cause more variance in data and then it works. But as of now it fails on the famous 'Wisconsin Breast Cancer dataset' (attached with the ticket).

**Comment by mwaskom** [comment] 2020-04-23 20:43
While you don't show the full traceback, the final error has a typo in it that matches the error raised from statsmodels in #1990, so I imagine that's what you're seeing.

Depending on how you updated seaborn, doing so may have installed statsmodels. It is technically an optional dependency and not included in the `setup.py` that I maintain, but some third party packages include it as a dependency (I know this is true of the conda-forge recipe, for instance).

Given that, I'm going to mark this as a duplicate of #1990; thanks for the report.

**Closed by mwaskom** 2020-04-23 20:43 UTC
