### ISSUE TITLE
Plotting conditional distribution with different hues

### ISSUE THREAD

**Issue by kwhkim** [mwaskom/seaborn#3551] opened 2023-11-07 02:41 UTC
When I'd like to visualize joint probability estimates(MLE) of categorical data,
I can go with the following 

```python
import statsmodels.api as sm # https://www.statsmodels.org/stable/api.html
import seaborn as sns

BankWages = sm.datasets.get_rdataset('BankWages', package='AER').data

sns.displot(kind='hist', row='minority', col='gender', 
            data=BankWages, x='job', 
            hue='job', shrink=0.8,
            stat='probability', 
            height=1.5, aspect=7/2/1.5)
```

But when I want to plot conditional probability estimates, I can go with the following but not with `hue='job'`

```
sns.displot(kind='hist', row='minority', col='gender', 
            data=BankWages, x='job', shrink=0.8,
            stat='probability', common_norm=False,
            height=1.5, aspect=7/2/1.5)
```

Since the following code will generate useless bar plot with all the heights equal to 1

```
sns.displot(kind='hist', row='minority', col='gender', 
            data=BankWages, x='job', 
            hue='job', shrink=0.8,
            stat='probability', common_norm=False,
            height=1.5, aspect=7/2/1.5)
```

So I suggest how about going the different path when the names for x and hue are the same 
when plotting a histogram with `common_norm=False`

**Comment by mwaskom** [comment] 2023-11-07 14:56
I don't understand what you are asking / proposing.

**Comment by thuiop** [comment] 2023-11-08 17:39
I think the issue here is that the hue is used as a grouping variable for `common_norm`, so in his last example the normalization is done both on row, col and hue, and since `job` has discrete values everything is equal to one.

The expected result can be achieved through the objects interface though :
```
import statsmodels.api as sm # https://www.statsmodels.org/stable/api.html
import seaborn.objects as so
import matplotlib.pyplot as plt

BankWages = sm.datasets.get_rdataset('BankWages', package='AER').data
p = (
	so.Plot(data=BankWages,x="job",color="job")
	.facet(row="minority",col="gender")
	.add(so.Bar(),so.Hist(stat="probability",common_norm=["row","col"]))
)
p.show()
```

Depending on the difficulty, it may be desirable to allow `common_norm` to be a list, as it can be in the objects interface (but I can see some issues, like the color/hue naming).

**Comment by mwaskom** [comment] 2023-11-09 01:12
> Depending on the difficulty, it may be desirable to allow common_norm to be a list

Yes this is a handy feature in the objects interface. It would be challenging to implement it in the existing code for the function interface. So that probably won't happen outside of a larger refactor to actually use the objects inside those functions.

There's actually already an open issue for this (https://github.com/mwaskom/seaborn/issues/2741) although someone should follow up to mention that the object interface route there.

**Comment by kwhkim** [comment] 2023-11-09 02:43
Looking through the code, I found work-around using `sns.FacetGrid()`, here's the code,

```python
BankWages['minority_cat'] = BankWages['minority'].astype('category')
BankWages['job_cat'] = BankWages['job'].astype('category')
# This makes color coding set to the common coding across columns or rows
def sns_histplotx(x, hue, **kwargs):
    ax = plt.gca()
    sns.histplot(x=x, hue=hue, ax=ax, **kwargs)
    return ax
fig_h = 3; fig_w = 7;
fg = sns.FacetGrid(BankWages, col='gender', legend_out=False,
                   height = fig_h, aspect=fig_w/fig_h/BankWages['gender'].nunique()) 
fg.map(sns_histplotx, 'job_cat', 'job_cat', 
       stat='probability', 
       discrete = True, shrink=0.8);
```

Except for the legend, everything seems fine. Any thought on how to add legend on the figure-level?

**Comment by thuiop** [comment] 2023-11-09 09:21
>  Any thought on how to add legend on the figure-level?
I fear it will be quite difficult to get the correct legend with this kind of setup, which is why I suggested the objects interface. If you really need one you probably need to build it for scratch ; you could also forego it since the color is redundant with the x-axis anyway. Other possibility is to do the statistical treatment yourself (e.g. using `groupby`) and then make a `catplot`.

**Comment by mwaskom** [comment] 2023-11-09 12:27
> I fear it will be quite difficult to get the correct legend with this kind of setup

Don't forget you can at least manually add legend handles:

```python
g = sns.FacetGrid(tips, col="time")
legend_data = {"A": mpl.patches.Patch(color="b"), "B": mpl.patches.Patch(color="r")}
g.add_legend(legend_data)
```
![image](https://github.com/mwaskom/seaborn/assets/315810/71761fb9-df97-47f0-a497-a8e4895a050c)

**Comment by mwaskom** [comment] 2023-11-18 19:24
I'm going to close this issue as a duplicate of https://github.com/mwaskom/seaborn/issues/2741 for tracking the potential expansion of normalizations in the function interface. Thanks!

**Closed by mwaskom** 2023-11-18 19:24 UTC
