### ISSUE TITLE
pairplot x_vars issue: First plot is not being displayed

### ISSUE THREAD

**Issue by RPunyatoya** [mwaskom/seaborn#2277] opened 2020-09-13 21:42 UTC
`iris = sns.load_dataset("iris")`
`sns.pairplot(data=iris, x_vars=['sepal_length', 'petal_length','petal_width'], y_vars=['sepal_width']);`
`sns.pairplot(data=iris, x_vars=['','sepal_length', 'petal_length','petal_width'], y_vars=['sepal_width']);`
`sns.pairplot(data=iris, x_vars=['sepal_length', '', 'petal_length','petal_width'], y_vars=['sepal_width']);`

First plot of pairplot is not being displayed when using multiple variables in [x_vars.]
(https://github.com/RPunyatoya/Seaborn-Issue/blob/master/Seaborn%200.11.0%20Issue.ipynb)
Also when giving wrong column name such as blank (''), It's not throwing any error instead just displaying empty plot in the 1st place where as getting appropriate error when providing '' as 2nd onward column name.

![Capture](https://user-images.githubusercontent.com/53420500/93029352-0f172d00-f638-11ea-835b-8e32cca3a8d5.PNG)

Thank you..!!

**Comment by mwaskom** [comment] 2020-09-13 21:58
Duplicate of https://github.com/mwaskom/seaborn/issues/2260, which has a workaround.

**Closed by mwaskom** 2020-09-13 21:58 UTC

**Comment by gunjank775** [comment] 2020-12-16 14:23
First plot is not being displayed... please help

**Comment by mmagnuski** [comment] 2020-12-16 18:24
@gunjank775 Help is just around the corner: look at the post immediately above yours and follow the link - you'll find an earlier report of this issue that also contains a workaround. :)

**Comment by gunjank775** [comment] 2020-12-16 18:29
@mmagnuski oh thanks

**Comment by HarishSreenivas** [comment] 2021-07-04 09:09
Hi. You can display the first plot using the below code:

sns.pairplot(diag_kind= None,data=iris, x_vars=['sepal_length', 'petal_length','petal_width'], y_vars=['sepal_width'])
plt.show()
