### ISSUE TITLE
Boxenplot hue stopped working?

### ISSUE THREAD

**Issue by mdastro** [mwaskom/seaborn#2164] opened 2020-07-13 17:55 UTC
Dear seaborners,

I was rerunning some code I had worked in the past with the letter-value plots (i.e. boxenplots) and some errors started to appear (errors that didn't exist in the past). The problem appears to be with the hue argument in boxenplot. I thought you had removed this feature, but I could still find it in the docstring.

The code is the following:

```
plt.rcParams.update(plotpars)
lvplot = sns.boxenplot(x=my_data['WHAN_CLASS'].values, y=my_data['D4000N'].values, data=my_data, palette=palette_c,
                       hue=my_data['UV_CLASS_YI2011'], 
                       order=['Unclassified', 'Retired/Passive', 'wAGN', 'sAGN', 'SF'], 
                       k_depth='trustworthy', outlier_prop=0.2, scale='exponential', saturation=0.8)
plt.xticks([0,1,2,3,4], ['Unclass.', 'R/P', 'wAGN', 'sAGN', 'SF'])
plt.xlabel("WHAN class")
plt.ylabel("D$_n$4000")
lvplot.legend(loc='lower right', borderaxespad=0.2, ncol=2)
plt.ylim([0,3.5])
plt.tight_layout()
plt.savefig(os.path.join(figs_paper_path, 'lvplot_dn4000.png'), bbox_inch='tight')
plt.savefig(os.path.join(figs_paper_path, 'lvplot_dn4000.pdf'), bbox_inch='tight')
plt.show()

```

which used to produce the following image:

[lvplot_dn4000.pdf](https://github.com/mwaskom/seaborn/files/4914218/lvplot_dn4000.pdf)

Now, the following error appears:

```
---------------------------------------------------------------------------
IndexingError                             Traceback (most recent call last)
<ipython-input-32-b3d65df2d58f> in <module>
      3                        hue=my_data['UV_CLASS_YI2011'],
      4                        order=['Unclassified', 'Retired/Passive', 'wAGN', 'sAGN', 'SF'],
----> 5                        k_depth='trustworthy', outlier_prop=0.2, scale='exponential', saturation=0.8)
      6 plt.xticks([0,1,2,3,4], ['Unclass.', 'R/P', 'wAGN', 'sAGN', 'SF'])
      7 plt.xlabel("WHAN class")

~/anaconda3/lib/python3.7/site-packages/seaborn/categorical.py in boxenplot(x, y, hue, data, order, hue_order, orient, color, palette, saturation, width, dodge, k_depth, linewidth, scale, outlier_prop, showfliers, ax, **kwargs)
   2630         ax = plt.gca()
   2631 
-> 2632     plotter.plot(ax, kwargs)
   2633     return ax
   2634 

~/anaconda3/lib/python3.7/site-packages/seaborn/categorical.py in plot(self, ax, boxplot_kws)
   2060     def plot(self, ax, boxplot_kws):
   2061         """Make the plot."""
-> 2062         self.draw_letter_value_plot(ax, boxplot_kws)
   2063         self.annotate_axes(ax)
   2064         if self.orient == "h":

~/anaconda3/lib/python3.7/site-packages/seaborn/categorical.py in draw_letter_value_plot(self, ax, kws)
   2039 
   2040                     hue_mask = self.plot_hues[i] == hue_level
-> 2041                     box_data = remove_na(group_data[hue_mask])
   2042 
   2043                     # Handle case where there is no non-null data

~/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in __getitem__(self, key)
    906 
    907         if com.is_bool_indexer(key):
--> 908             key = check_bool_indexer(self.index, key)
    909 
    910         return self._get_with(key)

~/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py in check_bool_indexer(index, key)
   2316         if mask.any():
   2317             raise IndexingError(
-> 2318                 "Unalignable boolean Series provided as "
   2319                 "indexer (index of the boolean Series and of "
   2320                 "the indexed object do not match)."

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
```

Do you have any insights on what may be going on? If I remove the hue argument, this issue goes away.

Thanks!

**Comment by mwaskom** [comment] 2020-07-13 20:42
Hi could you please specify the version of seaborn you are using and make the example reproducible? Thank you!

**Comment by mdastro** [comment] 2020-07-13 20:51
Sure, it's version 0.10.1.

Thank you!

**Comment by MaozGelbart** [comment] 2020-07-17 13:05
Hi @mdastro ,

I noticed you're using individual Series or numpy arrays in your `boxenplot` call in addition to providing `my_data` dataframe. Try passing x, y and hue as string identifiers to columns in `my_data`:
```python
lvplot = sns.boxenplot(x='WHAN_CLASS', y='D4000N', data=my_data, palette=palette_c,
                       hue='UV_CLASS_YI2011', 
                       order=['Unclassified', 'Retired/Passive', 'wAGN', 'sAGN', 'SF'], 
                       k_depth='trustworthy', outlier_prop=0.2, scale='exponential', saturation=0.8)
```
I suspect the error you see due to misaligned indexing between pandas Series and numpy arrays (obtained by using `.values`).

I hope this may resolve your issue.

**Comment by mdastro** [comment] 2020-07-28 16:43
Hi, sorry for the delay. I am submitting my PhD thesis this week and things have been hectic. I'll answer you next week for sure. Please, don't close the issue just yet. 

Thanks!

**Comment by mwaskom** [comment] 2020-07-28 16:47
OK, but to answer your question: no the feature hasn't been removed, and I think @MaozGelbart's suggestion likely has a hint to the underlying problem you're running into.

**Comment by mwaskom** [comment] 2020-08-18 22:05
Closing for lack of information and likelihood that it's not a problem in seaborn, but do ping if you can come up with a reproducible example that suggests otherwise.

**Closed by mwaskom** 2020-08-18 22:05 UTC
Labels: mod:categorical, question
