### ISSUE TITLE
row_template doesn't work for FactorGrid when margin_titles=True

### ISSUE THREAD

**Issue by napsternxg** [mwaskom/seaborn#1062] opened 2016-10-31 02:21 UTC
When using `row_template` on FactorGrid when `margin_titles=True`, row_template will not render correctly as the earlier call to finalize_grid already creates an annotated text for the row margin (See: https://github.com/mwaskom/seaborn/blob/v0.7.1/seaborn/axisgrid.py#L731)

I think a fix will be to add a switch to map function which will ask if titles need to created. Another, option will be to keep track of the created row titles and edit their text (as they are created using ax.annotate https://github.com/mwaskom/seaborn/blob/v0.7.1/seaborn/axisgrid.py#L939)

Code for replication:

```
df = pd.DataFrame(np.random.choice(["a", "b", "c"], size=(10,2)), columns=["col1", "col2"])
df["col_value"]=np.random.randint(10, size=df.shape[0])
g = (sns.FacetGrid(row="col1", col="col2", aspect=1.5, margin_titles=True,
                  data=df)
g = g.map(plt.hist, "col_value", bins=range(10))
g = g.set_titles(template="", col_template="{col_name}", row_template="{row_name}")
g.fig.tight_layout()
```

**Comment by mwaskom** [comment] 2016-11-29 16:16
Duplicate of https://github.com/mwaskom/seaborn/issues/509

**Closed by mwaskom** 2016-11-29 16:16 UTC
