### ISSUE TITLE
Lineplot, errorbar with multiple variables.

### ISSUE THREAD

**Issue by Raycoms** [mwaskom/seaborn#3583] opened 2023-12-05 09:01 UTC
I wanted to display a classic lineplot with errorbars with seaborn with my data structured a bit like this:

array approach (a,a,a,a,b,b,b,b)
array clients(7000,7000,700,700,7000,7000,700,700)
array latency (......)
array throughput(......)

So, I increase the load by increasing the number of clients. So, I was expecting that seaborn was be able to calculate the mean of each configuration (client/approach) and display the errorbar. Instead, seaborn plotted every single value (all 4 observations per client load) instead of the mean observation by client load

**Comment by thuiop** [comment] 2023-12-05 09:30
Hello, please provide a reproducible example so we can provide help. I am really unsure what the problem is and what you are trying to do in the first place.

**Comment by mwaskom** [comment] 2023-12-09 12:46
Closing as this sounds like a basic "how do I ..." question not a bug report, and there's not enough information here to provide any help. I recommend putting together a clear question with a reproducible example and asking on stackoverflow.

**Closed by mwaskom** 2023-12-09 12:46 UTC
Labels: needs-reprex
