### ISSUE TITLE
diverging_palette() return TypeError when working in numpy version 1.18.1

### ISSUE THREAD

**Issue by TS32** [mwaskom/seaborn#1919] opened 2020-01-10 06:04 UTC
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32,

>>> import seaborn as sns
>>> import numpy as np

>>> sns.__version__
'0.9.0'
>>> np.__version__
'1.18.1'

>>> sns.palplot(sns.diverging_palette(150, 275, s=80, l=55, n=9))

Traceback (most recent call last):
  File "C:\Users\Test\.conda\envs\Python37\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Test\.conda\envs\Python37\lib\site-packages\seaborn\palettes.py", line 744, in diverging_palette
    neg = palfunc((h_neg, s, l), 128 - (sep / 2), reverse=True, input="husl")
  File "C:\Users\Test\.conda\envs\Python37\lib\site-packages\seaborn\palettes.py", line 641, in light_palette
    return blend_palette(colors, n_colors, as_cmap)
  File "C:\Users\Test\.conda\envs\Python37\lib\site-packages\seaborn\palettes.py", line 777, in blend_palette
    pal = _ColorPalette(pal(np.linspace(0, 1, n_colors)))
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\Users\Test\.conda\envs\Python37\lib\site-packages\numpy\core\function_base.py", line 121, in linspace.format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

**Comment by mwaskom** [comment] 2020-01-10 12:32
This is a duplicate of #1907 and fixed in master by #1912

**Closed by mwaskom** 2020-01-10 12:32 UTC
