### ISSUE TITLE
Seaborn error

### ISSUE THREAD

**Issue by meyringer** [mwaskom/seaborn#1945] opened 2020-01-23 16:17 UTC
I am trying to use seaborn in a python standard shell environment , but I always get an error when I use the basis palette function

sns.palplot(sns.diverging_palette(240, 10, n=9))

any Idea from where this could come from ???

Traceback (most recent call last):
  File "C:\Users\meyringer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/meyringer/AppData/Local/Programs/Python/Python37-32/seabornpalette.py", line 3, in <module>
    sns.palplot(sns.diverging_palette(240, 10, n=9))
  File "C:\Users\meyringer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\seaborn\palettes.py", line 744, in diverging_palette
    neg = palfunc((h_neg, s, l), 128 - (sep / 2), reverse=True, input="husl")
  File "C:\Users\meyringer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\seaborn\palettes.py", line 641, in light_palette
    return blend_palette(colors, n_colors, as_cmap)
  File "C:\Users\meyringer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\seaborn\palettes.py", line 777, in blend_palette
    pal = _ColorPalette(pal(np.linspace(0, 1, n_colors)))
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\Users\meyringer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

**Comment by mwaskom** [comment] 2020-01-23 16:30
Duplicate of #1907

**Closed by mwaskom** 2020-01-23 16:30 UTC
