### ISSUE TITLE
Heatmap reversed in subplots when sharing y axis

### ISSUE THREAD

**Issue by gitvishy** [mwaskom/seaborn#1784] opened 2019-07-28 21:41 UTC
I'm trying to plot side-by-side heatmaps and I'm seeing this problem when `sharey=True`. The ordering of the data in all but the last subplot is reversed. But because the y axis is shared, the overall figure displays incorrectly.

```python
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df1 = pd.DataFrame(np.random.random((10,10,)))
df1.loc[2] = 0
df2 = pd.DataFrame(np.random.random((10,10,)))
df2.loc[7] = 0
```
Without `sharey=True`
```python
fig, ax = plt.subplots(1,2)
sns.heatmap(df1, ax=ax[0])
sns.heatmap(df2, ax=ax[1]);
```
Correctly shows as
![image](https://user-images.githubusercontent.com/2991876/62012940-058be680-b152-11e9-8e20-839efedcd9b8.png)

With `sharey=True`
```python
fig, ax = plt.subplots(1,2, sharey=True)
sns.heatmap(df1, ax=ax[0])
sns.heatmap(df2, ax=ax[1]);
```
shows as 
![image](https://user-images.githubusercontent.com/2991876/62012996-ab3f5580-b152-11e9-81c1-4a00be683bff.png)

The y axis on the left is reversed (and correctly labeled). But the values on the right are not reversed and because the y is shared, it is incorrect.

I can't tell if this related to https://github.com/mwaskom/seaborn/issues/1306

I found this issue after looking at 
https://stackoverflow.com/questions/28356359/one-colorbar-for-seaborn-heatmaps-in-subplot

Using the code from the accepted answer (from mwaskom), 

```python
fig, axn = plt.subplots(2, 2, sharex=True, sharey=True)
cbar_ax = fig.add_axes([.91, .3, .03, .4])

for i, ax in enumerate(axn.flat):
    sns.heatmap(df1, ax=ax,
                cbar=i == 0,
                vmin=0, vmax=1,
                cbar_ax=None if i else cbar_ax)
```
![image](https://user-images.githubusercontent.com/2991876/62013072-957e6000-b153-11e9-95d3-c2942ec7661e.png)

I'm getting plots 1, 2, 3 are reversed and 4 is okay. But in the original stackoverflow answer, all plots are okay (identical), so perhaps this is a bug in a recent version of seaborn?

I'm using seaborn 0.9.0, matplotlib 3.1.0, python 3.7.3 on Mac OS X 10.14.5.

**Comment by mwaskom** [comment] 2019-07-28 22:10
Duplicate of #1771

**Closed by mwaskom** 2019-07-28 22:10 UTC
