### ISSUE TITLE
AttributeError : Seaborn

### ISSUE THREAD

**Issue by hkb111** [mwaskom/seaborn#2310] opened 2020-10-07 14:20 UTC
sns.set_theme(style="ticks")
sns.pairplot(df)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-102-2c212b079315> in <module>
----> 1 sns.set_theme(style="ticks")
      2 sns.pairplot(df)

**AttributeError: module 'seaborn' has no attribute 'set_theme'**

I have got this error while using seaborn.

**Comment by mwaskom** [comment] 2020-10-07 14:22
Duplicate of #2301

**Closed by mwaskom** 2020-10-07 14:22 UTC
