### ISSUE TITLE
sns.distplot(tips['total_bill']) Y-Axis Values

### ISSUE THREAD

**Issue by alibinkhalid** [mwaskom/seaborn#2011] opened 2020-03-30 20:56 UTC
While creating a distplot on 'Tips' dataset on 'Total_Bills' column the Y axis values in the chart appear in decimal while I am expecting it to provide the counts.

I am using the following code:

`import seaborn as sns
%matplotlib inline
tips = sns.load_dataset('tips')
sns.distplot(tips['total_bill'],bins=10,norm_hist=False)`

which gives following output:
![New_Book_Same_Cell](https://user-images.githubusercontent.com/33238033/77960555-3a28f100-7324-11ea-9f74-68af6e1c930f.PNG)

while I am expecting the y axis to show the values as per below. 
![Expected Output](https://user-images.githubusercontent.com/33238033/77960814-a146a580-7324-11ea-8f2f-e96a9104f3c3.PNG)

Following Troubleshooting steps were performed:

1. Restart Kernel and Run All Cells
2. Copy the entire code in One Cell
3. Open a new Jupyter Notebook to wrote the code again.
4. Explicitly mentioned norm_hist = False in the argument

But none of these work. Why by default does it show values like 0.01, 0.02, 0.03 .... 0.06 on the y-axis?

**Comment by mwaskom** [comment] 2020-03-30 23:14
This is a duplicate of #1288. As the docs for `norm_hist` say:

> If True, the histogram height shows a density rather than a count. This is implied if a KDE or fitted density is plotted.

**Closed by mwaskom** 2020-03-30 23:14 UTC
