### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by NiranjanAgaram** [mwaskom/seaborn#1563] opened 2018-09-12 00:30 UTC
I'm trying to plot a seaborn histogram using the following command to get the gaussian kernel density estimation.
 
`sns.distplot(df['charges'], kde=True)`

I'm using 

- seaborn version 0.7.1
- windows machine
- jupyter notebooks

I'm getting the following error and I only see histogram but not kde.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-7ce1443b0805> in <module>()
----> 1 sns.distplot(df['charges'], bins=50, kde=True)

C:\Users\Niranjan\Anaconda3\lib\site-packages\seaborn\distributions.py in distplot(a, bins, hist, kde, rug, fit, hist_kws, kde_kws, rug_kws, fit_kws, color, vertical, norm_hist, axlabel, label, ax)
    219     if kde:
    220         kde_color = kde_kws.pop("color", color)
--> 221         kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
    222         if kde_color != color:
    223             kde_kws["color"] = kde_color

C:\Users\Niranjan\Anaconda3\lib\site-packages\seaborn\distributions.py in kdeplot(data, data2, shade, vertical, kernel, bw, gridsize, cut, clip, legend, cumulative, shade_lowest, ax, **kwargs)
    602         ax = _univariate_kdeplot(data, shade, vertical, kernel, bw,
    603                                  gridsize, cut, clip, legend, ax,
--> 604                                  cumulative=cumulative, **kwargs)
    605 
    606     return ax

C:\Users\Niranjan\Anaconda3\lib\site-packages\seaborn\distributions.py in _univariate_kdeplot(data, shade, vertical, kernel, bw, gridsize, cut, clip, legend, ax, cumulative, **kwargs)
    268         x, y = _statsmodels_univariate_kde(data, kernel, bw,
    269                                            gridsize, cut, clip,
--> 270                                            cumulative=cumulative)
    271     else:
    272         # Fall back to scipy if missing statsmodels

C:\Users\Niranjan\Anaconda3\lib\site-packages\seaborn\distributions.py in _statsmodels_univariate_kde(data, kernel, bw, gridsize, cut, clip, cumulative)
    326     fft = kernel == "gau"
    327     kde = smnp.KDEUnivariate(data)
--> 328     kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
    329     if cumulative:
    330         grid, y = kde.support, kde.cdf

C:\Users\Niranjan\Anaconda3\lib\site-packages\statsmodels\nonparametric\kde.py in fit(self, kernel, bw, fft, weights, gridsize, adjust, cut, clip)
    144             density, grid, bw = kdensityfft(endog, kernel=kernel, bw=bw,
    145                     adjust=adjust, weights=weights, gridsize=gridsize,
--> 146                     clip=clip, cut=cut)
    147         else:
    148             density, grid, bw = kdensity(endog, kernel=kernel, bw=bw,

C:\Users\Niranjan\Anaconda3\lib\site-packages\statsmodels\nonparametric\kde.py in kdensityfft(X, kernel, bw, weights, gridsize, adjust, clip, cut, retgrid)
    504     zstar = silverman_transform(bw, gridsize, RANGE)*y # 3.49 in Silverman
    505                                                    # 3.50 w Gaussian kernel
--> 506     f = revrt(zstar)
    507     if retgrid:
    508         return f, grid, bw

C:\Users\Niranjan\Anaconda3\lib\site-packages\statsmodels\nonparametric\kdetools.py in revrt(X, m)
     18     if m is None:
     19         m = len(X)
---> 20     y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
     21     return np.fft.irfft(y)*m
     22 

TypeError: slice indices must be integers or None or have an __index__ method

**Comment by mwaskom** [comment] 2018-09-12 12:49
Duplicate of #1103

**Closed by mwaskom** 2018-09-12 12:49 UTC
