### ISSUE TITLE
help! violinplot stack trace

### ISSUE THREAD

**Issue by paulathomas** [mwaskom/seaborn#1400] opened 2018-04-07 00:45 UTC
Hi,

Firstly great library!

However I have a stack trace when trying to do a vilolinplot that I can't fathom.

my dataframe.head  is:

  | delta | winner
-- | -- | --
Aberdeen North |18999 | Lab
Aberdeen South|13721 | Lab
Airdrie and Shotts |4900 | Lab
Angus |6103 | SNP
Argyle & Bute |4367 | LD

I want to do a volinplot for delta catagorized by winner so

import seaborn as sn
sn.violinplot(y="delta",x="winner",data=df_delta,ax=ax)

which gives

AttributeError                            Traceback (most recent call last)
<ipython-input-47-8dd32899e5f9> in <module>()
      2 ax=fig.add_subplot(1,1,1)
      3 #sn.violinplot(data=df_delta,ax=ax)
----> 4 sn.violinplot(y="delta",x="winner",data=df_delta,ax=ax)

/usr/local/lib/python3.6/dist-packages/seaborn/categorical.py in violinplot(x, y, hue, data, order, hue_order, bw, cut, scale, scale_hue, gridsize, width, inner, split, dodge, orient, linewidth, color, palette, saturation, ax, **kwargs)
   2362                              bw, cut, scale, scale_hue, gridsize,
   2363                              width, inner, split, dodge, orient, linewidth,
-> 2364                              color, palette, saturation)
   2365 
   2366     if ax is None:

/usr/local/lib/python3.6/dist-packages/seaborn/categorical.py in __init__(self, x, y, hue, data, order, hue_order, bw, cut, scale, scale_hue, gridsize, width, inner, split, dodge, orient, linewidth, color, palette, saturation)
    557         self.establish_variables(x, y, hue, data, orient, order, hue_order)
    558         self.establish_colors(color, palette, saturation)
--> 559         self.estimate_densities(bw, cut, scale, scale_hue, gridsize)
    560 
    561         self.gridsize = gridsize

/usr/local/lib/python3.6/dist-packages/seaborn/categorical.py in estimate_densities(self, bw, cut, scale, scale_hue, gridsize)
    623 
    624                 # Fit the KDE and get the used bandwidth size
--> 625                 kde, bw_used = self.fit_kde(kde_data, bw)
    626 
    627                 # Determine the support grid and get the density over it

/usr/local/lib/python3.6/dist-packages/seaborn/categorical.py in fit_kde(self, x, bw)
    710         # Allow for the use of old scipy where `bw` is fixed
    711         try:
--> 712             kde = stats.gaussian_kde(x, bw)
    713         except TypeError:
    714             kde = stats.gaussian_kde(x)

/usr/local/lib/python3.6/dist-packages/scipy/stats/kde.py in __init__(self, dataset, bw_method)
    170 
    171         self.d, self.n = self.dataset.shape
--> 172         self.set_bandwidth(bw_method=bw_method)
    173 
    174     def evaluate(self, points):

/usr/local/lib/python3.6/dist-packages/scipy/stats/kde.py in set_bandwidth(self, bw_method)
    497             raise ValueError(msg)
    498 
--> 499         self._compute_covariance()
    500 
    501     def _compute_covariance(self):

/usr/local/lib/python3.6/dist-packages/scipy/stats/kde.py in _compute_covariance(self)
    507         if not hasattr(self, '_data_inv_cov'):
    508             self._data_covariance = atleast_2d(np.cov(self.dataset, rowvar=1,
--> 509                                                bias=False))
    510             self._data_inv_cov = linalg.inv(self._data_covariance)
    511 

/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py in cov(m, y, rowvar, bias, ddof, fweights, aweights)
   3083             w *= aweights
   3084 
-> 3085     avg, w_sum = average(X, axis=1, weights=w, returned=True)
   3086     w_sum = w_sum[0]
   3087 

/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
   1161 
   1162     if returned:
-> 1163         if scl.shape != avg.shape:
   1164             scl = np.broadcast_to(scl, avg.shape).copy()
   1165         return avg, scl

AttributeError: 'float' object has no attribute 'shape'

**Comment by paulathomas** [comment] 2018-04-07 19:53
mwaskom

Thanks for the reply.

 There are 650 rows each similar to the 5 included in my post. If you'd like me to send it to you, I can but would require precise instructions on saving the dataframe to disc. (I know of ways to do this but need to know which you want me to use.)

I have since come to the conclusion that this is either a pandas or matplotlib issue as I get the same error when I pass this dataframe to pyplot's violinplot. Should I keep this issue open or raise a new issue on pandas or matplotlib (which?).

**Comment by mwaskom** [comment] 2018-04-07 19:57
My suspicion is that it's probably a problem with the dataset itself, and not a bug in one of the libraries. The first step would be to rule that out yourself or to ask for help on stackoverflow.

But nobody will be able to help you without seeing the data. To share it, you should save it to a csv file. Ensure that when you write the csv file out and then read it back in, you can reproduce the bug you are getting (or else nobody else will be able to).

Since it doesn't seem to be a seaborn problem, I'm going to close this issue.

**Closed by mwaskom** 2018-04-07 19:57 UTC
