### ISSUE TITLE
Swarmplot online docs uses "dodge" in example for "split" keyword

### ISSUE THREAD

**Issue by tamir-dingjan** [mwaskom/seaborn#1336] opened 2017-11-30 06:04 UTC
The  [online docs page for swarmplot](https://seaborn.pydata.org/generated/seaborn.swarmplot.html#) uses "dodge" in an example of the behaviour of "split".

Copied from the doc page:

> **_Split_** each level of the hue variable along the categorical axis:
> 
> > ax = sns.swarmplot(x="day", y="total_bill", hue="smoker",
> ...                    data=tips, palette="Set2", **_dodge_**=True)

**Comment by mwaskom** [comment] 2017-11-30 13:11
Duplicate of https://github.com/mwaskom/seaborn/issues/1278

**Closed by mwaskom** 2017-11-30 13:11 UTC
