### ISSUE TITLE
import seaborn error-ValueError: underlying buffer has been detached

### ISSUE THREAD

**Issue by Jethi** [mwaskom/seaborn#1201] opened 2017-06-12 06:00 UTC
Hi @mwaskom ,

I raised an issue regarding importing seaborn error https://github.com/mwaskom/seaborn/issues/1200
while trying to run the flask application in IIS server. However since I couldn't provide much information at that time you couldn't help me. Sorry for late reply.

But I tried to log the traceback error caused due to importing seaborn. Results are below. Any help regarding this?

Traceback (most recent call last):
File ".\test.py", line 62, in 
import seaborn as sns
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn_init_.py", line 16, in 
from .widgets import *
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\widgets.py", line 8, in 
from ipywidgets import interact, FloatSlider, IntSlider
File "C:\ProgramData\Anaconda3\lib\site-packages\ipywidgets_init_.py", line 23, in 
from IPython import get_ipython
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython_init_.py", line 49, in 
from .terminal.embed import embed
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 17, in 
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 62, in 
from IPython.utils import io
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 97, in 
stdin = IOStream(sys.stdin, fallback=devnull)
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 41, in init
for meth in filter(clone, dir(stream)):
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 40, in clone
return not hasattr(self, meth) and not meth.startswith('_')
File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 84, in closed
return self.stream.closed
ValueError: underlying buffer has been detached

Eagerly waiting for your insights into this.

**Comment by mwaskom** [comment] 2017-06-12 14:26
Duplicate of #1200

**Closed by mwaskom** 2017-06-12 14:26 UTC
