### ISSUE TITLE
pandas sparse data doesn't plot in some plots

### ISSUE THREAD

**Issue by nickwan** [mwaskom/seaborn#1373] opened 2018-02-09 19:27 UTC
Ran into a strange issue today when trying to plot data after I sparsified a pandas DataFrame (i.e. df.to_sparse(fill_value=0)). When using sns.jointplot(), a sparse DataFrame would plot fine but when plotting an sns.regplot() it would either throw an error or plot nothing. However, when I convert a sparse matrix into a dense matrix, the plots are fine. 

Attached is a notebook where I reproduce this problem. 
https://github.com/nickwan/seaborn_and_pandas_sparse/blob/master/seaborn_and_pandas_sparse.ipynb

**Comment by mwaskom** [comment] 2018-02-09 19:37
So the first error seems to be on the matplotlib side:

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-152-468218c20775> in <module>()
----> 1 sns.regplot("A", "B", df)

~/anaconda/lib/python3.6/site-packages/seaborn/regression.py in regplot(x, y, data, x_estimator, x_bins, x_ci, scatter, fit_reg, ci, n_boot, units, order, logistic, lowess, robust, logx, x_partial, y_partial, truncate, dropna, x_jitter, y_jitter, label, color, marker, scatter_kws, line_kws, ax)
    787     scatter_kws["marker"] = marker
    788     line_kws = {} if line_kws is None else copy.copy(line_kws)
--> 789     plotter.plot(ax, scatter_kws, line_kws)
    790     return ax
    791 

~/anaconda/lib/python3.6/site-packages/seaborn/regression.py in plot(self, ax, scatter_kws, line_kws)
    337         # Draw the constituent plots
    338         if self.scatter:
--> 339             self.scatterplot(ax, scatter_kws)
    340         if self.fit_reg:
    341             self.lineplot(ax, line_kws)

~/anaconda/lib/python3.6/site-packages/seaborn/regression.py in scatterplot(self, ax, kws)
    366 
    367             x, y = self.scatter_data
--> 368             ax.scatter(x, y, **kws)
    369         else:
    370             # TODO abstraction

~/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1715                     warnings.warn(msg % (label_namer, func.__name__),
   1716                                   RuntimeWarning, stacklevel=2)
-> 1717             return func(ax, *args, **kwargs)
   1718         pre_doc = inner.__doc__
   1719         if pre_doc is None:

~/anaconda/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   3950         y = np.ma.ravel(y)
   3951         if x.size != y.size:
-> 3952             raise ValueError("x and y must be the same size")
   3953 
   3954         if s is None:

ValueError: x and y must be the same size
```

The issue is that for pandas sparse series the `size` attribute gives the number of filled entires, not the shape of the array itself.

```
print(df.A.shape)
print(df.A.size)

(100,)
98
```

```
print(df.A.to_dense().shape)
print(df.A.to_dense().size)

(100,)
100
```

**Comment by mwaskom** [comment] 2018-02-09 19:38
And actually I can't replicate the empty plot with `fit_reg=False` ... I get the same error.

**Comment by mwaskom** [comment] 2018-02-19 17:17
Closing as apparently not a seaborn issue.

**Closed by mwaskom** 2018-02-19 17:17 UTC

**Comment by xpe** [comment] 2018-03-22 21:23
@nickwan Did you file a bug elsewhere? Based on some bugs I've been seeing with Pandas `SparseDataFrame`, I think it would be useful to file your bug with the appropriate project.
