### ISSUE TITLE
The top and bottom rows of ClusterGrid are truncated by half

### ISSUE THREAD

**Issue by sangaline** [mwaskom/seaborn#1778] opened 2019-07-17 20:10 UTC
I'm running this code from [Discovering structure in heatmap data](https://seaborn.pydata.org/examples/structured_heatmap.html) example in the gallery.

```python
%pylab inline

import pandas as pd
import seaborn as sns
sns.set()

# Load the brain networks example dataset
df = sns.load_dataset("brain_networks", header=[0, 1, 2], index_col=0)

# Select a subset of the networks
used_networks = [1, 5, 6, 7, 8, 12, 13, 17]
used_columns = (df.columns.get_level_values("network")
                          .astype(int)
                          .isin(used_networks))
df = df.loc[:, used_columns]

# Create a categorical palette to identify the networks
network_pal = sns.husl_palette(8, s=.45)
network_lut = dict(zip(map(str, used_networks), network_pal))

# Convert the palette to vectors that will be drawn on the side of the matrix
networks = df.columns.get_level_values("network")
network_colors = pd.Series(networks, index=df.columns).map(network_lut)

# Draw the full plot
sns.clustermap(df.corr(), center=0, cmap="vlag",
               row_colors=network_colors, col_colors=network_colors,
               linewidths=.75, figsize=(13, 13))
```

When I run it, the top and bottom rows are truncated by half causing all of the rows to slightly misalign with the dendrograms.

![image](https://user-images.githubusercontent.com/8236564/61407939-c2995b80-a893-11e9-9b05-6052333f857a.png)

This is with the latest release `0.9.0` and matplotlib version `3.1.1`.

**Comment by mwaskom** [comment] 2019-07-17 20:53
Duplicate of #1773

**Closed by mwaskom** 2019-07-17 20:53 UTC
