### ISSUE TITLE
How does Seaborn Clustermap compute linkages?

### ISSUE THREAD

**Issue by nkanrar** [mwaskom/seaborn#2209] opened 2020-08-20 04:12 UTC
Hi, thanks for making Seaborn, it's an amazing package! I've been using the clustermap function to visualize a distance matrix. I initially wanted to pass the linkage I compute with SciPy hierarchical clustering's linkage function. I also used the linkage generated by the Seaborn clustermap function itself, with the same method and metric I used for scipy's linkage function, and got an entirely different linkage. 
I was wonder how exactly (what underlying packages and functions) Seaborn clustermap computes row and column linkages? 
I am attaching the Seaborn clustermap with the seaborn linkages here:
![0 05_seaborn](https://user-images.githubusercontent.com/65882575/90715986-a3bc8400-e260-11ea-9612-9011f2065bff.png)

Here are the linkages I get with Scipy:
![0 05_linkage](https://user-images.githubusercontent.com/65882575/90716002-ad45ec00-e260-11ea-9305-7281ef4f35d4.png)

Both were computed with the metric Euclidean and the method average.

**Comment by mwaskom** [comment] 2020-08-20 15:31
If the `fastcluster` library is installed, seaborn uses that instead of `scipy`. This may not be clearly documented. Beyond that, I can't speculate about what's causing the differences you see because you didn't share a reproducible example.

**Comment by mwaskom** [comment] 2020-09-02 17:06
Closing for lack of information but comment if you can come up with a reproducible example that demonstrates the issue.

**Closed by mwaskom** 2020-09-02 17:06 UTC
Labels: mod:matrix, question
