### ISSUE TITLE
heatmap cutoff vertical in seaborn 0.9

### ISSUE THREAD

**Issue by haraldschilly** [mwaskom/seaborn#1835] opened 2019-09-16 12:03 UTC
Running this code in a jupyter notebook plots a heatmap which is cutoff at the top and bottom -- horizontal view is ok.

```
data=np.array([[7.49377179e-10, 5.04982270e-02, 8.41080502e-01, 1.08421271e-01],
    [6.33214717e-02, 6.86063645e-01, 1.57489835e-01, 9.31250485e-02],
    [1.42185280e-02, 1.06747920e-01, 8.38806192e-01, 4.02273604e-02],
    [7.81118162e-01, 1.28774739e-32, 4.47694456e-24, 2.18881838e-01]])
sns.heatmap(data,annot=True,fmt='.2f',cmap='Reds',vmin=0,vmax=1,cbar=False,mask=(data<0.01))
```

* seaborn 0.9.0
* matplotlib 3.1.1

![Screenshot from 2019-09-16 14-02-35](https://user-images.githubusercontent.com/207405/64956372-acefe480-d88a-11e9-8847-f20cebe3815d.png)

**Comment by mwaskom** [comment] 2019-09-16 14:07
This is a matplotlib bug and a duplicate of numerous seaborn issues that will turn up with a quick search.

**Closed by mwaskom** 2019-09-16 14:07 UTC
