### ISSUE TITLE
seaborn.countplot orientation

### ISSUE THREAD

**Issue by techshot25** [mwaskom/seaborn#1938] opened 2020-01-20 20:47 UTC
The `orient` method in countplot does not work. Pass a list like:
`['Rose', 'Teal', 'Teal', 'Orange', 'Orange', 'Orange']` and try to adjust the orientation to see the issue.

**Comment by mwaskom** [comment] 2020-01-20 20:48
Duplicate of https://github.com/mwaskom/seaborn/issues/654. While the issue was obvious in this case, please provide a reproducible example in any future bug reports.

**Closed by mwaskom** 2020-01-20 20:48 UTC
