### ISSUE TITLE
rugplot plots nothing in version 0.10.0

### ISSUE THREAD

**Issue by dounykim** [mwaskom/seaborn#2032] opened 2020-04-21 06:38 UTC
Seaborn rugplot plot nothing in version 0.10.0

Same code works fine under 0.9.0 and I checked https://seaborn.pydata.org/whatsnew.html to find out if there was an update regarding rugplot but there wasn't.

```
import seaborn
from matplotlib import pyplot
iris = seaborn.load_dataset('iris')

x = iris.petal_length.values

seaborn.rugplot(x)
pyplot.show()
```
![2](https://user-images.githubusercontent.com/32084214/79833302-18340300-83e6-11ea-8563-f4fd4a0b0920.png)
![1](https://user-images.githubusercontent.com/32084214/79833313-19fdc680-83e6-11ea-9515-3472603628a8.png)

**Comment by mwaskom** [comment] 2020-04-21 12:23
This is a duplicate of https://github.com/mwaskom/seaborn/issues/2015; it's actually a matplotlib bug that I believe is fixed now.

**Comment by dounykim** [comment] 2020-04-23 21:02
I just updated matplotlib to latest version which is 3.2.1 and still get the same error.

**Comment by mwaskom** [comment] 2020-04-23 22:33
I don't believe that matplotlib has done a release (if you follow the linked github issues you'll see it was discovered recently) so you'd need to install their development version, or downgrade back to matplotlib 3.1. In terms of workarounds you can explicitly set the axis limits or call a matplotlib function that will properly trigger an autoscale update, something like

```
pyplot.scatter(x, x * 0).remove()
```

**Closed by mwaskom** 2020-04-23 22:33 UTC
