### ISSUE TITLE
Catplot FutureWarning

### ISSUE THREAD

**Issue by stfnrpplngr** [mwaskom/seaborn#1660] opened 2019-01-30 11:46 UTC
I get a similar warning as #1538 plotting some data with `catplot`. 

```
sns.catplot(x='task', y='RT', hue='response',
                data=data, order=['simple', 'complex'],
                kind='point')
plt.show()
```
That is the warning.
```
C:\Continuum\anaconda3\lib\site-packages\scipy\stats\stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
```

Writing the order as tuple instead of list, there appears to be no problem:
```
sns.catplot(x='task', y='RT', hue='response',
                data=data, order=('simple', 'complex'),
                kind='point')
plt.show()
```

**Comment by mwaskom** [comment] 2019-01-30 14:58
I can't reproduce the behavior you're seeing (versions would be helpful) but I strongly suspect that the list/tuple formatting of `order` is a red herring. There's no interaction between the order parameter and code that touches `scipy.stats` and I expect that like #1538 this is a warning about code that is outside the purview of seaborn.

**Comment by stfnrpplngr** [comment] 2019-01-30 15:08
Spyder 3.3.2
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
IPython 7.2.0 -- An enhanced Interactive Python.
Seaborn 0.9.0
Matplotlib 3.0.2
SciPy 1.1.0

Thank you for the fast reply.Tomorrow, I will take a closer look on that.

**Comment by mwaskom** [comment] 2019-01-30 15:56
What numpy version? The issue has to do with a change in numpy.

**Comment by stfnrpplngr** [comment] 2019-01-31 09:35
Sorry, forgot the most important one:
NumPy 1.15.4

**Comment by mwaskom** [comment] 2019-01-31 15:15
Thanks. I'm closing because this is fixed in scipy. Compare:

`1.1`: https://github.com/scipy/scipy/blob/v1.1.0/scipy/stats/stats.py#L1713
`1.2`: https://github.com/scipy/scipy/blob/v1.2.0/scipy/stats/stats.py#L1741

**Closed by mwaskom** 2019-01-31 15:15 UTC
