### ISSUE TITLE
Replace 'normed' kwarg to hist by 'density'

### ISSUE THREAD

**Issue by donscheme** [mwaskom/seaborn#1412] opened 2018-04-20 19:12 UTC
https://github.com/mwaskom/seaborn/blob/102cf08f9e40ef7037daf4b3b60b94ee144dc5cb/seaborn/distributions.py#L216

'normed' kwarg is deprecated

**Comment by mwaskom** [comment] 2018-04-20 19:18
Duplicate of #1380

**Closed by mwaskom** 2018-04-20 19:18 UTC
