### ISSUE TITLE
Numerical dodge option in boxplot

### ISSUE THREAD

**Issue by robince** [mwaskom/seaborn#2789] opened 2022-05-04 08:34 UTC
It would be great to have a numerical dodge option for boxplot that matches the behaviour of pointplot. 
This would allow boxplots over violin plots:
https://discourse.matplotlib.org/t/boxplots-on-top-of-violinplots/22807

**Comment by mwaskom** [comment] 2022-05-04 10:22
Hi, this is a duplicate of #1455

**Closed by mwaskom** 2022-05-04 10:22 UTC
