### ISSUE TITLE
Warning with pandas 2.2.0 and seaborn 0.13.1 kdeplot

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#3623] opened 2024-01-25 12:20 UTC
With seaborn 0.13.1 and pandas 2.2.0:
```python
import seaborn as sns

tips = sns.load_dataset('tips')
sns.kdeplot(tips, x='tip', hue='day')
```
generates a warning:
```
...\seaborn\_base.py:949: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  data_subset = grouped_data.get_group(pd_key)
```
This can be mitigated by changing the code to `data_subset = grouped_data.get_group((pd_key, ))`, as suggested in the message.

**Comment by mwaskom** [comment] 2024-01-25 12:59
Duplicate of https://github.com/mwaskom/seaborn/issues/3618 and already addressed in master by https://github.com/mwaskom/seaborn/pull/3620.

> This can be mitigated by changing the code to data_subset = grouped_data.get_group((pd_key, )), as suggested in the message

You would think, except pandas does not support that on 1.x and requires the `pd_key` to be a singleton string. It's a truly ridiculous situation.

**Closed by mwaskom** 2024-01-25 12:59 UTC

**Comment by mwaskom** [comment] 2024-01-25 21:16
I pushed out a 0.13.2 release this morning which should avoid these warnings (I don't see any in the [test logs](https://github.com/mwaskom/seaborn/actions/runs/7654939897/job/20859922254)).
