### ISSUE TITLE
heatmap annotates only first row

### ISSUE THREAD

**Issue by DimiM99** [mwaskom/seaborn#3573] opened 2023-11-25 20:11 UTC
plotting a heatmap and passing annot=True as argument, doesn't work as expected

<img width="865" alt="Screenshot 2023-11-25 at 9 03 37 PM" src="https://github.com/mwaskom/seaborn/assets/94388771/4ba9af9b-81b4-4f7f-9bea-18bdb71a8ebd">

using:
macOS arm64
conda 23.10.0
python 3.11.5
seaborn 0.12.2
matplotlib 3.8.0
matplotlib-base 3.8.0
matplotlib-inline 0.1.6

**Comment by mwaskom** [comment] 2023-11-25 20:58
Duplicate of https://github.com/mwaskom/seaborn/issues/3478

**Closed by mwaskom** 2023-11-25 20:58 UTC
