### ISSUE TITLE
Seaborn boxplot within a facet grid produces erroneous graph.

### ISSUE THREAD

**Issue by xapple** [mwaskom/seaborn#3398] opened 2023-06-20 20:36 UTC
I just encountered a rather serious bug in seaborn 0.12.2 facet plotting, in which a graph is produced -- without any warning or error -- showing the data in the wrong category. Potentially leading the scientist to draw the wrong conclusion!

    #!/usr/bin/env python3
    
    # Modules #
    import seaborn, pandas, numpy
    
    # Create a list for each category #
    patients   = ['Patient1',   'Patient2',   'Patient3']
    cohorts    = ['Cohort1',    'Cohort2',    'Cohort3']
    treatments = ['Treatment1', 'Treatment2', 'Treatment3']
    
    # We will use these lists to create a DataFrame with unique combinations #
    data = {
        'Patient':   [],
        'Cohort':    [],
        'Treatment': [],
        'Value':     []
    }
    
    # Create all unique combinations and add random values for each #
    for patient in patients:
        for cohort in cohorts:
            for treatment in treatments:
                for i in range(10):
                    data['Patient'].append(patient)
                    data['Cohort'].append(cohort)
                    data['Treatment'].append(treatment)
                    data['Value'].append(numpy.random.rand())
    
    # Make dataframe #
    df = pandas.DataFrame(data)
    
    # Find the indexes of the rows to drop #
    index_to_drop = df[(df['Patient'] == 'Patient2') &
                       (df['Cohort'] ==   'Cohort2') &
                       (df['Treatment'] == 'Treatment2')].index
    
    # Drop these rows from the DataFrame #
    df = df.drop(index_to_drop)
    
    ###############################################################################
    facet_params = dict(data      = df,
                        col       = 'Patient',
                        row       = 'Cohort',
                        col_order = patients,
                        row_order = cohorts)
    
    seaborn_params = dict(x = 'Treatment',
                          y = 'Value',)
    
    # Call seaborn #
    grid = seaborn.FacetGrid(**facet_params)
    
    # Bar plot #
    grid.map_dataframe(seaborn.boxplot, **seaborn_params, showfliers=False)
    
    # Bar plot #
    grid.map_dataframe(seaborn.stripplot, **seaborn_params, jitter=True)
    
    # Save #
    grid.savefig('facet_bug.png')

![facet_wrong](https://github.com/mwaskom/seaborn/assets/649288/0bd3a820-b0d9-4e3b-89c8-69f0982726fb)

In this short example, we have four different levels:
* Patients (categorical)
* Cohorts (categorical)
* Treatments (categorical)
* Value (scalar)

We introduce missing data: there are no values for Patient2 of Cohort2 getting Treatment2.

We make a FacetGrid with the patients and cohorts levels, and plot the treatments on the x axis with the value on the y axis (of each subplot).

We superimpose both a boxplot and a stripplot.

In the case of the stripplot, the data is correctly plotted. In the case of the boxplot, the data pertaining to Treatment3 ends up under the label of Treatment2!

The ideal behavior would actually be to produce a graph where the subaxes for Patient2 of Cohort2 only has two categories on the x axis in order to display only two boxplots (and shouldn't contain an empty space).

Is there any way of producing a facet grid where the number of categories of each X-axis is variable based on the data available?

Here is a mockup of plot desired that I edited manually using GIMP:

![facet_desired](https://github.com/mwaskom/seaborn/assets/649288/8a52545f-b8fc-467d-8e87-57d42b04fee6)

**Comment by mwaskom** [comment] 2023-06-20 20:59
Duplicate of #3389 (and others); as noted there the docs for FacetGrid warn about the potential for incorrect results.

**Comment by xapple** [comment] 2023-06-21 11:40
The docs might warn about it, but considering that the `stripplot` call followed correct behavior, it's quite easy for the user to assume that `boxplot` will also work when used in the exact same way. I believe `seaborn` should emit a warning in this case. Silently mixing up categories is quite serious for a plotting library.

Looking more into this problem, there are two easy fixes.

The first is to specify `order = treatments` in the `seaborn_params` dictionary, which produces this plot:

![facet_with_treat_order](https://github.com/mwaskom/seaborn/assets/649288/1b189b49-8be1-4276-836f-474ba0136255)   

The second is to specify `sharex = False` in the `facet_params` dictionary, which produces this plot:

![facet_without_sharex](https://github.com/mwaskom/seaborn/assets/649288/56b7269d-9c6b-4b82-b21f-adcdda0f6298)

**Comment by mwaskom** [comment] 2023-06-22 00:52
As noted in the duplicate issue, this is something that has already been improved for v0.13 so there's nothing else to discuss here. I continue to discourage direct use of `FacetGrid` unless you really know what you're doing, which is what the docs fairly clearly say.

**Closed by mwaskom** 2023-06-22 00:52 UTC
