### ISSUE TITLE
sns.displot(..., facet_kws=dict(sharex=False, sharey=False)) not working in 0.12.2

### ISSUE THREAD

**Issue by sorenwacker** [mwaskom/seaborn#3257] opened 2023-02-13 18:40 UTC
penguins = sns.load_dataset("penguins")
sns.displot(data=penguins, x="flipper_length_mm", col='species', facet_kws=dict(sharex=False, sharey=False))

![image](https://user-images.githubusercontent.com/3391614/218545874-ff5a5360-3310-4cc7-b410-878fa7e266a6.png)

The x-axis should not be shared.

**Comment by mwaskom** [comment] 2023-02-13 23:42
Duplicate of https://github.com/mwaskom/seaborn/issues/2472

**Closed by mwaskom** 2023-02-13 23:42 UTC
