### ISSUE TITLE
catplot() does not allow excluding incomplete data with sharex=False

### ISSUE THREAD

**Issue by felixdivo** [mwaskom/seaborn#1848] opened 2019-10-03 11:42 UTC
Say you have some some incomplete data on weirdly growing plants, and want to plot it as below. You might want to explicitly exclude the *tree* data for *outdoor*, as you just didn't test it and do not want to confuse anyone. How can this be done? I would have expected `sharex=False` to accomplish this, but apparently it does not. I this intended and can this be done in another way? (In my real example I also have set `hue='other_attribute'` but it probably does not play a role in this discussion.)

```python
import seaborn as sns
from matplotlib import pyplot as plt
from pandas import DataFrame

data = DataFrame(
    data=[
        ['grass', 'indoor', 30],
        ['bushes', 'indoor', 80],
        ['tree', 'indoor', 100],
        ['grass', 'outdoor', 50],
        ['bushes', 'outdoor', 120]
        # this does not exist: ['tree', 'outdoor', 300],
    ],
    columns=[
        'type', 'where', 'height'
    ])

graph = sns.catplot(x="type", y="height", col="where", data=data,
                    kind="bar", orient="v")
plt.show()
```

![image](https://user-images.githubusercontent.com/4403130/66123784-1c800680-e5e3-11e9-9d89-c1403134c673.png)

**Comment by felixdivo** [comment] 2019-10-03 11:48
`catplot()` passes all unknown `kwargs` down "through to the underlying plotting function" (see [here](https://seaborn.pydata.org/generated/seaborn.catplot.html)), but passing it to `facet_kws` and then to `subplot_kws` didn't work as well.

I also tried to cut it away by fiddling with `graph.axes[0, 1].xaxis` but it did not work.

**Comment by mwaskom** [comment] 2019-10-03 15:55
This is basically on purpose, but also a duplicate of https://github.com/mwaskom/seaborn/issues/1702

**Comment by felixdivo** [comment] 2019-10-03 19:18
Oh yes, this now woks with the example:

```python
grid = sns.FacetGrid(data, col="where", sharex=False)
grid.map_dataframe(sns.barplot, x="type", y="height")
```

![image](https://user-images.githubusercontent.com/4403130/66157052-40633c80-e623-11e9-8b07-87812bad978e.png)

Thanks! (Though it somehow lost the styling along the way)

**Comment by felixdivo** [comment] 2019-10-03 19:52
It now also works on my actual data set, though I have to include `dropna=False` to be able to see the bars that only exist in some grid tiles.

**Closed** 2019-10-03 21:42 UTC
