### ISSUE TITLE
IndexError in clustermap with keyword argument {x,y}ticklabels=False

### ISSUE THREAD

**Issue by harryscholes** [mwaskom/seaborn#1323] opened 2017-11-03 16:20 UTC
## `xticklabels` and `yticklabels` kwargs in `clustermap` are broken in seaborn v0.8.

This behaviour can be reproduced by:

```
$ conda create -n seaborn0.8 python=3 seaborn=0.8
$ source activate seaborn0.8
$ python
>>> import numpy as np
>>> import seaborn as sns
>>> sns.clustermap(np.random.rand(5,5), xticklabels=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/harry/anaconda3/envs/seaborn0.8/lib/python3.6/site-packages/seaborn/matrix.py", line 1301, in clustermap
    **kwargs)
  File "/Users/harry/anaconda3/envs/seaborn0.8/lib/python3.6/site-packages/seaborn/matrix.py", line 1142, in plot
    self.plot_matrix(colorbar_kws, xind, yind, **kws)
  File "/Users/harry/anaconda3/envs/seaborn0.8/lib/python3.6/site-packages/seaborn/matrix.py", line 1118, in plot_matrix
    xtl_rot = self.ax_heatmap.get_xticklabels()[0].get_rotation()
IndexError: list index out of range
```

With seaborn v0.7 this behaviour works as expected:

```
$ conda create -n seaborn0.7 python=3 seaborn=0.7
$ source activate seaborn0.7
$ python
>>> import numpy as np
>>> import seaborn as sns
>>> sns.clustermap(np.random.rand(5,5), xticklabels=False)
/Users/harry/anaconda3/envs/seaborn0.7/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:106: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
<seaborn.matrix.ClusterGrid object at 0x101a22898>
```

**Comment by mwaskom** [comment] 2017-11-03 17:57
Duplicate of #1231

**Closed by mwaskom** 2017-11-03 17:57 UTC
