### ISSUE TITLE
Sorting with New Interface

### ISSUE THREAD

**Issue by mattharrison** [mwaskom/seaborn#2936] opened 2022-08-04 16:17 UTC
I'm trying to recreate a line plot using the new interface. Because the line plots can go in any direction, I needed to use `sort=False` on old interface.

Is there an equivalent for the new interface?

![image](https://user-images.githubusercontent.com/119405/182898446-6881a693-6dbd-4f4a-b2f5-1d6859fb90b3.png)

**Comment by mattharrison** [comment] 2022-08-04 16:25
My end goal is to be able to do this with the new interface:

![image](https://user-images.githubusercontent.com/119405/182902083-67814c23-b7c4-4d6a-802e-d91766e7c2b0.png)

**Comment by mwaskom** [comment] 2022-08-04 22:29
Hi Matt, thanks for testing out the new tools. Oh

**Comment by mattharrison** [comment] 2022-08-04 22:37
Thanks. Which part of `Path` helps with order?

**Comment by mwaskom** [comment] 2022-08-04 22:44
There’s no parameter you need to set. Line is sorted (and drops missing observations), Path draws in the original order (and preserves them, as gaps in the path).

**Comment by mwaskom** [comment] 2022-08-04 23:44
BTW, when doing pandas method chaining -> seaborn, I recommend this style:

```python
(
    df
    .operation()
    .pipe(
        sns.lineplot,
        x=..., y=..., ...
    )
)
```

Rather than packing a pandas chain inside the function call to the seaborn function.

The catch is that prior to 0.12, most `sns` functions require you to do `.pipe((func, "data"), ...)` rather than `.pipe(func, ...)`. With keyword-only arguments in 0.12 the signatures have now been rearranged to support this. I probably wouldn't teach it immediately because students on older versions will get confused. But you _can_ use this style with `so.Plot` immediately, and I would suggest teaching it that way.

Also, when using `sns`, an advantage of using the figure-level functions is that the `FacetGrid` they return is also chainable (and has a couple of new methods in v0.12 to support this further, `.apply` and `.pipe`).

Personally I have been getting tons of mileage out of writing every seaborn plot such that a dataframe is piped into it rather than passed directly, it makes it really easy to drop in upstream tweaks (query, rename, replace, etc.), and it also saves your notebook from having a bunch of variable names with intermediate dataframes.

**Comment by mwaskom** [comment] 2022-08-06 01:01
Closing as resolved but ping if that didn't work for you.

**Closed by mwaskom** 2022-08-06 01:01 UTC

**Comment by mattharrison** [comment] 2022-08-15 14:24
Not sure what `Path` is doing but it doesn't seem right.

![image](https://user-images.githubusercontent.com/119405/184653796-63534b59-7480-4092-b58d-e5f09dcca785.png)

**Comment by mwaskom** [comment] 2022-08-15 15:00
Hi Matt, happy to help but please produce reproducible examples with your questions.

**Comment by mattharrison** [comment] 2022-08-15 15:49
Sorry, you probably want the data...

```
df = pd.read_csv('https://github.com/mattharrison/datasets/raw/master/data/owid-spending-vs-lifeexp.csv', index_col=0)
```

Let me know if this helps.

**Comment by mwaskom** [comment] 2022-08-20 19:37
Thanks for sharing the data.

When I do

```python
df = (
    pd.read_csv('https://github.com/mattharrison/datasets/raw/master/data/owid-spending-vs-lifeexp.csv', index_col=0)
    .groupby('LOCATION')
    .filter(lambda g: (g.Life_Expectancy.max() > 80) | (g.name == 'USA'))
)
```

And then

```python
so.Plot(df, x='Spending_USD', y='Life_Expectancy', color='LOCATION').add(so.Path())
```

or 

```python
sns.relplot(df, x='Spending_USD', y='Life_Expectancy', hue='LOCATION', sort=False, kind="line", aspect=1.3)
```

I get the following two images:

![image](https://user-images.githubusercontent.com/315810/185763519-cef83228-616f-4fbd-8fc9-dc4a5898ea2a.png)

![image](https://user-images.githubusercontent.com/315810/185763489-f89f3bbc-74c3-424d-806c-6501c5622eac.png)

Which, to my eye, look like they're plotting the data the same way?
