### ISSUE TITLE
Cannot change the fontsize of annotation in jointplot

### ISSUE THREAD

**Issue by neurongeek** [mwaskom/seaborn#996] opened 2016-08-19 12:08 UTC
I am making a joint plot using command -

sns.jointplot(xdata,ydata,kind='reg', order=1,color='k',ylim=[-0.62,0.22],xlim=[-16,15],annot_kws={"loc": 4})

With the annot_kws, I can move around where the annotation appears, but cannot change the font size. Also, can you select what stats you want to appear?

Thanks!

**Comment by mwaskom** [comment] 2016-08-19 13:26
Closing as duplicate of http://stackoverflow.com/questions/39039000/how-to-change-font-size-of-the-annotation-in-seaborn-jointplot

**Closed by mwaskom** 2016-08-19 13:26 UTC
