### ISSUE TITLE
Missaligned Y-Axis Labels in Heatmap

### ISSUE THREAD

**Issue by FirefoxMetzger** [mwaskom/seaborn#2592] opened 2021-05-25 08:18 UTC
I'm fairly certain that I found a bug; though it could be user error on my part. If this is a known issue, please feel free to close :)

Minimal Code:

```python
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# technically not necessary, but looks nicer :)
sns.set_context("talk")

df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                   "B": ["1", "1", "1", "2", "2",
                         "1", "1", "2", "2"],
                   "C": ["small", "large", "large", "small",
                         "small", "large", "small", "small",
                         "large"],
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

table = pd.pivot_table(df, values='D', index=['A', 'B'],
                    columns=['C'], aggfunc=np.sum)

fig, ax = plt.subplots()
sns.heatmap(table, fmt=".2f", cmap=sns.diverging_palette(230, 20, as_cmap=True), ax=ax)

plt.show()
```

Produces:

![bug](https://user-images.githubusercontent.com/4402489/119463376-90aa7900-bcf6-11eb-921d-bfa734301d4c.png)

Which has misaligned labels along the y-axis. If the labels get longer, seaborn seems to automatically rotate them, in which case the problem disappears.

Version Info:
```
Python 3.8.8
seaborn==0.11.1
matplotlib==3.3.4
```

**Comment by mwaskom** [comment] 2021-05-25 10:53
Duplicate of #2484

**Closed by mwaskom** 2021-05-25 10:53 UTC
