### ISSUE TITLE
Please  provide  contextmanager for  sns.set_ Theme 

### ISSUE THREAD

**Issue by CatNofishing** [mwaskom/seaborn#2507] opened 2021-03-15 00:45 UTC
If you can provide contextmanger for sns.set_theme ,it will be very convenient for contrel axes theme.
![image](https://user-images.githubusercontent.com/33288114/111090474-cbf83100-856a-11eb-80cd-cce2341c3603.png)

**Comment by mwaskom** [comment] 2021-03-15 00:50
This is a duplicate of #2505, which you opened this morning.

Please don't open multiple issues with the same request. If you would like to continue the discussion, please do so on the other issue thread.

**Closed by mwaskom** 2021-03-15 00:50 UTC
