### ISSUE TITLE
pairplot hue argument is broken

### ISSUE THREAD

**Issue by maxwellmckinnon** [mwaskom/seaborn#1826] opened 2019-09-05 12:34 UTC
Pairplot breaks when adding hue argument

sns.pairplot(features_df, hue='size_box')  # error
sns.pairplot(features_df)  # no error

Why does adding hue throw an error? This seems a regression either in seaborn or a dependency as this was known good code that used to work. Re-running my notebook I see it breaks here.

Thanks! :)

```
scipy/linalg/basic.py in inv(a, overwrite_a, check_finite)
    972         inv_a, info = getri(lu, piv, lwork=lwork, overwrite_lu=1)
    973     if info > 0:
--> 974         raise LinAlgError("singular matrix")
    975     if info < 0:
    976         raise ValueError('illegal value in %d-th argument of internal '

LinAlgError: singular matrix
```

**Comment by mwaskom** [comment] 2019-09-05 13:57
This is a duplicate of a highly trafficked issue that you will find if you search

**Closed by mwaskom** 2019-09-05 13:57 UTC
