### ISSUE TITLE
Bugs in non quadratic pairplots

### ISSUE THREAD

**Issue by markus783** [mwaskom/seaborn#2369] opened 2020-12-03 15:33 UTC
From version 0.9.0 to version 0.11.0 the "diagonal" on non quadratic pairplots is empty.

Sample Code:

```python
import seaborn as sns
import pandas as pd 
from matplotlib import pyplot as plt

test_df = pd.DataFrame({"a": [1,2,3,4], "b": [3,4,5,6], "c": [5,3,6,1]})
sns.pairplot(test_df, x_vars=["a"], y_vars=["b", "c"])
plt.show()
```

The top graph is empty although a scatter plot should be shown in place as the two columns have matching indices.

**Comment by Horst-Konopka** [comment] 2020-12-03 15:42
Yes, this is also a problem we had at our company. We solved it by just not using non quadratic pairplots.

**Comment by mwaskom** [comment] 2020-12-03 15:53
Duplicate of #2260 (there's an easy workaround given there).

**Closed by mwaskom** 2020-12-03 15:53 UTC
