### ISSUE TITLE
Passing 'c=cols' to pairplot/PairGrid causes ValueError - it would be nice to be more flexible

### ISSUE THREAD

**Issue by jbrinchmann** [mwaskom/seaborn#1301] opened 2017-10-09 15:40 UTC
There is a conflict in seaborn when one tries to colour points in a pairplot using a continuous colour scale - while a work-around exists, this is such a common case it would be nice if it was directly handled by the code. A simple example is:

```x = np.random.normal(0, 4, size=100)
y = np.random.normal(-2, 4, size=100)
z = np.abs(x)*y
T = x*y
df = pd.DataFrame({'x': x, 'y': y, 'z': z, 'T': T})
sns.pairplot(df, plot_kws=dict(c= T))
```

which fails with `ValueError: Supply a 'c' kwarg or a 'color' kwarg but not both; they differ but their functionalities overlap`.

This seems to be caused by a call in axisgrid.py:
```     func(data_k[x_var], data_k[y_var],   label=label_k, color=color, **kwargs) ```
which always passes in the color keyword. 

It would be desirable to inspect the kwargs option, and if c= is not provided, to pass color in as keyword.

Now as a work-around it is of course possible to wrap plt.scatter explicitly with say 
```
def colplot(x, y, color, **kwargs):
    plt.scatter(x, y, c=color, **kwargs)
```
but this is not obvious from the documentation and as I would expect this to be a fairly common use case it would be nice with a more flexible handling of continous colour variables, in line with how poweful seaborn in general is out of the box.

**Comment by mwaskom** [comment] 2017-10-09 16:08
Part of the problem with supporting this is that there's no real good way to get a colorbar.

**Comment by mwaskom** [comment] 2017-10-09 16:11
I'm somewhat averse to doing anything here as I have tried to avoid hardcoding behavior for specific functions into the grid objects. In general the approach you propose, defining a small wrapper function, is my preferred suggestion. It may not be immediately obvious from the docs, but it actually is discussed in the [axisgrid tutorial](http://seaborn.pydata.org/tutorial/axis_grids.html#mapping-custom-functions-onto-the-grid) (though in the FacetGrid section):

```
Sometimes, though, you’ll want to map a function that doesn’t work the way you expect with the color and label keyword arguments. In this case, you’ll want to explictly catch them and handle them in the logic of your custom function. For example, this approach will allow use to map plt.hexbin, which otherwise does not play well with the FacetGrid API:
```

**Comment by jbrinchmann** [comment] 2017-10-09 18:49
That is a fair enough point. I did indeed find the wrapper function discussed in the axisgrid tutorial but it is not the first thing you look for. 

What would have been useful from my experience would be to have a warning or a pointer in the documentation of {plot, diag, grid}_kws to say that some keywords cannot be passed in through this mechanism but needs a wrapper. That is usually where people first look when something does not work - and getting a heads-up is good enough to then google. 

Anyway, I'll live fine with my wrapper for now.

**Comment by mwaskom** [comment] 2017-10-09 20:34
Actually this specific issue is caused by a change in matplotlib; I was able to get exactly what you wanted to work [previously](https://github.com/mwaskom/seaborn/issues/313#issuecomment-57829698), but they now raise when both `c` and `color` are passed.

**Comment by machism0** [comment] 2018-02-13 16:05
I'm running into this problem right now. Just trying to put a color mapping on my off diagonal scatter plots.

**Comment by domgarvir** [comment] 2018-04-13 09:06
So .... what is the solution then?
I've tried to call the function colplot defined by jbrinchmann, but then the interpreter complaints:
"TypeError: scatter() got multiple values for keyword argument 'c'"
What is the correct way to plot a color using a continuous variable inside pairplot/grid?

**Comment by mwaskom** [comment] 2020-08-31 00:58
With #2234 the original code now works and you can also accomplish a continuous color mapping with:

```python
x, y = np.random.normal(-2, 4, size=(2, 100))
z = np.abs(x) * y
T = x * y
df = pd.DataFrame({'x': x, 'y': y, 'z': z, 'T': T})
g = sns.pairplot(df, plot_kws=dict(hue=df["T"]))
g.add_legend(title="T")
```

or
```python
g = sns.PairGrid(df, hue="T")
g.map_offdiag(sns.scatterplot)
g.map_diag(sns.histplot, hue=None)
g.add_legend()
```

Like other uses of scatterplot with a numeric hue mapping, this shows a "representative legend" not a colorbar, but that's tracked elsewhere (#2231 ) so I'm going to close this issue as resolved.

**Closed by mwaskom** 2020-08-31 00:58 UTC
Labels: annoyance, mod:axisgrid
