### ISSUE TITLE
pairplot updating no longer works in `seaborn 0.11.0`

### ISSUE THREAD

**Issue by loftusa** [mwaskom/seaborn#2349] opened 2020-11-12 22:40 UTC
I had some plotting code running on seaborn 0.10:
```
def plot_oos(X_hat, oos_vertices, labels, oos_labels, title):
    # Plot the in-sample latent positions
    plot = pairplot(X_hat, labels=labels, title=title)

    # generate out-of-sample dataframe
    oos_vertices = np.atleast_2d(oos_vertices)
    data = {'Type': oos_labels, 
          'Dimension 1': oos_vertices[:, 0], 
          'Dimension 2': oos_vertices[:, 1]}
    oos_df = pd.DataFrame(data=data)
    
    # update plot with out-of-sample latent positions,
    # plotting out-of-sample latent positions as stars
    plot.data = oos_df
    plot.hue_vals = oos_df["Type"]
    plot.map_offdiag(plt.scatter, s=500, marker="*", edgecolor="black")
```

Here, `pairplot` is a wrapper on seaborn's `pairplot`, which is why it has different arguments. The wrapper returns a seaborn `PairGrid`.

The last three lines are the most important. They essentially updated the data and hue-values inside a pairplot with new data, then mapped it onto the pairplot. This function was quite useful for me -- I use variations of it all the time to add stuff to PairGrid plots.

Using `seaborn 11.0` broke this code -- the `plot.map_offdiag` line no longer does anything -- and I'm trying to understand why. Is this a bug, or a feature? I see that [whatsnew](https://seaborn.pydata.org/whatsnew.html) talks about changing delegation of `hue` handling, but I don't fully understand what this changes.

See below for example. The top picture correctly has the added data (plotted large, with the star marker), and the bottom plot does not have the added data. Plots were generated with the same code on seaborn 0.10.0, and then 0.11.0.

<img width="388" alt="Screen Shot 2020-11-12 at 6 56 16 PM" src="https://user-images.githubusercontent.com/12386450/99010865-b103aa80-24ff-11eb-956f-771b1765ee04.png">

<img width="412" alt="Screen Shot 2020-11-12 at 6 57 31 PM" src="https://user-images.githubusercontent.com/12386450/99010919-cc6eb580-24ff-11eb-9794-bf7a763e5106.png">

**Comment by loftusa** [comment] 2020-11-13 03:04
Update: fixed by switching plt.scatter to sns.scatterplot

**Comment by mwaskom** [comment] 2020-11-13 12:06
Duplicate of #2307?

**Closed** 2020-11-13 15:35 UTC
