### ISSUE TITLE
Boxplot ignores 'hue' if no 'x' given

### ISSUE THREAD

**Issue by bluss** [mwaskom/seaborn#2597] opened 2021-06-15 13:54 UTC
In the following, the `hue` has no effect (seaborn 0.11.1 as well as current master)

```python
tips = sns.load_dataset("tips")
sns.boxplot(data=tips, y='tip', hue='smoker')
```

It takes effect if something like `x='sex'` is added.

Thanks for creating a great package.

**Comment by mwaskom** [comment] 2021-06-17 20:07
Duplicate of https://github.com/mwaskom/seaborn/issues/2340, probably a few others, but that has a workaround.

**Closed by mwaskom** 2021-06-17 20:07 UTC
