### ISSUE TITLE
displot histogram gets stuck when handling data with non-unique indices

### ISSUE THREAD

**Issue by ArtoVi** [mwaskom/seaborn#2667] opened 2021-09-22 18:53 UTC
Hello,

I discovered that my Seaborn-dependent package gets, as far as I can tell, eternally stuck when creating a displot histogram if using Seaborn==0.11.2 (matplotlib==3.4.2). Everything functions as intended on Seaborn v0.11.0 and 0.11.1.

While solving the issue, I narrowed the problem down to **row 400 of distributions.py plot_univariate_histogram()**:
```python
all_data = self.comp_data.dropna()
```
I was not able to view contents of self.comp_data on PyCharm's debugger, so that's the likely culprit.

Furthermore, I tested that the problem occurs with a melted & merged Data Frame that **has repeated indices**. Resetting of the index solves the problem and the distributions are plotted within seconds. While altering my code solved this for me, I bring this to your attention as I feel like this (at least the Python getting stuck part) is not intended.

### Data and code
Note: '_Old ind_' are the indices before resetting, and '_Reset ind_' after reset.

Reset ind | Old ind | Channel | DistBin | Sample Group | Type | Value
-- | -- | -- | --------- | -- | ---- | --------
0 | 0 | DAPI10x | 0 | Ctrl | Area | 31.2650
0 | 0 | DAPI10x | 0 | Ctrl | Area | 24.9275
0 | 0 | DAPI10x | 0  | Ctrl | Area | 81.1201
0 | 0 | DAPI10x | 0 | Ctrl | Area | 49.4325
0 | 0 | DAPI10x | 0 | Ctrl | Area | 22.3925
... | ...  | ... | ... | ... | ... | ...
1596983 | 40167 | DAPI10x | 61 | MutB | Volume | 287.5537
1596984 | 40168 | DAPI10x | 61 | MutB | Volume | 287.5537
1596985 | 40169 | DAPI10x | 61 | MutB | Volume | 349.9147
1596986 | 40170 | DAPI10x | 61 | MutB | Volume | 453.8498
1596987 | 40171 | DAPI10x |  61 | MutB | Volume | 204.4056

```python
row_order = data.loc[:, 'Type'].unique()
plot_palette = {'Ctrl': (0.39215686274509803, 0.5333333333333333, 0.9176470588235294),
                'MutB': (0.9803921568627451, 0.7607843137254902, 0.0196078431372549)}

sns.displot(data=data, x='Value', hue='Sample Group', col=None, row='Type', alpha=0.4, kind='hist',
            stat='probability', palette=plot_palette, kde=True, height=2.5, aspect=2.25,
            row_order=row_order, discrete=False, multiple='stack',
            facet_kws={'legend_out': True, 'sharex': False, 'sharey': False,
                       'gridspec_kws': {'top': 0.92, 'left': 0.15, 'right': 0.8, 'hspace': 0.6}}
            )
```

**Comment by mwaskom** [comment] 2021-09-23 00:27
Thanks for spelunking to find the issue and reporting it clearly! The issue manifests in a few different ways but this is a duplicate of #2652

**Closed by mwaskom** 2021-09-23 00:27 UTC
