### ISSUE TITLE
Having issue importing seaborn

### ISSUE THREAD

**Issue by ishaan-khurana** [mwaskom/seaborn#3303] opened 2023-03-24 18:35 UTC
Hi I am trying to import seaborn via python console in Pycharm and I keep getting the following error

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6f477838ac7f>", line 1, in <module>
    import seaborn
  File "/private/var/folders/nl/bfb0ndrn0j10d745f7vr24380000gt/T/AppTranslocation/4E71CD11-E583-4421-AD73-B333DE7988D5/d/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/ishaankhurana/Library/Python/3.10/lib/python/site-packages/seaborn/__init__.py", line 12, in <module>
    from .widgets import *  # noqa: F401,F403
  File "/private/var/folders/nl/bfb0ndrn0j10d745f7vr24380000gt/T/AppTranslocation/4E71CD11-E583-4421-AD73-B333DE7988D5/d/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/ishaankhurana/Library/Python/3.10/lib/python/site-packages/seaborn/widgets.py", line 6, in <module>
    from ipywidgets import interact, FloatSlider, IntSlider
  File "/private/var/folders/nl/bfb0ndrn0j10d745f7vr24380000gt/T/AppTranslocation/4E71CD11-E583-4421-AD73-B333DE7988D5/d/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipywidgets/__init__.py", line 59, in <module>
    _handle_ipython()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipywidgets/__init__.py", line 57, in _handle_ipython
    register_comm_target()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipywidgets/__init__.py", line 47, in register_comm_target
    comm_manager = get_comm_manager()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ipywidgets/__init__.py", line 33, in get_comm_manager
    if ip is not None and ip.kernel is not None:
AttributeError: 'PyDevTerminalInteractiveShell' object has no attribute 'kernel'

Any knowledge on how to fix this? Thanks! -IK

**Comment by mwaskom** [comment] 2023-03-26 18:29
It looks like your exception is being raised when trying to import objects from ipywidgets. I have heard of a bug in PyCharm that arises when importing ipywidgets (https://github.com/mwaskom/seaborn/issues/3242) although it prevents somewhat differently. Ultimately I doubt that there's much seaborn can do here, aside from the suggestion in the other issue to make the ipywidgets import more optional. I don't really understand the root cause of these problems, though, so I am uncertain how that would actually work.

**Comment by mwaskom** [comment] 2023-03-26 18:29
The components in seaborn that depend on ipywidgets are completely optional though, so if you're not otherwise using that library, uninstalling it from your environment should "fix" the problem.

**Comment by mwaskom** [comment] 2023-04-02 18:23
Closing as this is not a seaborn issue as far as i can tell.

**Closed by mwaskom** 2023-04-02 18:23 UTC
