### ISSUE TITLE
Swarm/StripPlot recalculate expensive point_color property inside a loop

### ISSUE THREAD

**Issue by alterscape** [mwaskom/seaborn#2596] opened 2021-06-04 19:10 UTC
A coworker and I are generating a `stripplot` of several thousands of points. In Seaborn 0.11.1, this is extremely slow. `_CategoricalScatterPlotter.point_colors` (line 1055 in categorical.py) is called in several inner loops. Each time `point_colors` is called, the property recomputes a lost of colors by appending to a pandas `Series`.  Editing pandas Series (using append, etc) is relatively slow. Recomputing every color each time you need to index into the list to get one color is slow.

Our proposed fixes:  
1. Compute `group_colors` as a numpy array rather than as a pd.Series. Construct a pd.Series, if required, after the loop on line 1075-1078, rather than before, since those computations don't rely on `group_data.index`
2. Store point_colors' output in a local variable before entering the loop (for example, in `draw_stripplot` on line 1117 of categorical.py) so that the expensive computation only happens once.

For our use-case, we get a 10-20x speedup (from >1 min to approx 4.5 sec) by implementing these changes.

Any feedback on this before we submit a PR?  It looks like stripplot is under a larger general refactoring at this time, but we'd like to get these fixes upstream (assuming we can get all the tests passing, etc, of course!) so everyone benefits and we don't have to maintain a subclass of CategoricalScatterPlotter in our own code.

**Comment by mwaskom** [comment] 2021-06-04 20:08
It would be helpful to have a code example (it should be sufficient to generate random data?).

Both of those functions have been completely rewritten since 0.11 so this issue has probably gone away. (Have you tested on the development version?)

With the ~50k row diamonds dataset:

```python
%time sns.stripplot(data=diamonds, x="cut", y="price", hue="clarity", palette="Blues")
```
```
CPU times: user 267 ms, sys: 14.4 ms, total: 281 ms
Wall time: 306 ms
```

But I get almost the exact same timing on 0.11.1, so I'm not quite sure what's happening on your end.

Also 

> Each time point_colors is called, the property recomputes a lost of colors by appending to a pandas Series. Editing pandas Series (using append, etc) is relatively slow. Recomputing every color each time you need to index into the list to get one color is slow.

I guess you mean https://github.com/mwaskom/seaborn/blob/v0.11.1/seaborn/categorical.py#L1080?

`point_colors` here is a Python list, which has O(1) appends. So perhaps I am a bit confused about the issue.

**Comment by mwaskom** [comment] 2021-06-10 15:30
Closing as nonreproducible / likely moot, but feel free to add more information.

**Closed by mwaskom** 2021-06-10 15:30 UTC
