### ISSUE TITLE
Order of categories not correct in FacetGrid with barplot

### ISSUE THREAD

**Issue by wienen** [mwaskom/seaborn#1158] opened 2017-04-16 12:29 UTC
When I perform the following:
```
# Import relevant libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# set up the dataframe
ids = range(12)
surv = [0,0,1,1] * 3
fare = list(range(3, 3*13, 3))
sex = ['m', 'f', 'f', 'm'] * 3
emb = ['A'] * 4 +['B']*4 + ['C'] * 4
titles = ['id', 'Survived', 'Fare', 'Sex', 'Embarked']

data = pd.DataFrame(columns=titles)

data['id'] = ids
data['Survived'] = surv
data['Fare'] = fare
data['Sex'] =sex
data['Embarked'] = emb

# inspect the data - esp. values for fare and sex
data
```
<img width="268" alt="data" src="https://cloud.githubusercontent.com/assets/1828588/25071180/f0c68ae8-22b0-11e7-9290-bb235b445b80.png">

```
# plot the data - here the bug manifests
grid = sns.FacetGrid(data, row='Embarked', col='Survived', size=2.2, aspect=1.6)
grid.map(sns.barplot, 'Sex', 'Fare', alpha=.5, ci=None)
grid.add_legend()
```
<img width="520" alt="facetgrid" src="https://cloud.githubusercontent.com/assets/1828588/25071175/c4466574-22b0-11e7-81b5-7aa732e05785.png">
As you can see, the order of the 'm' and 'f' bars in the graphs in the first columns have been switched, even though the labels on the axes suggest otherwise.

Versions:
pandas    :  0.19.2
seaborn   :  0.7.1
matplotlib:  2.0.0

**Comment by mwaskom** [comment] 2017-04-16 13:48
Duplicate of https://github.com/mwaskom/seaborn/issues/1151

**Closed by mwaskom** 2017-04-16 13:48 UTC

**Comment by wienen** [comment] 2017-04-16 14:50
Thx
