### ISSUE TITLE
jointplot - When no column names not found in dataset, error message is unclear

### ISSUE THREAD

**Issue by TartySG** [mwaskom/seaborn#1206] opened 2017-06-21 18:43 UTC
```
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns

mean, cov = [0, 1], [(1, .5), (.5, 1)]
data = np.random.multivariate_normal(mean, cov, 200)
df = pd.DataFrame(data, columns=["x", "y"])

sns.jointplot(x="Not_X_Name", y="Not_a_valid_name", data=df)
sns.jointplot(x="Not_X_Name", y="y", data=df)
sns.jointplot(x="", y="", data=df)
```

All of those calls return different error message, none of which are clear / help find the actual issue column names not found in the dataframe.

@chrish42

**Comment by mwaskom** [comment] 2017-06-21 18:46
Duplicate of #1204

**Closed by mwaskom** 2017-06-21 18:46 UTC
