### ISSUE TITLE
Seaborn Objects: Barplot bars order

### ISSUE THREAD

**Issue by JanPalasek** [mwaskom/seaborn#3022] opened 2022-09-13 07:09 UTC
Hello. I found an inconsistency between SO (Seaborn Objects) and functional API.

When having a values sorted descendingly, SO puts the first value (as ordered in pandas df) to the bottom. This problem occurs only for horizontal bar chart.

<details>
<summary>SO</summary>

![image](https://user-images.githubusercontent.com/26582151/189832872-6f10ce11-a709-443c-a9a5-11a7a544005f.png)

</details>

This works differently than in the functional API.

<details>
<summary>Functional API</summary>

![image](https://user-images.githubusercontent.com/26582151/189833204-ec7befad-a1ef-4112-a5bf-0d8cad479912.png)

</details>

Would it be possible to have the default set as in the functional API with an option to override it? This default would work better with value_counts, since people start looking at the plot from the top-left corner, so this is the place where we want them to show the "most important" category.

**Comment by liuzj039** [comment] 2022-09-13 09:11
Not the developer of seaborn, but I believe `scale` can solve this problem.
```
(
    so.Plot(data=freq, x='name', y='index')
    .add(so.Bar())
    .scale(y=so.Nominal(order = ['A', 'B']))
)
```
![image](https://user-images.githubusercontent.com/55271666/189861545-a99a789c-0147-4e30-863f-bb027163b58e.png)

**Comment by mwaskom** [comment] 2022-09-13 10:31
Duplicate of #2967, thanks.

**Closed by mwaskom** 2022-09-13 10:31 UTC
