### ISSUE TITLE
Feature request: intercept and slope of regressed line

### ISSUE THREAD

**Issue by LiquePy** [mwaskom/seaborn#1506] opened 2018-07-19 09:22 UTC
lmplot Method does not give a good sense of regressed line when axes boundaries are far from zero and not in scale. It might be a good idea to write a method or argument to somehow (either on the plot or as print) output the intercept and slope of the regressed line.

**Comment by mwaskom** [comment] 2018-07-19 11:51
Duplicate of #207

**Closed by mwaskom** 2018-07-19 11:51 UTC
