### ISSUE TITLE
tsplot crashes when there is only one datapoint

### ISSUE THREAD

**Issue by BlackHC** [mwaskom/seaborn#1078] opened 2016-12-12 11:29 UTC
when data has only one datapoint (for a given unit and condition), tsplot crashes with an out of bounds exception.

```
seaborn/timeseries.py in tsplot(data, time, unit, condition, value, err_style, ci, interpolate, color, estimator, n_boot, err_palette, err_kws, legend, ax, **kwargs)
    328     # Pad the sides of the plot only when not interpolating
    329     ax.set_xlim(x.min(), x.max())
--> 330     x_diff = x[1] - x[0]
    331     if not interpolate:
    332         ax.set_xlim(x.min() - x_diff, x.max() + x_diff)

IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by BlackHC** [comment] 2016-12-12 11:29
Please let me know if I need to provide additional information.
Thanks,
 Andreas

**Comment by phobson** [comment] 2016-12-13 19:32
@BlackHC in general, a self-contained example that builds a data structure from scratch and reproduces the problem is helpful.

**Comment by mmagnuski** [comment] 2016-12-13 20:41
hm, but I doesn't make much sense to use tsplot for data with one sample. Maybe a more helpful error message would be ok?

**Comment by BlackHC** [comment] 2016-12-14 17:28
https://cloud.sagemath.com/projects/26d7dccf-e180-450e-b348-05e3242d8779/files/2016-12-14-171122.ipynb

```python
import pandas as pd
import seaborn

# This crashes.
data = [
    {'unit': 1, 'condition': '2015-12-02', 'tick': 1, 'value': 2},  
    {'unit': 1, 'condition': '2015-12-02', 'tick': 2, 'value': 3},
    {'unit': 1, 'condition': '2015-12-01', 'tick': 1, 'value': 1}, 
]
data_frame = pd.DataFrame(data)
seaborn.tsplot(data_frame, time="tick", unit="unit", condition="condition", value="value", err_style="unit_traces")
```

Creating the example, I noticed that it only breaks if the single data point trace comes last because x is a loop variable, so the padding only takes the last trace into account... which means that the padding is probably off when you have traces that vary wildly in their span in general.

Thanks,
 Andreas

**Comment by mwaskom** [comment] 2017-07-07 20:56
Closing with tsplot deprecation.

**Closed by mwaskom** 2017-07-07 20:56 UTC
