### ISSUE TITLE
Seaborn Distplot "misses" some values on the x axis 

### ISSUE THREAD

**Issue by pradnyabulusu** [mwaskom/seaborn#1894] opened 2019-12-15 04:09 UTC
![Screenshot 2019-06-08 at 11 44 11 PM](https://user-images.githubusercontent.com/37510501/70857972-b38c0780-1f1e-11ea-80f3-a5ba4c7b1515.png)
![Screenshot 2019-06-08 at 11 49 18 PM](https://user-images.githubusercontent.com/37510501/70857973-bb4bac00-1f1e-11ea-8d51-1bd2b45f87e5.png)

**Comment by mwaskom** [comment] 2019-12-15 13:33
Please don’t post screenshots of code. You’ll get help much faster if you write an example I can copy and paste.

**Comment by mwaskom** [comment] 2019-12-18 15:07
Closing as duplicate of #327

**Closed by mwaskom** 2019-12-18 15:07 UTC
