### ISSUE TITLE
histplot hangs with increasing memory usage

### ISSUE THREAD

**Issue by pylipp** [mwaskom/seaborn#2424] opened 2021-01-07 16:57 UTC
```
import seaborn as sns
sns.histplot([20.002347, 20.002347, 51.004152, 19.00218, 20.002346])
```

is irresponsive for a long time with increasing memory usage. Adding `bins=10` creates the plot without major delay.

Version: 0.11.1

**Comment by mwaskom** [comment] 2021-01-07 18:26
Thanks, this is a duplicate of #2325

**Closed by mwaskom** 2021-01-07 18:26 UTC
