### ISSUE TITLE
pairplot can't convert object type column to numeric when the hue keyword is set

### ISSUE THREAD

**Issue by frbourassa** [mwaskom/seaborn#2420] opened 2021-01-06 16:32 UTC
In seaborn 0.11.1, a column with a non-numeric dtype (but that can be cast to a numeric type) can be plotted with pairplot if it is specified in the `vars` argument, when the `hue` keyword argument is not specified. The type conversion is done automatically. 

```
iris = sns.load_dataset("iris")
iris["sepal_length"] = iris["sepal_length"].astype(object)
sns.pairplot(iris, vars=["sepal_length", "sepal_width", "petal_length"])
```

However, if `hue` is specified, the conversion fails with a long, ugly traceback: 
```
sns.pairplot(iris, hue="species")
```

This worked without problem in seaborn < 0.11. There is no error if the object-type column is explicitly omitted with the `vars` argument:
```
sns.pairplot(iris, hue="species", vars=["sepal_width", "petal_length"])
```

The untidy error message suggests that this is not an intentional restriction. It is not a major bug since it is easily fixed by manually converting the columns to a numeric dtype beforehand, but it can be annoying, especially with older code. 

seaborn version: 0.11.1
matplotlib version: 3.3.2
matplotlib backends: MacOSX, Agg or jupyter notebook inline.

**Comment by mwaskom** [comment] 2021-01-06 16:38
Thanks for the clear report. I can reproduce on v0.11.1 but not on master. I haven't done a full bisect, but I think this was probably fixed by https://github.com/mwaskom/seaborn/pull/2417

**Comment by mwaskom** [comment] 2021-01-07 13:27
I'm going to close this issue as it appears resolved.

I wouldn't advise updating to master in production right now, because there's a lot of work happening on it, but if you get a chance to test out your actual usecase and find it sill not working, please ping.

**Closed by mwaskom** 2021-01-07 13:27 UTC
Labels: bug, mod:axisgrid

**Comment by frbourassa** [comment] 2021-01-07 14:08
Will do, thank you for quickly looking into the issue!
