### ISSUE TITLE
Clustermap annot=True only plots value in lower left corner

### ISSUE THREAD

**Issue by StefanJansen01** [mwaskom/seaborn#810] opened 2016-01-01 17:14 UTC
In responding to a [stackoverflow question](http://stackoverflow.com/questions/34556180/how-to-plot-correlation-matrix-in-python/34558152#34558152), I noticed that 

    sns.clustermap(data=corr, col_cluster=False, annot=True, fmt='d', cmap='Greens')

produced annotation only in the lower left corner. This looks like a bug?
![cluster](https://cloud.githubusercontent.com/assets/4275885/12071571/d3d22044-b080-11e5-88e5-862340170011.png)

**Comment by mwaskom** [comment] 2016-01-01 17:21
Duplicate of #619

**Closed by mwaskom** 2016-01-01 17:21 UTC
