### ISSUE TITLE
relplot must assign a list or a column name in the "size" parameter 

### ISSUE THREAD

**Issue by FrankBGao** [mwaskom/seaborn#2330] opened 2020-10-22 02:08 UTC
https://seaborn.pydata.org/examples/scatter_bubbles.html
```
import seaborn as sns
sns.set_theme(style="white")

mpg = sns.load_dataset("mpg")

sns.relplot(x="horsepower", y="mpg", hue="origin", size="weight",
            sizes=(40, 400), alpha=.5, palette="muted",
            height=6, data=mpg)
```

In the version 0.10.0, I could assign size=1, in the sns.relplot(), there is no error.
In the version 0.10.1, I will gain an error "TypeError: object of type 'int' has no len()".
I must assign size be  "size=[1] * len(mpg)".

**Comment by mwaskom** [comment] 2020-10-22 11:18
Duplicate of #2279

**Closed by mwaskom** 2020-10-22 11:18 UTC
