### ISSUE TITLE
Heatmap bounds cut-off in matplotlib 3.1

### ISSUE THREAD

**Issue by jakevdp** [mwaskom/seaborn#1861] opened 2019-11-02 00:15 UTC
I'm not certain if this is a regression in matplotlib or a bug in seaborn, but a user reported this difference with seaborn between matplotlib 3.0 and 3.1 ([original issue](https://github.com/googlecolab/colabtools/issues/828)):

Example code:
```python
import numpy as np
import pandas as pd
import seaborn as sns

np.random.seed(0)
data = pd.DataFrame(np.random.randint(0, 10, (10, 10)))
sns.heatmap(data, annot=True);
```
Output in matplotlib 3.0:
![seaborn-2](https://user-images.githubusercontent.com/781659/68062974-f5dcea80-fcca-11e9-87ce-afdf24151e79.png)

Output in matplotlib 3.1:
![seaborn-1](https://user-images.githubusercontent.com/781659/68062976-f8d7db00-fcca-11e9-9aa4-dca8800f38b8.png)

**Comment by jakevdp** [comment] 2019-11-02 00:33
Actually, this looks to have changed from matplotlib 3.1.0 to 3.1.1, so most likely a matplotlib issue.

**Comment by mwaskom** [comment] 2019-11-02 13:06
Duplicate of https://github.com/mwaskom/seaborn/issues/1773 (and like 60% of new seaborn tickets over the last three months...)

**Closed by mwaskom** 2019-11-02 13:06 UTC

**Comment by jakevdp** [comment] 2019-11-02 13:19
Sorry - I tried an issue search before filing and didn't come across that.
