### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by wdecoster** [mwaskom/seaborn#1386] opened 2018-03-12 14:36 UTC
Hello,

I use seaborn extensively for creating plots in my [NanoPlot](https://github.com/wdecoster/NanoPlot) tool. Users have been reporting the following error:

```
Traceback (most recent call last):
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 61, in main
    make_plots(datadf, settings, args)
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 260, in make_plots
    log=settings["logBool"])
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/nanoplotter/nanoplotter.py", line 250, in length_plots
    kde_kws={"label": name, "clip": (0, maxvalx)})
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 224, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 657, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 273, in _univariate_kdeplot
    cumulative=cumulative)
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 345, in _statsmodels_univariate_kde
    kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 146, in fit
    clip=clip, cut=cut)
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 506, in kdensityfft
    f = revrt(zstar)
  File "/users/218819/scratch/apps/Anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py", line 20, in revrt
    y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
TypeError: slice indices must be integers or None or have an __index__ method
```

https://github.com/wdecoster/NanoPlot/issues/52
https://github.com/wdecoster/nanopack/issues/5
https://github.com/wdecoster/NanoPlot/issues/23
https://github.com/wdecoster/NanoPlot/issues/45

See also https://github.com/mwaskom/seaborn/issues/1103 and https://github.com/mwaskom/seaborn/issues/1092 for the same problem

Would it make sense to make seaborn depend on statsmodels>=0.8.0 or a recent scipy version? I'd be happy to open a PR for this if you agree.

Cheers,
Wouter

**Comment by mwaskom** [comment] 2018-03-12 14:38
Duplicate of #1103

**Closed by mwaskom** 2018-03-12 14:38 UTC

**Comment by wdecoster** [comment] 2018-03-12 14:44
Yes, I know. I referenced that issue too. Fine, I'll explicitly adapt my dependencies to require statsmodels>=0.8.0 although I consider this an upstream issue.

**Comment by mwaskom** [comment] 2018-03-12 15:18
Well, it's upstream of seaborn too...

**Comment by wdecoster** [comment] 2018-03-12 15:28
Fair point. So upstream of seaborn is scipy, then numpy? I'm not sure when exactly statsmodels comes in this and where the issue should be raised. I'm essentially just escalating the dependency chain...

**Comment by mwaskom** [comment] 2018-03-23 21:34
There's no issue to raise; it has been solved, hence the problem going away when you use the newest version statsmodels. It is an incompatibility between older versions of statsmodels and newer versions of numpy, which started to raise when using a float as an array index.

seaborn does not have a strict dependency on statsmodels so it would not declare a dependency on a specific version, and anyway, things work fine with older numpys, so it would be ill-advised to force people to update.
