### ISSUE TITLE
FacetGrid mislabels when using a pandas.DataFrame with dtype=object

### ISSUE THREAD

**Issue by Unode** [mwaskom/seaborn#1154] opened 2017-04-07 18:32 UTC
As seen in this [Jupyter notebook (in HTML format)](http://jsbin.com/tafofahece) - ([gist of the HTML here](https://gist.github.com/anonymous/6d2d02a24e428bfc19315726c7084899)), using `FacetGrid` and `seaborn.boxplot` may produce incorrect/incomplete outputs.

This problem appears primarily when data has gaps or missing values, the target column is used for `FacetGrid(row=...)` and the dtype of said column is `object`. The problem is gone when columns are converted to `category`. Detailed examples on the linked HTML document.

**Comment by mwaskom** [comment] 2017-04-07 18:48
Duplicate of #1151. Use `factorplot`.

**Closed by mwaskom** 2017-04-07 18:48 UTC
