### ISSUE TITLE
heatmap not annoting

### ISSUE THREAD

**Issue by TejasPatil80178** [mwaskom/seaborn#3679] opened 2024-04-21 10:32 UTC
sns.heatmap function annot = True is not annoting all the values in the data, it is only annoting for the first row.
I tried reinstalling the library but still the same issue.

please let me know a fix. Thanks!
![Screenshot 2024-04-21 4 00 30 PM](https://github.com/mwaskom/seaborn/assets/62493951/be934b79-9464-475b-8c04-dfd23efeaf23)

**Comment by thuiop** [comment] 2024-04-21 11:52
Duplicate of #3478. TL;DR : either downgrade matplolib to 3.7 or upgrade seaborn to 0.13. Also in the future please post your code as text instead of as an image, as it takes more effort to replicate if we have to rewrite the code manually instead of copypasting.

**Closed** 2024-04-21 12:23 UTC
