### ISSUE TITLE
Heatmap: Only one cell annotated (with the wrong color) when using annot=True

### ISSUE THREAD

**Issue by halflings** [mwaskom/seaborn#677] opened 2015-08-17 13:11 UTC
When I plot a heatmap and want to show the given values on top of the cells, only the cell at the bottom/left of the heatmap gets annotated.

    import numpy as np
    import seaborn as sns
    import matplotlib.pyplot as plt
    m = np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
    sns.heatmap(m, annot=True, fmt='d')
    plt.show()

![heatmap_bug2](https://cloud.githubusercontent.com/assets/1626936/9305444/c84bc45a-44f1-11e5-8356-24951f955862.png)

Another problem is that the text color is poorly chosen, like in this example:

    m = np.array([[50000, 50000, 50000], [50000, 50000, 50000], [1, 50000, 50000]])
    sns.heatmap(m, annot=True, fmt='d')
    plt.show()

![heatmap_light_bug](https://cloud.githubusercontent.com/assets/1626936/9305455/cfc8d9ca-44f1-11e5-9633-fad1397c6fda.png)

I'm using seaborn 0.6.0 with Python 3.4.3 (tried with Python 2.7.9 too, and I have the same bug)

**Comment by halflings** [comment] 2015-08-17 14:05
Another example with the code provided here:
http://stanford.edu/~mwaskom/software/seaborn/examples/heatmap_annotation.html

![heatmap_flights](https://cloud.githubusercontent.com/assets/1626936/9306626/cd8cc4a2-44f9-11e5-8815-0b23164c34f7.png)
(not sure if it's related, but the labels also aren't rotated)

**Comment by mwaskom** [comment] 2015-08-17 15:04
Duplicate of https://github.com/mwaskom/seaborn/issues/619 I think

**Comment by halflings** [comment] 2015-08-17 16:28
Oh, missed that one. Using Agg did indeed fix the problem!

**Comment by mwaskom** [comment] 2015-08-17 18:42
No worries, the problems were expressed slightly differently. Glad to hear it works now.

**Closed by mwaskom** 2015-08-17 18:42 UTC
