### ISSUE TITLE
Scatterplot for 'Annual Income' and 'Monthly Debt' not showing.Other pair's scatter plot is showing OK

### ISSUE THREAD

**Issue by abhraimrb** [mwaskom/seaborn#2284] opened 2020-09-17 08:24 UTC
sns.pairplot(credit_data , x_vars = ['Annual Income','Current Credit Balance'],
             y_vars = ['Monthly Debt', 'Maximum Open Credit'], aspect = 3)

**Comment by abhraimrb** [comment] 2020-09-17 08:34
[credit_train.xlsx](https://github.com/mwaskom/seaborn/files/5237510/credit_train.xlsx). Here is the datafile, which i converted to csv format.

**Comment by mwaskom** [comment] 2020-09-17 11:45
Here is some information on how to write an actionable bug report:http://seaborn.pydata.org/installing.html#getting-help

**Comment by mwaskom** [comment] 2020-09-17 12:43
This sounds like a duplicate of #2260

**Closed** 2020-09-18 14:05 UTC
