### ISSUE TITLE
Incomplete contours when adding labels (kdeplot)

### ISSUE THREAD

**Issue by am-thyst** [mwaskom/seaborn#2119] opened 2020-06-02 17:28 UTC
So first of all I produced a contour plot using 

```python
clevs = [0, 0.00002, 0.00004, 0.00006, 0.00008, 0.00010, 0.00012, 0.00014, 0.00016, 0.00018, 0.00020]
sns_plot_us = sns.kdeplot(xx, yy, levels=clevs, colors='red', shade=False, cbar=False, linestyles='--')
sns_plot_us = sns.kdeplot(xx_2, yy_2, levels=clevs, colors='black', shade=False, cbar=False)
sns_plot_us.set(xlim=(0, 3000), ylim=(0, 20))
```

![image](https://user-images.githubusercontent.com/41115380/83549676-96afb480-a4fd-11ea-815d-3b41701c8f27.png)

I wanted to change several things, including:

- Make the first plot blue rather than red, and bring it to the top
- Reduce the levels on the solid line plot 
- Add contour labels.

So I altered the _bivariate_kdeplot function in seaborn, as is shown[ here](https://stackoverflow.com/questions/33169093/how-to-label-a-seaborn-contour-plot). I basically just amended `return ax` to `return ax, cset` so I could get the contourset.

Then I ran:
```python
clevs = [0, 0.00002, 0.00004, 0.00006, 0.00008, 0.00010, 0.00012, 0.00014, 0.00016, 0.00018, 0.00020]
clevs_2 = [0, 0.00004, 0.00008, 0.00012, 0.00016, 0.00020]
sns_plot_us, cs  = sns.kdeplot(xx, yy, levels=clevs, colors='blue', shade=False, cbar=False,  linestyles='--', zorder=100)
sns_plot_us, cs_2 = sns.kdeplot(xx_2, yy_2, levels=clevs_2, colors='black',shade=False, cbar=False)
plt.clabel(cs, cs.levels, inline=True)
plt.clabel(cs_2, cs_2.levels, inline=True)
sns_plot_us.set(xlim=(0, 3000), ylim=(0, 20))
```
Which broke something and I ended up with this:
![image](https://user-images.githubusercontent.com/41115380/83550640-112d0400-a4ff-11ea-8e51-93ff0c9b8565.png)

Altering the  _bivariate_kdeplot function to label the contours works on simple data, like what's given in the example linked above. So, any idea what's gone wrong here and how I can fix it?

**Comment by mwaskom** [comment] 2020-06-02 17:40
I'm not sure, sorry. If you have a question about the stackoverflow answer you are modifying, I would suggesting leaving a comment on the answer, or making a fully reproducible example and adding a new question.

**Comment by mwaskom** [comment] 2020-06-02 17:40
Closing because "my hack isn't working properly" isn't an issue for seaborn development.

**Closed by mwaskom** 2020-06-02 17:40 UTC
