### ISSUE TITLE
lmplot not honoring my 'hue' definition column.

### ISSUE THREAD

**Issue by xguse** [mwaskom/seaborn#826] opened 2016-01-19 18:51 UTC
Here is a screen shot that shows the dataframe in question and the resulting plot.

I am completely befuddled.

![](http://i.imgur.com/4YZsmdn.png)

Any guidance would be very helpful!

Gus

**Comment by mwaskom** [comment] 2016-01-19 19:04
Probably a dupe of #802

**Comment by xguse** [comment] 2016-01-19 20:50
@mwaskom: That would affect the legend too?  WT and WKO are both assigned the same color in the legend.  In #802 the legend still lists the color of group 'p1' correctly as purple.

I will try building from the repo and see if it fixes it, but this seems to behave at least a bit different than #802.

**Comment by xguse** [comment] 2016-01-19 21:09
FYI: building from git commit 1210fefccb8db1ce51c3571e1893a1872d05d5c9 does not fix it.

**Comment by mwaskom** [comment] 2016-01-19 21:12
I'm not sure what's going on in your legend, but I can't see the 143 cells before this plot. I suspect you've set the default palette to be `["b", "g"]` somewhere in your notebook and so it is cycling.

**Comment by xguse** [comment] 2016-01-19 21:21
> I'm not sure what's going on in your legend, but I can't see the 143 cells before this plot.

fair enough: http://nbviewer.jupyter.org/github/xguse/ipy_notebooks/blob/master/BCH/Amy/2016-01-11__16S_exploration.ipynb

> I suspect you've set the default palette to be ["b", "g"] somewhere in your notebook and so it is cycling.

I suppose that is possible, but if so it happened cryptically.  I do not set the palette directly anywhere on that notebook except for the  confusion matrix plots and that happens encapsulated in an external module.... and the palette used is 'blues'.

Thank you for your efforts.

**Comment by xguse** [comment] 2016-01-19 21:37
OK I seem to be mostly wrong.  I believe that it IS a dupe of #802 for the most part.  When I append a duplicate row for WKO (and so now WKO has more than three members) all points are plotted again and the colors are correct.

I still dont understand what was going on with the legend however.

**Closed** 2016-01-19 21:42 UTC

**Comment by mwaskom** [comment] 2016-01-19 21:50
Actually nevermind, the default palette shouldn't cycle anyway, it should switch to `husl` if the number of hue levels exceeds the length of the palette. So I'm not sure, but I imagine it's just the matplotlib legend code getting confused in light of the other color issues.
