### ISSUE TITLE
bug:seaborn cannot use plus (+) as outlier

### ISSUE THREAD

**Issue by fancz2002** [mwaskom/seaborn#1157] opened 2017-04-15 08:36 UTC
To reproduce this:

```
import matplotlib.pyplot as plt
x = [0.15, 0.11, 0.06, 0.06, 0.12, 0.56]
plt.boxplot(x,sym='+')
plt.show()
```

The outliers display correctly.

However, after I add `import seaborn`, the outliers disappear.

**Comment by mwaskom** [comment] 2017-04-15 12:19
Duplicate of #102

**Closed by mwaskom** 2017-04-15 12:19 UTC
