### ISSUE TITLE
Not able to customise legends for histplots

### ISSUE THREAD

**Issue by shivendra90** [mwaskom/seaborn#2632] opened 2021-08-05 10:28 UTC
In seaborn, it seems one cannot customise legends for histplots. I'm not sure about the other categorical plots, but it is possible for scatter plots.

```
# This works
f, ax = pt.subplots()

x = np.arange(0, 6)
y1 = np.random.randint(1, 50, 6)
y2 = np.random.randomint(1, 25, 6)

sns.scatterplot(x=x, y=y1, color="blue", ax=ax)
sns.scatterplot(x=x, y=y2, color="red", ax=ax)
ax.legend(fontsize="medium")
plt.show()

# This does not work
f, ax = plt.subplots()

sns.histplot(x=x, y=y1, ax=ax)
sns.histplot(x=x, y=y2, ax=ax)
ax.legend(fontsize="medium")
```
For hisplots, I get the error `No handles with labels found to put in legend.` Any way to have `ax.legend` function properly?

**Comment by mwaskom** [comment] 2021-08-05 10:55
Duplicate of #2280

**Closed by mwaskom** 2021-08-05 10:55 UTC
