### ISSUE TITLE
When only 3 rows in data sets, scatter plots uses grey-scale colors.

### ISSUE THREAD

**Issue by cammil** [mwaskom/seaborn#920] opened 2016-05-10 08:14 UTC
4 or more rows appears to use the expected color palette. However 3 uses unexpected black-grey-white colours for the points.

**Comment by mmagnuski** [comment] 2016-05-10 09:20
Are you referring to a specific seaborn plotting function?
Generally - matplotlib's scatter can act weird with 3 points - RGB values are interpreted as colormap values. The documentation of scatter says that color would be read as rgb (not as colormap values) if it is a 2d numpy array (1 by 3). Unfortunatelly I've had problems with 1 by 3 too. Only when I passed a 3 by 3 (the same rgb vavlues for each observation) it worked well.

**Comment by cammil** [comment] 2016-05-10 09:51
I checked with lmplot, regplot and pairplot (off diagonal plots). They all produced 3 dots which were white, grey and black.

**Comment by mwaskom** [comment] 2016-05-10 14:39
Duplicate of #840

**Closed by mwaskom** 2016-05-10 14:39 UTC
