### ISSUE TITLE
Importing seaborn causes MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by sandpiturtle** [mwaskom/seaborn#1596] opened 2018-10-25 22:03 UTC
```python3
import seaborn as sns
```
This causes:
```
/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning: 
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
```

python 3.6

**Comment by mwaskom** [comment] 2018-10-25 22:06
Duplicate of #1594

It's an irritating, but irrelevant warning.

**Closed by mwaskom** 2018-10-25 22:06 UTC
