### ISSUE TITLE
"sharey=True" causes incorrect axis labels

### ISSUE THREAD

**Issue by nikhil153** [mwaskom/seaborn#1780] opened 2019-07-20 16:39 UTC
Identical dataframe creates incorrect axis labels depending "sharey" argument. The issue is occurs when catplot is used with multiple columns or under matlplotlib subplots. 

example code: 
1. sharey=False

`with sns.axes_style("whitegrid"):
    sns.catplot(x="AGE_AT_SCAN", y="qc", hue="DX_GROUP", kind="violin", split=True, height=10, aspect=1, col='Outlier', palette=palette, data=bug_df,sharey=False)`

![image](https://user-images.githubusercontent.com/7978607/61581335-27022800-aaeb-11e9-956b-3cc2c2b76483.png)

2. sharey=True

`with sns.axes_style("whitegrid"):
    sns.catplot(x="AGE_AT_SCAN", y="qc", hue="DX_GROUP", kind="violin", split=True, height=10, aspect=1, col='Outlier', palette=palette, data=bug_df,sharey=True)`

![image](https://user-images.githubusercontent.com/7978607/61581341-4305c980-aaeb-11e9-8a9f-943643ab4555.png)

**Comment by mwaskom** [comment] 2019-07-20 18:24
Duplicate of #1771

**Closed by mwaskom** 2019-07-20 18:24 UTC
