### ISSUE TITLE
Legend with colorbar

### ISSUE THREAD

**Issue by JanPalasek** [mwaskom/seaborn#3531] opened 2023-10-18 13:49 UTC
Could we get colorbar inside legend for continuous color variables? It would much better express continuous values e.g. in scatterplots. Also we could have it neatly alongside other things like marker type, size, etc.

Inspiration from [ggplot2](https://ggplot2.tidyverse.org/reference/guide_colourbar.html):

![image](https://github.com/mwaskom/seaborn/assets/26582151/7e02ae28-fb54-492d-a531-cb851124c052)

**Comment by mwaskom** [comment] 2023-10-18 14:07
Duplicate of https://github.com/mwaskom/seaborn/issues/2172

The short answer is that I agree this would be nice but legend and colorbars work *very* differently in matplotlib so it's not trivial. If it's added, it will probably only be in the objects interface.

**Closed by mwaskom** 2023-10-18 14:07 UTC

**Comment by JanPalasek** [comment] 2023-10-19 07:18
@mwaskom Would u accept some PR, if I managed to implement it?

**Comment by mwaskom** [comment] 2023-10-19 10:55
Probably not, sorry, this isn't going to be something that's solved well in a simple well-contained PR.
