### ISSUE TITLE
Suggestion: seaborn.catplot(kind = ['box', 'strip'] ...)

### ISSUE THREAD

**Issue by freekvh** [mwaskom/seaborn#1781] opened 2019-07-24 12:45 UTC
Dear dev,

I like combining box and strip plots, I also like making optimal use of seaborn categorical plotting features, i.e. like this:

    sns.catplot(kind='point', data=alldata_long, x='gene_id', y='TPM', hue='Exp condition', row='Lib prep', height=3, aspect=4)

I would like to be able to combine both approaches, would the command from the title of this post be an option? At the moment I am having difficulties combining the two plots in a row and col split catplot...

Highest regards,

Freek.

**Comment by mwaskom** [comment] 2019-07-24 14:49
Thanks, this is a duplicate of #1484

**Closed by mwaskom** 2019-07-24 14:49 UTC
