### ISSUE TITLE
Facetgrid maps incorrect hue to scatter plot

### ISSUE THREAD

**Issue by paperzebra** [mwaskom/seaborn#848] opened 2016-02-03 11:12 UTC
When the category you are mapping out to use as the hue in facetgrid contains three items then they do not colour as they should, instead taking on a grayscale when plotted using pyplot scatter. See attached code and image.  

This issue was fixed for lmplot from Seaborn 0.6 to 0.7, but is still present in the facetgrid.

![seaborn](https://cloud.githubusercontent.com/assets/17030467/12780601/ba9a3d00-ca66-11e5-9ad1-8e85b9addf11.png)
Points from category 'three'  circled in red.

python 2.7
pandas version: 0.17.1
numpy version:  1.10.1
matplotlib version: 1.5.1
seaborn version: 0.7.0

    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    import seaborn as sns

    df = pd.DataFrame(np.random.randint(0,100,size=(15, 4)), columns=list('ABCD'))

    lst = ['one', 'two', 'two', 'three', 'three', 'three', 'four', 'four', 'four',
    'four', 'five', 'five', 'five', 'five', 'five']

    df["color"] = lst

    print df

    graph = sns.FacetGrid(data=df, hue='color')
    graph.map(plt.scatter, 'A', 'B', s=300,
              alpha=1, edgecolors='black', linewidths=1)
    plt.legend(loc='center left', bbox_to_anchor=(1.01, 0.5))
    plt.show()

**Comment by mwaskom** [comment] 2016-02-03 17:35
Duplicate of #848

**Closed** 2016-02-03 17:35 UTC
