### ISSUE TITLE
A non-string or non-byte (e.g., int) pandas column name raises TypeError

### ISSUE THREAD

**Issue by tnigon** [mwaskom/seaborn#2350] opened 2020-11-13 00:17 UTC
I have a dataframe that has some column names as integers (e.g., 1, 2, 3, 4, etc.) indicating a number of features used in a machine learning problem. However, as of seaborn version 0.11.0, a TypeError is raised because seaborn never checks for vectors/columns in `data` if `x` or `y` are integers.

## Example
```
import seaborn as sns
import numpy as np
import pandas as pd

data = np.random.randint(5,30,size=(10,2))
df = pd.DataFrame(data, columns=['x', 1])
ax = sns.scatterplot(x='x', y=1, data=df)
```

```
Traceback (most recent call last):

  File "<ipython-input-91-7086dc4312d0>", line 1, in <module>
    ax = sns.scatterplot(x='x', y=1, data=df)

  File "C:\Users\nigo0024\Anaconda3\envs\sip_run_2\lib\site-packages\seaborn\_decorators.py", line 46, in inner_f
    return f(**kwargs)

  File "C:\Users\nigo0024\Anaconda3\envs\sip_run_2\lib\site-packages\seaborn\relational.py", line 794, in scatterplot
    p = _ScatterPlotter(

  File "C:\Users\nigo0024\Anaconda3\envs\sip_run_2\lib\site-packages\seaborn\relational.py", line 580, in __init__
    super().__init__(data=data, variables=variables)

  File "C:\Users\nigo0024\Anaconda3\envs\sip_run_2\lib\site-packages\seaborn\_core.py", line 604, in __init__
    self.assign_variables(data, variables)

  File "C:\Users\nigo0024\Anaconda3\envs\sip_run_2\lib\site-packages\seaborn\_core.py", line 667, in assign_variables
    plot_data, variables = self._assign_variables_longform(

  File "C:\Users\nigo0024\Anaconda3\envs\sip_run_2\lib\site-packages\seaborn\_core.py", line 895, in _assign_variables_longform
    if val is not None and len(data) != len(val):

TypeError: object of type 'int' has no len()
```

## Version info:
```
sns.__version__
import matplotlib
matplotlib.__version__
```

```
'0.11.0'
'3.3.3'
```

**Comment by tnigon** [comment] 2020-11-13 00:28
I implemented a fix for this, but wasn't able to commit as a new branch due to permission issues. Here is the code I modified:

seaborn/_core.py
Replaced lines 871-907 with:
```
        # The caller will determine the order of variables in plot_data
        for key, val in kwargs.items():

            if isinstance(val, (str, bytes)):
                # String inputs trigger __getitem__
                if val in data:
                    # First try to get an entry in the data object
                    plot_data[key] = data[val]
                    variables[key] = val
                elif val in index:
                    # Failing that, try to get an entry in the index object
                    plot_data[key] = index[val]
                    variables[key] = val
                else:
                    # We don't know what this name means
                    err = f"Could not interpret value `{val}` for parameter `{key}`"
                    raise ValueError(err)

            else:

                # Check if the value is a data column, but not str or byte type (e.g., int column name)
                if val in data:
                    # If so, get an entry in the data object
                    plot_data[key] = data[val]
                    variables[key] = val

                # Raise when data is present and a vector can't be combined with it
                elif isinstance(data, pd.DataFrame) and not isinstance(val, pd.Series):
                    if val is not None and len(data) != len(val):
                        val_cls = val.__class__.__name__
                        err = (
                            f"Length of {val_cls} vectors must match length of `data`"
                            f" when both are used, but `data` has length {len(data)}"
                            f" and the vector passed to `{key}` has length {len(val)}."
                        )
                        raise ValueError(err)

                # Otherwise, assume the value is itself a vector of data
                else:
                    plot_data[key] = val

                    # Try to infer the name of the variable
                    variables[key] = getattr(val, "name", None)
```

**Comment by mwaskom** [comment] 2020-11-13 12:07
Duplicate of #2279

**Closed by mwaskom** 2020-11-13 12:07 UTC
