### ISSUE TITLE
seaborn v0.8 changes matplotlib font.size on import

### ISSUE THREAD

**Issue by tritemio** [mwaskom/seaborn#1229] opened 2017-07-09 23:21 UTC
Seaborn v0.8 should not change any plot style at import time.
However, it does revert to font size to the matplotlib default:

```python
import matplotlib as mpl
mpl.rcParams['font.size'] = 12
print(mpl.rcParams['font.size'])

import seaborn as sns

print(mpl.rcParams['font.size'])
```

Output:

```
12.0
10.0
```

**Comment by mwaskom** [comment] 2017-07-09 23:47
I'm not sure seaborn is doing this aside from the fact that it imports `matplotlib.pyplot`:

```python
import matplotlib as mpl
mpl.rcParams['font.size'] = 12
print(mpl.rcParams['font.size'])
import matplotlib.pyplot as plt
print(mpl.rcParams['font.size'])
```
Ouput:
```
12.0
10.0
```

**Comment by tritemio** [comment] 2017-07-10 00:04
I see, never mind. 

@tacaswell, is there anything matplotlib can do about it?

**Comment by mwaskom** [comment] 2017-07-10 00:25
My guess is that the default rcParams actually get applied when `matplotlib.pyplot` is imported, not on the import of `matplotlib` itself?

**Comment by mwaskom** [comment] 2017-07-10 00:59
Hm [maybe not](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L1094). I don'tknow, but I'm going to close this on the seaborn side.

**Closed by mwaskom** 2017-07-10 00:59 UTC

**Comment by tacaswell** [comment] 2017-07-10 02:43
I can not reproduce this with 2.0.2  What versions Matplotlib are you using?

```python
import matplotlib as mpl
print(mpl.rcParams['font.size'])
mpl.rcParams['font.size'] = 12
print(mpl.rcParams['font.size'])
import matplotlib.pyplot as plt
print(mpl.rcParams['font.size'])
```

In `~/.config/matplotlib/matplotlibrc`

```
font.size: 5
```

Gives

```
(widgets-2017) ✔ ~
21:40 $ python /tmp/test.py 
5.0
12.0
12.0
(widgets-2017) ✔ ~
21:40 $ conda list matplotlib
# packages in environment at /home/tcaswell/mc3/envs/widgets-2017:
#
matplotlib                2.0.2               np112py36_0  
```

**Comment by tritemio** [comment] 2017-07-10 02:47
I have 2.0.2, and tried both python 35 and 36 on mac os:

```
$ conda list matplotlib
# packages in environment at /Users/anto/miniconda3:
#
matplotlib                2.0.2               np112py35_0  
```

**Comment by mwaskom** [comment] 2017-07-10 11:35
FWIW I was seeing this on 2.0.1/python2.7

```
[mlw-mbair Desktop]$ conda list matplotlib
# packages in environment at /Users/mwaskom/anaconda:
#
matplotlib                2.0.1               np112py27_0
```

**Comment by mwaskom** [comment] 2017-07-10 15:53
I tried this on my ubuntu/py35/2.0.2 setup and was not able to reproduce.

I think signs point to an OSX dependency?

**Comment by tacaswell** [comment] 2017-07-11 14:07
I am having trouble imagining how this has an OS dependence..

What backend are you using on mac (I assume Qt or OSX)?

Does it happen in a plain python shell on mac?  That should isolate if this is related to the IPython integration.

**Comment by mwaskom** [comment] 2017-07-11 14:14
OK yes interesting. On my Mac, I only see this in the notebook, not in terminal IPython or the plain Python shell. Here is the sum total of what I'm running in the notebook; I don't have any custom matplotlibrc files (that I'm aware of; is there an mpl function that will show the paths for all matplorlibrc files that are influencing the current session?)

```python
import matplotlib as mpl
print(mpl.get_backend())
print(mpl.rcParams['font.size'])
mpl.rcParams['font.size'] = 12
print(mpl.rcParams['font.size'])
import matplotlib.pyplot as plt
print(mpl.rcParams['font.size'])
```
```
module://ipykernel.pylab.backend_inline
10.0
12.0
12.0
```

**Comment by mwaskom** [comment] 2017-07-11 14:15
And to close the loop -- I do see this in the notebook on Ubuntu/3.6/2.0.2. I think yesterday I probably tested in terminal IPython. I'm ashamed of my experimental design :)
