### ISSUE TITLE
[histplot] KDE line cannot change the color

### ISSUE THREAD

**Issue by Vuong-Chu** [mwaskom/seaborn#2680] opened 2021-10-16 11:38 UTC
I am using Python 3.8.10, seaborn 0.11.2

As you can see in the code below, the color (in line_kws) did not render the KDE line. I mean the kde line should be in red instead of blue.

```python
import numpy as np
import seaborn as sns

x = np.random.normal(-1,1,1000)

fig, ax = plt.subplots(figsize=(10,10))
sns.histplot(x,kde=True,line_kws={"color":"red","linewidth":3})
```

**Comment by mwaskom** [comment] 2021-10-16 11:55
Duplicate of https://github.com/mwaskom/seaborn/issues/2344, this is intentional but you can easily work around it as its demonstrated there.

**Closed by mwaskom** 2021-10-16 11:55 UTC
