### ISSUE TITLE
Seaborn plot Chinese error

### ISSUE THREAD

**Issue by GoingMyWay** [mwaskom/seaborn#1095] opened 2017-01-18 03:39 UTC
here is my sample data `cities_counter[:10]`

    [('上海', 285), ('杭州', 225), ('北京', 163), ('广州', 136), ('南京', 130), ('武汉', 124), ('深圳', 88), ('温州', 67), ('苏州', 66), ('宁波', 45)]

and I want to make a bar plot with Seaborn and Matplotlib, so here is my code

    >>> sns.set(style="whitegrid")
    >>> sns.set_color_codes("pastel")
    >>> sns.barplot(x=[k for k, _ in cities_counter[:10]], y=[v for _, v in cities_counter[:10]])

and the result is here: https://i.stack.imgur.com/pXHAE.png

ENV:

 - Windows 10
 - Python 2,7

How can I plot Chinese character?

I have tried with the following code

```
import matplotlib as mpl
mpl.rcParams['font.sans-serif'] = ['SimHei']
mpl.rcParams['font.serif'] = ['SimHei']
import seaborn as sns
sns.set_style("darkgrid",{"font.sans-serif":['simhei', 'Arial']})
```

And downloaded SimHei.ttf from this issue https://github.com/mwaskom/seaborn/issues/1009

**Comment by mwaskom** [comment] 2017-01-18 12:48
Duplicate of #1009?

**Closed** 2017-07-07 20:33 UTC
