### ISSUE TITLE
Faceting messes up categorical axis assignments in barplots

### ISSUE THREAD

**Issue by Pweidemueller** [mwaskom/seaborn#3399] opened 2023-06-22 16:09 UTC
I want to draw a barplot facetted for different cateogories in a data frame.

Each sub0barplot shows has as a y-axis another categorical variable. I expect the the y-axes to be shared across facets. If a specific y-category doesn't exist for a specific facet I expect seaborn to either throw an error or properly draw the bars only for those y-cateogories that are present and not draw any bars for those categories that are not present.

However, what actually happens is seaborn just fills the bars from index 0 to whatever the maxum length of unique y-categories exists in a specific facet. Hence this producses false and wrong plots, as bars appear in the wrong places.

Please consider either throwing an error or not drawing a bar when a y-category is not present for all facets.

Example
```
iris = sns.load_dataset('iris')
iris['flowerID'] = np.tile(np.arange(0,50), 3)

tmp = iris.loc[iris.flowerID<10].iloc[4:]
tmp['flowerID'] = [str(i) for i in tmp['flowerID']]
g = sns.FacetGrid(tmp, col="species", height=8)
g.map_dataframe(sns.barplot, y='flowerID', x='sepal_length')
```
Result is the following plot: 
![image](https://github.com/mwaskom/seaborn/assets/18192128/00268b06-e6d9-489e-b5f5-6bcd397e5b51)

However for setosa flowers bars should only appear at the IDs 4-9. The seabor bar chart makes you belief the sepal lengths are assigned to IDs 1-5.
<img width="491" alt="image" src="https://github.com/mwaskom/seaborn/assets/18192128/6fdf9fd6-c375-4720-94f6-d41bb439f057">

**Comment by mwaskom** [comment] 2023-06-27 23:23
Duplicate of #3389

**Closed by mwaskom** 2023-06-27 23:23 UTC
