### ISSUE TITLE
Scatter Points with Incorrect Hue

### ISSUE THREAD

**Issue by jthurbs** [mwaskom/seaborn#840] opened 2016-01-26 21:44 UTC
I have observed an issue with hues on FacetGrids displaying scatter plots. Some of the plotted points are the incorrect color and yet appear to be represented correctly in the legend. I was able to reproduce this in the following snippet. In the generated plot, the lower left axes includes points whose marker face color is black and some that are white. I originally discovered this phenomena in a larger 3 row x n column FacetGrid with a larger number of hues. In this case, all the axes on the second row had incorrect marker face colors (either black or white). 

A second observation is that the legend is overlaid on the axes instead of being displayed to the right of the last column of axes.

``` python
import matplotlib.pyplot as plt
import seaborn as sns

tips = sns.load_dataset('tips')
g = sns.FacetGrid(tips, col="time", row="smoker", hue = 'size') # Create Grid
g = (g.map(plt.scatter, "total_bill", "tip")).add_legend()
plt.show()
```

**Image of Issue (mpl 1.5.1)**
![issue - 1 5 1 marked up](https://cloud.githubusercontent.com/assets/8389423/12626354/48a690a0-c506-11e5-9af6-4233ac56891c.png)

matplotlib version   --> 1.5.1
seaborn version     --> 0.7.0
matplotlib backend --> TkAgg
python --> 2.7.10
os --> windows 7

It appears that the issue does not occur in matplotlib version 1.4.3
**Works in mpl 1.4.3**
![no issue - 1 4 3](https://cloud.githubusercontent.com/assets/8389423/12626403/79aadcb0-c506-11e5-9f86-686b3fb3f882.png)

Huge fan of seaborn by the way. Thanks so much for all the work you put into it.

**Comment by phobson** [comment] 2016-03-23 18:43
just a note about this:
what's probably happening is matplotlib is interpreting the (r, b, g) tuple as a sequence of grayscale values since there's something else where `len(x) = 3`

**Comment by mwaskom** [comment] 2016-03-23 19:05
Yeah this was a recent change in matplotlib. I fixed some functions [here](https://github.com/mwaskom/seaborn/pull/798) but forgot about `regplot`. It's a pain because most of the functions have a number of tests assuming an rgb representation so that conversion to hex has to happen late and with care.

**Comment by mwaskom** [comment] 2016-04-25 01:17
This particular case of the issues with `plt.scatter`'s interpretation of the `c` parameter ends up being a little tricky because `FacetGrid` tries to be very general and agnostic to the functions that are passed into it. In other seaborn functions this issue is handled by forcing colors to hex representation before they are passed to `plt.scatter`, but doing that in `FacetGrid` could cause issues for other applications and I would like to avoid lots of messy special case code.

Going to punt on changing anything right now to address this, but if you are running into this problem, you can always do, e.g. `sns.FacetGrid(..., palette=sns.color_palette("deep", n_colors).as_hex())`.

**Comment by jonsedar** [comment] 2016-05-04 13:19
Aha, was banging my head against this for a few hours, so it's nice to at least have the issue confirmed! It's certainly an edge case...

@mwaskom your suggested fix doesn't seem to work for me, so I manually crafted the legend... I can post code if anyone's interested

**Comment by mwaskom** [comment] 2016-05-04 14:58
Another workaround would be to use `plt.plot` with `marker="o"` and `linestyle=""`, which will also produce a scatterplot.

**Comment by Unode** [comment] 2017-04-07 16:13
Likely related. I hit a `ValueError` while trying out the example from https://github.com/mwaskom/seaborn/issues/209#issuecomment-135807375

The exception `ValueError: Invalid RGBA argument: 0.29803921568627451` is raised by `matplotlib/colors.py`.

```
Versions:
  python-3.6.1
  matplotlib-2.0.0
  seaborn-0.7.1
```

**Comment by mwaskom** [comment] 2017-10-04 16:08
I believe this may be fixed in matplotlib 2.1 (potentially "by accident" https://github.com/matplotlib/matplotlib/issues/8658).

**Comment by mwaskom** [comment] 2017-10-24 14:03
Closing as fixed in matplotlib. Ping if that turns out not to be the case.

**Closed by mwaskom** 2017-10-24 14:03 UTC

**Comment by blsymens** [comment] 2020-04-04 19:53
I'm using matplotlib in google colab. Seems to still something messed up with my colours having only 4 records in a given category. Not sure how to solve this. 

My code: 
`sns.pairplot(data,hue='Die plate',corner = True)`

I expect to get just two colours. Also in legend I don't seem to get it right. Hopefully, someone could give me some advice. Cheers!

Output: 
![image](https://user-images.githubusercontent.com/13687285/78460120-8f675880-76be-11ea-99df-37b62270aa96.png)

**Comment by phobson** [comment] 2020-04-07 15:17
@blsymens it's hard to say what's going on without knowing what versions of python, matplotlib, seaborn you're using and what your data look like.

**Comment by blsymens** [comment] 2020-04-10 11:32
The version I use are the following: 

- Python version: 3.6
- Numpy version:1.18.2
- Pandas version: 1.0.3
- Seaborn version: 0.10.0

This is a sample of some simulated data you can use. 
[DATA.TXT](https://github.com/mwaskom/seaborn/files/4461310/DATA.TXT)

Help is very much appreciated

**Comment by MaozGelbart** [comment] 2020-05-16 09:32
@blsymens this stems from having a group with four points only and matplotlib=3.2 (see #1083 ). Meanwhile try downgrading matplotlib to 3.1.2.
