### ISSUE TITLE
histplot legend: No handles with labels found to put in legend

### ISSUE THREAD

**Issue by trenton3983** [mwaskom/seaborn#2432] opened 2021-01-12 21:32 UTC
I'm trying to move the legend for a `sns.histplot`

```python
import seaborn as sns
import pandas as pd
import numpy as np  # for test data
import random  # for test data
import calendar  # for test data

# test dataframe
np.random.seed(365)
random.seed(365)
df = pd.DataFrame({'Days': random.choices(calendar.day_name, k=1000), 'Visitors': np.random.randint(1, 121, size=(1000))})

ax = sns.histplot(data=df, x='Visitors', hue='Days', multiple="stack")
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
```
![image](https://user-images.githubusercontent.com/12875240/104376507-f6316200-54d9-11eb-9046-73a47576973f.png)

- Without trying to move the legend
![image](https://user-images.githubusercontent.com/12875240/104376621-1cef9880-54da-11eb-8666-f4f4aa6d9f70.png)

- Moving the legend in this way works fine with `sns.barplot`
```python
ax = sns.barplot(data=df, x='Days', y='Visitors', hue='Days', dodge=False, estimator=sum)
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
```
![image](https://user-images.githubusercontent.com/12875240/104376995-a4d5a280-54da-11eb-90d6-ab5ee422abe1.png)

**Comment by mwaskom** [comment] 2021-01-12 21:34
Duplicate of #2280 which has a workaround and links to some broader context.

**Closed** 2021-01-12 21:34 UTC

**Comment by trenton3983** [comment] 2021-01-12 21:38
Thanks Michael. I searched, but didn't see it. Best Regards
