### ISSUE TITLE
Annotation not showing on heatmap

### ISSUE THREAD

**Issue by legaultmarc** [mwaskom/seaborn#619] opened 2015-07-01 18:37 UTC
In version 0.6.0, annotations do not show up on the heatmap (for me at least). Here is a minimal example to reproduce the problem:

```python
import numpy as np
import seaborn
import matplotlib.pyplot as plt

data = np.random.random((5, 5))
seaborn.heatmap(data, annot=True)
plt.savefig("test.png")
````
Resulting in the following image:

![test](https://cloud.githubusercontent.com/assets/864275/8461869/981a5db4-1ffd-11e5-98ac-41562eccc080.png)

From what I understand, `annot=True` should write the matrix entries on the heatmap, like symmatplot used to do (and as shown in the documentation). Interestingly, there seems to be only one value in the bottom left corner.

**Comment by mwaskom** [comment] 2015-07-01 18:54
I can't reproduce locally:

![test](https://cloud.githubusercontent.com/assets/315810/8462338/faea392a-1fe7-11e5-8150-fd7a7163746f.png)

Can you provide some more information about your environment (matplotlib version, backend, maybe OS, etc).

**Comment by legaultmarc** [comment] 2015-07-01 19:07
Mac OS: 10.10.4
Python: 2.7.8
Numpy: 1.9.2
Matplotlib: 1.4.3, backend: MacOSX 
Seaborn: 0.7.dev and 0.6.0

This is probably platform specific, so I will see if I can fix it on my setup.

**Comment by mwaskom** [comment] 2015-07-01 19:08
First thing I would try is using a different matplotlib backend...seaborn seems to find a number of bugs in the MacOSX one.

**Comment by legaultmarc** [comment] 2015-07-01 19:10
Oh you are right, using "Agg" fixed it...
Thank you for your help.

**Comment by mwaskom** [comment] 2015-07-01 19:14
Not really sure what the actual problem is, though. Relevant code is here: https://github.com/mwaskom/seaborn/blob/master/seaborn/matrix.py#L195

Strangely, it looks like only one cell is getting annotated (so it's not a downstream drawing problem), as `len(ax.texts)` is `1`.

**Comment by mwaskom** [comment] 2015-07-01 19:19
Ah,

```python
mesh = plt.pcolormesh(data)
mesh.get_facecolors()
```
returns 

```
array([[ 0.29803922,  0.44705882,  0.69019608,  1.        ]])
```

with the MacOSX backend, but

```
array([[ 0.21776241,  0.21776241,  0.21776241,  1.        ],
       [ 0.57747023,  0.57747023,  0.57747023,  1.        ],
       [ 0.56455212,  0.56455212,  0.56455212,  1.        ],
       [ 0.1046982 ,  0.1046982 ,  0.1046982 ,  1.        ],
       [ 0.56885815,  0.56885815,  0.56885815,  1.        ],
       [ 0.98154556,  0.98154556,  0.98154556,  1.        ],
       [ 0.34694349,  0.34694349,  0.34694349,  1.        ],
       [ 0.38348328,  0.38348328,  0.38348328,  1.        ],
       [ 0.78811228,  0.78811228,  0.78811228,  1.        ],
       [ 0.6530104 ,  0.6530104 ,  0.6530104 ,  1.        ],
       [ 0.32258363,  0.32258363,  0.32258363,  1.        ],
       [ 0.97785467,  0.97785467,  0.97785467,  1.        ],
       [ 0.30634372,  0.30634372,  0.30634372,  1.        ],
       [ 0.48704345,  0.48704345,  0.48704345,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.82256056,  0.82256056,  0.82256056,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.80533642,  0.80533642,  0.80533642,  1.        ],
       [ 0.31741639,  0.31741639,  0.31741639,  1.        ],
       [ 0.24544407,  0.24544407,  0.24544407,  1.        ],
       [ 0.36724338,  0.36724338,  0.36724338,  1.        ],
       [ 0.39972319,  0.39972319,  0.39972319,  1.        ],
       [ 0.91535564,  0.91535564,  0.91535564,  1.        ],
       [ 0.84322954,  0.84322954,  0.84322954,  1.        ],
       [ 0.51718571,  0.51718571,  0.51718571,  1.        ]])
```

With one that works.

Because of how `zip()` works, this mean there is only one annotation.

Looks like a matplotlib bug?

**Comment by legaultmarc** [comment] 2015-07-01 19:27
Exactly, I have the same results on my side. It is definitely because of the weird behaviour from this matplotlib backend.

**Comment by mwaskom** [comment] 2015-07-09 03:56
Closing for now...there's a note on the install page suggesting not to use the MacOSX backend with seaborn...suppose I could make the suggesting stronger but at least I have developed a keen sense for when issues can be traced back to it :)

**Closed by mwaskom** 2015-07-09 03:56 UTC

**Comment by alechoward** [comment] 2015-10-26 07:23
Do you have any updates on this bug? I've been having trouble creating a workaround

**Comment by kyleabeauchamp** [comment] 2015-11-25 18:18
I've also hit this issue.  The Agg backend is fine for saving PNGs, but I really do want a backend that supports interactive mode.  I suppose the real answer is that we need to pressure MPL folks to improve the OSX backend.

**Comment by mwaskom** [comment] 2015-11-25 18:19
Have you tried `%matplotlib notebook`?

**Comment by kyleabeauchamp** [comment] 2015-11-25 20:01
So %matplotlib notebook and %matplotlib inline don't work in the terminal version of ipython.

In the ipython notebook, I found that %matplotlib inline gives the correctly plotted annotation while %matplotlib notebook gives the busted one-cell annotations.

**Comment by mwaskom** [comment] 2015-11-25 20:53
That is interesting about matplotlib notebook.

Have you tried a different terminal-friendly interactive backend, like TkAgg?

**Comment by kyleabeauchamp** [comment] 2015-11-25 21:04
TkAgg and QT4Agg have the same one-cell behavior as OSX.  

Here is my driver script:

```
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import time

x = np.random.normal(size=(5, 10))
sns.heatmap(x, annot=True)
plt.show()
time.sleep(3)
```

I run the driver with `python test.py --verbose-helpful`, which tells me that I have in fact loaded the target backends.  

```
matplotlib version 1.5.0
verbose.level helpful
interactive is False
platform is darwin
backend Qt4Agg version 4.11.4
```

**Comment by suntong** [comment] 2016-01-08 15:26
I can confirm what @kyleabeauchamp has reported -- QT4Agg have the same one-cell behavior as OSX

And I'm using Windows7 instead of OSX:

	Python: 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Dec  1 2015, 11:46:22) [MSC v.1900 64 bit (AMD64)]
	IPython: 4.0.0
	Matplotlib: 1.5.0
	Seaborn: 0.6.0

So this is not a OSX specific problem. Here is a link on SO that discussed the same issue:

http://stackoverflow.com/questions/34375363/seaborn-bug-inconsistent-in-heatmap-plotting
