### ISSUE TITLE
lineplot: crash in algorithm.py line 84 (numpy 1.18.1)

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#1964] opened 2020-02-15 22:21 UTC
When trying out the standard lineplot example on my machine, the code stops with an error in algorithm.py line 85:

`TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'`

line 85 is: `sample = [a.take(resampler, axis=0) for a in args]`

where `resampler` comes from the previous line `resampler = integers(0, n, n)`

and [`integers`](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.integers.html) is `np.random.default_rng().integers` which default returns an array of int64.

Probably a recent change to [`np.take`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.take.html) now checks the type of its first parameter (`indices`).
An obvious solution seems to be changing line 84 to `resampler = integers(0, n, n, dtype=np.int32)`.

numpy version 1.18.1
seaborn version 0.10.0

Just running the default example caused the crash:
```
import seaborn as sns
import numpy as np
fmri = sns.load_dataset("fmri")
ax = sns.lineplot(x="timepoint", y="signal", data=fmri)
```

**Comment by mwaskom** [comment] 2020-02-15 22:29
Duplicate of #1950

**Closed by mwaskom** 2020-02-15 22:29 UTC
