### ISSUE TITLE
Issue with lineplot - conflict with pandas

### ISSUE THREAD

**Issue by KathSe1984** [mwaskom/seaborn#3423] opened 2023-07-20 22:31 UTC
When trying to create a lineplot - with only x (datetime64 or simple int64) and y without any sophisticated arguments - the following error is raised:

> OptionError: No such keys(s): 'mode.use_inf_as_null'

This is the detailed reference to pandas:

> File [~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/seaborn/_core.py:1054](https://file+.vscode-resource.vscode-cdn.net/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/seaborn/_core.py:1054), in VectorPlotter.comp_data(self)
>    1050 axis = getattr(ax, f"{var}axis")
>    1052 # Use the converter assigned to the axis to get a float representation
>    1053 # of the data, passing np.nan or pd.NA through (pd.NA becomes np.nan)
> -> 1054 with pd.option_context('mode.use_inf_as_null', True):
>    1055     orig = self.plot_data[var].dropna()
>    1056 comp_col = pd.Series(index=orig.index, dtype=float, name=var)
> 
> File [~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/pandas/_config/config.py:441](https://file+.vscode-resource.vscode-cdn.net/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/pandas/_config/config.py:441), in option_context.__enter__(self)
>     440 def __enter__(self) -> None:
> --> 441     self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
>     443     for pat, val in self.ops:
>     444         _set_option(pat, val, silent=True)
> File [~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/pandas/_config/config.py:441](https://file+.vscode-resource.vscode-cdn.net/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/pandas/_config/config.py:441), in (.0)
>     440 def __enter__(self) -> None:
> --> 441     self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
>     443     for pat, val in self.ops:
>     444         _set_option(pat, val, silent=True)
> 
> File [~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/pandas/_config/config.py:135](https://file+.vscode-resource.vscode-cdn.net/Users/kathse/Documents/NeueFische/4_Capstone/capstone_solar_energy/notebooks/~/Documents/NeueFische/4_Capstone/capstone_solar_energy/.venv/lib/python3.11/site-packages/pandas/_config/config.py:135), in _get_option(pat, silent)
>     134 def _get_option(pat: str, silent: bool = False) -> Any:
> --> 135     key = _get_single_key(pat, silent)
>     137     # walk the nested dict
>     138     root, k = _get_root(key)

I tried multiple seaborn version, including 0.12.1 and 0.12.2. For pandas, I tried 2.0.2 and 2.0.1. Matplotlib is version 3.7.1.

I would appreciate your help and also I would like to thank you for your awesome work!!

**Comment by mwaskom** [comment] 2023-07-20 22:46
Duplicate of https://github.com/mwaskom/seaborn/issues/3350? Hard to tell without a reproducible example.

**Comment by KathSe1984** [comment] 2023-07-29 08:21
It was also not really reproducible to me. Maybe, it was solved when importing not only seaborn but also matplotlib. But this is just a vague idea.

**Comment by mwaskom** [comment] 2023-08-02 11:20
Going to close as not reproducible but can revisit if someone provides some code that demonstrates the issue on latest versions...

**Closed by mwaskom** 2023-08-02 11:20 UTC
