### ISSUE TITLE
Possible inconsistency in boxenplot thicknesses and shading

### ISSUE THREAD

**Issue by beyarkay** [mwaskom/seaborn#3001] opened 2022-09-06 10:49 UTC
Hey!

I think I found a bug, although I'm not sure if it might be intended behavior. If it is actually a bug, I'll try find the fix and flesh out a proper minimum reproducible example.

Here's an annotated plot that I generated during my day-to-day usage:

<img width="631" alt="Screenshot 2022-09-06 at 12 30 28" src="https://user-images.githubusercontent.com/33420535/188614232-f84ab5d2-00fc-47bd-9dde-a4474f27f2ec.png">

This is a fairly standard  `g = sns.catplot(...,  kind="boxen", ...)`, but have a look at the colouring for the fourth boxen in red on the two axes. On the left, the "very light red" has a width of about half the main box, but on the right the "very light red" has a width of only a quarter the main box, and the "light red" has a width of half the main box.

I feel like the red boxens should look something more like:

<img width="588" alt="Screenshot 2022-09-06 at 12 41 05" src="https://user-images.githubusercontent.com/33420535/188616018-5605b9a0-a358-446c-b2ba-7581dbbed92f.png">

So that if two boxes in a boxen plot have the same color and represent the same quantile range, they also have the same width.

Once again, it's debatable if this is a bug or not, but I thought I'd raise it and offer to help out if it was actually overlooked.

**Comment by jhncls** [comment] 2022-09-09 21:02
Related to https://github.com/mwaskom/seaborn/issues/2517

**Comment by mwaskom** [comment] 2022-09-09 21:48
Thanks @jhncls i did think this sounded familiar

**Comment by beyarkay** [comment] 2022-09-09 22:03
Okay cool, I'll make up a reproducible example in the morning. Wasn't sure if this was actually a bug or not.

**Comment by jhncls** [comment] 2022-09-10 06:35
I wouldn't call it a bug.  It is due to the way the coloring is chosen automatically for a complex type of plot. It is related to the cut-off that decides how many sub-boxes should be drawn. Often it works well. Sometimes it leads to unintuitive or inconsistent-looking results. Adding more parameters could help, but with the terrible drawback that most users would get overwhelmed with a hard-to-understand parameter for an issue that only pops up very occasionally. 

Having one or more clearly reproducible examples where things aren't looking as expected, would be helpful for someone who wants to research alternative ways to choose the coloring and/or the way to cut off, especially for figure-level plots.

**Comment by mwaskom** [comment] 2022-09-11 12:33
I don't think it's a bug exactly because it's not documented as doing anything other than what it is doing, and the "correct" behavior is a little hard to define.

Currently it generates a `light_palette` from each boxen' main color with `n` steps, where `n` is the number of letter values in each boxen. Because the boxen can have different numbers of letter values, the color ramps can have different slopes.

So what is the correct behavior? It would be possible to use `n` as `max(n_i)` where each `n_i` is what is currently used for each boxen. That would make a single-axes plot consistent but would not enforce consistency across plots (including across subplots in a `catplot` context).

There can be (in theory) an arbitrarily large number of letter values, so it's not possible to simply pick one ramp length.

Alternatively, I guess it could be possible to use the scalar factor applied to the width and apply it to the color too, but how exactly to do that? `light_palette` interpolates in RGB space so you won't quite get the same results if you just modify the luminance channel in `hls` space. And seaborn doesn't have a tool for picking arbitrary points along an interpolation line in RGB space (but maybe it should).

Even if we did that, though, the representation would still not exactly be quantitative since nothing enforces that the luminance values of the main colors are the same.

**Comment by mwaskom** [comment] 2022-09-12 11:21
Closing as duplicate of @2517; happy to continue the conversation there.

**Closed by mwaskom** 2022-09-12 11:21 UTC
Labels: mod:categorical
