### ISSUE TITLE
markers not showing on lineplot

### ISSUE THREAD

**Issue by JanHomann** [mwaskom/seaborn#2563] opened 2021-04-24 18:52 UTC
The following code does not show markers.

```
my_data = [1,2,5,3,0]
sns.lineplot(data = my_data,markers=True);
```

this code doesn't show markers either
```
ax = sns.lineplot(x = [1,2,3,4,5], y=[1,2,5,3,0],markers=True);
```

on the other hand, this code does:
```
my_data=pd.DataFrame([1,2,5,3,0])
sns.lineplot(data = my_data,markers=True);
```

seaborn version 0.11.1
matplotlib version 3.3.1

![image](https://user-images.githubusercontent.com/35338267/115969765-ae749a80-a50c-11eb-995b-8e9e9b7a0b9f.png)

**Comment by mwaskom** [comment] 2021-04-24 19:59
Duplicate of https://github.com/mwaskom/seaborn/issues/1680; see explanation there.

**Closed by mwaskom** 2021-04-24 19:59 UTC

**Comment by JanHomann** [comment] 2021-04-24 23:56
Don't you think that it would be better to introduce a logical, expected and consistent behavior? To be honest, I don't even understand the explanation that you gave in the other reported issue. But who cares in the end if it has something to do with the inner workings of matplotlib that it doesn't work as expected. I personally found it annoying that it didn't work and think immediately "bug". And so will many many other users. In my opinion it should just work as expected. 

Think about the many hours go down the drain cumulatively for all the people working with this, trying to figure out what's going on, every single person that runs into this has to play around with it like me in order to understand how to get those markers. That's is cumulatively a lot of time wasted for no reason.

**Comment by mwaskom** [comment] 2021-04-25 15:32
Just a suggestion, but that is not a very constructive way to engage with an open source project.
