### ISSUE TITLE
scatterplot - date x-axis is too wide

### ISSUE THREAD

**Issue by barashe** [mwaskom/seaborn#1641] opened 2019-01-07 10:32 UTC
When plotting a time series using scatterplot, the figure's x-axis is far too wide. 

```
df = pd.DataFrame({'Depth': {0: 0.2,
  1: 0.4,
  2: 0.4,
  3: 0.4,
  4: 0.4,
  5: 0.4,
  6: 0.6000000000000001,
  7: 0.4,
  8: 3.2,
  9: 2.0},
 'DateTimeUTC': {0: pd.Timestamp('2018-03-28 06:25:08'),
  1: pd.Timestamp('2018-03-28 06:25:49'),
  2: pd.Timestamp('2018-03-28 06:27:06'),
  3: pd.Timestamp('2018-03-28 06:32:11'),
  4: pd.Timestamp('2018-03-28 06:32:59'),
  5: pd.Timestamp('2018-03-28 06:34:02'),
  6: pd.Timestamp('2018-03-28 06:35:38'),
  7: pd.Timestamp('2018-03-28 06:37:04'),
  8: pd.Timestamp('2018-03-28 06:39:08'),
  9: pd.Timestamp('2018-03-28 06:40:52')}})

sns.scatterplot('DateTimeUTC', 'Depth', data=df)
```

![image](https://user-images.githubusercontent.com/10500355/50763117-97480b00-1277-11e9-9405-17733e5e36b6.png)

I got the same results on different python versions, using seaborn 0.9.0

When lineplot is used instead, the problem does not occur.

**Comment by CRiddler** [comment] 2019-01-07 20:55
The issue you're experiencing isn't entirely seaborn's fault. Plotting with dates is a little different than plotting "typical" numbers. I'd suggest diving down to matplotlib to plot your data if you want to plot dates. Here's an example that may help you out. Potentially to make seaborn more flexible, we could add a type check to check for a datetime dtype and call `ax.plot_date` instead of `ax.scatter` to account for this?

    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt

    df = pd.DataFrame({'Depth': [0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.6, 0.4, 3.2, 2.0],
                       'DateTimeUTC': [pd.Timestamp('2018-03-28 06:25:08'),
                                       pd.Timestamp('2018-03-28 06:25:49'),
                                       pd.Timestamp('2018-03-28 06:27:06'),
                                       pd.Timestamp('2018-03-28 06:32:11'),
                                       pd.Timestamp('2018-03-28 06:32:59'),
                                       pd.Timestamp('2018-03-28 06:34:02'),
                                       pd.Timestamp('2018-03-28 06:35:38'),
                                       pd.Timestamp('2018-03-28 06:37:04'),
                                       pd.Timestamp('2018-03-28 06:39:08'),
                                       pd.Timestamp('2018-03-28 06:40:52')]})

    fig, axes = plt.subplots(3, 1, figsize=(10, 8))
    ax1, ax2, ax3 = axes.flatten()

    # seaborn plots an empty scatter to get the current color/size rotation
    ## Adding the scout changes the xaxis relative to when we don't add the scout
    scout = ax1.scatter([], [])
    scout.remove()

    # Seaborn converts plotting inputs to numpy arrays
    x = np.asarray(df.DateTimeUTC)
    y = np.asarray(df.Depth)

    ax1.scatter(x, y)
    ax1.set_title("Plotting scatter how seaborn does internally")
    ax1.text(1.01, 0.5, 
             s=("This is the plot that\n"
                "we first plotted an empty 'scout' on\n"
                "which is how seaborn does it"), 
              transform=ax1.transAxes)
     
    ax2.scatter(x, y)
    ax2.set_title("Plotting dates as a normal scatterplot")
    ax2.text(1.01, 0.5, 
             s=("This is the plot that\n"
                "we did not plot an empty 'scout' on\n"
                "however our xaxis doesnt look quite right\n"
                "just yet, meaning that the scout wasn't\n"
                "entirely at fault for the oddly aligned xaxis"), 
             transform=ax2.transAxes)
    
    ax3.plot_date(x, y)
    ax3.set_title("using Axes.plot_date to plot dates as a scatterplot")
    ax3.text(1.01, 0.5, 
             s=("We used plot_date to create this plot\n"
                "the xaxis is scaled correctly"), 
             transform=ax3.transAxes)   
    
    fig.tight_layout()

![download](https://user-images.githubusercontent.com/31414128/50792827-230f6680-127b-11e9-843c-3cbda8c8c479.png)

**Comment by ImportanceOfBeingErnest** [comment] 2019-03-09 00:56
That is definitely a matplotlib issue. See https://github.com/matplotlib/matplotlib/issues/7413. The problem is the autoscaling of collections.

**Comment by mwaskom** [comment] 2019-03-09 13:57
Closing as matplotlib issue.

**Closed by mwaskom** 2019-03-09 13:57 UTC
