### ISSUE TITLE
Boxplot throws Numpy TypeError

### ISSUE THREAD

**Issue by mikkokotila** [mwaskom/seaborn#2736] opened 2022-01-29 18:42 UTC
Coming back to this after some time, a new error popped up with code that has worked fine for years. 

The way I'm calling it on my code:

```
    p = sns.boxplot(data=data,
                    x=x,
                    y=y,
                    hue=hue,
                    palette=palette)
```

The error I get:

```
Traceback (most recent call last):
  File "test_script.py", line 418, in <module>
    box_full(df)
  File "test_script.py", line 223, in box_full
    ast.box(data=df,
  File "/Users/upstairs/dev/astetik/astetik/plots/box.py", line 120, in box
    p = sns.boxplot(data=data,
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/seaborn/categorical.py", line 2251, in boxplot
    plotter.plot(ax, kwargs)
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/seaborn/categorical.py", line 509, in plot
    self.draw_boxplot(ax, boxplot_kws)
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/seaborn/categorical.py", line 470, in draw_boxplot
    artist_dict = ax.boxplot(box_data,
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 3745, in boxplot
    bxpstats = cbook.boxplot_stats(x, whis=whis, bootstrap=bootstrap,
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 1233, in boxplot_stats
    q1, med, q3 = np.percentile(x, [25, 50, 75])
  File "<__array_function__ internals>", line 5, in percentile
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3867, in percentile
    return _quantile_unchecked(
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3986, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3564, in _ureduce
    r = func(a, **kwargs)
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4112, in _quantile_ureduce_func
    r = _lerp(x_below, x_above, weights_above, out=out)
  File "/Users/upstairs/opt/miniconda3/envs/wip/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4009, in _lerp
    diff_b_a = subtract(b, a)
TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by mwaskom** [comment] 2022-01-29 20:15
Hi, it is really impossible to provide any help here without your data, or ideally code to generate a small dataset than can reproduce the error. Please also specify the versions of relevant libraries (i.e. at least the ones you see in the traceback).

**Comment by mikkokotila** [comment] 2022-01-29 20:39
Thanks :) 

The error can be seen to manifest [here](https://github.com/autonomio/astetik/runs/4992095981?check_suite_focus=true#step:6:151) as part of Github CI. All the versions are visible in there.

A Google Colab which runs exactly the same code but does not reproduce the error is [here](https://colab.research.google.com/drive/1VL4-0UQrf3jEDDFFu8fD6exfU7gg75Pv?usp=sharing). 

I've also tested on my local, where the error does manifest.

<details>
  <summary>Versions from the local machine where the error also manifests.</summary>
  
```
  Using cached astetik-1.11.1-py3-none-any.whl (5.4 MB)
Requirement already satisfied: patsy in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (0.5.2)
Requirement already satisfied: seaborn in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (0.11.2)
Requirement already satisfied: sklearn in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (0.0)
Requirement already satisfied: pandas in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (1.3.2)
Requirement already satisfied: numpy in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (1.21.2)
Collecting geonamescache
  Using cached geonamescache-1.3.0-py3-none-any.whl (2.6 MB)
Requirement already satisfied: statsmodels in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (0.12.2)
Requirement already satisfied: wrangle in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (0.6.9)
Requirement already satisfied: IPython in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from astetik) (7.26.0)
Requirement already satisfied: pickleshare in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (0.7.5)
Requirement already satisfied: matplotlib-inline in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (0.1.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (3.0.20)
Requirement already satisfied: pexpect>4.3 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (5.0.5)
Requirement already satisfied: backcall in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (0.2.0)
Requirement already satisfied: decorator in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (5.0.9)
Requirement already satisfied: pygments in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (2.10.0)
Requirement already satisfied: appnope in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (0.1.2)
Requirement already satisfied: jedi>=0.16 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (0.18.0)
Requirement already satisfied: setuptools>=18.5 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from IPython->astetik) (58.0.4)
Requirement already satisfied: python-dateutil>=2.7.3 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from pandas->astetik) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from pandas->astetik) (2021.1)
Requirement already satisfied: six in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from patsy->astetik) (1.16.0)
Requirement already satisfied: matplotlib>=2.2 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from seaborn->astetik) (3.4.3)
Requirement already satisfied: scipy>=1.0 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from seaborn->astetik) (1.7.1)
Requirement already satisfied: scikit-learn in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from sklearn->astetik) (1.0)
Requirement already satisfied: keras in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from wrangle->astetik) (2.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from jedi>=0.16->IPython->astetik) (0.8.2)
Requirement already satisfied: pillow>=6.2.0 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn->astetik) (8.3.2)
Requirement already satisfied: cycler>=0.10 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn->astetik) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn->astetik) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn->astetik) (1.3.2)
Requirement already satisfied: ptyprocess>=0.5 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from pexpect>4.3->IPython->astetik) (0.7.0)
Requirement already satisfied: wcwidth in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->astetik) (0.2.5)
Requirement already satisfied: ipython-genutils in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from traitlets>=4.2->IPython->astetik) (0.2.0)
Requirement already satisfied: joblib>=0.11 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from scikit-learn->sklearn->astetik) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./opt/miniconda3/envs/wip/lib/python3.8/site-packages (from scikit-learn->sklearn->astetik) (2.2.0)
Installing collected packages: geonamescache, astetik
Successfully installed astetik-1.11.1 geonamescache-1.3.0
```
</details>

**Comment by mwaskom** [comment] 2022-01-29 22:29
Thanks for sharing these links, but I still don't have an example I can reproduce on my machine. As you note, the colab notebook does not produce the error, and it seems to be using some sort of wrapper library.  I would first have to install that library, and then I would need to work out how it is calling seaborn internally. When asking people to spend time helping you, please do not make things more difficult than they need to be.

**Comment by jhncls** [comment] 2022-01-30 02:27
This error seems to pop up when the y-values are booleans. It might depend on numpy versions (I tested with `1.20.3`). A simple reproducible example would be:
```python
sns.boxplot(x=[1, 1], y=[False, True])
```
Also, directly via matplotlib, `plt.boxplot([False, True])` gives the same error.  A workaround would be to explicitly convert the values to integers (either by the user, or in the seaborn code).  But it is very hard to imagine a practical case where a boolean array of values would generate a useful boxplot. (I think no other seaborn functions give this error, apart from a violinplot that uses an inner boxplot.)

**Comment by mwaskom** [comment] 2022-01-30 13:12
Thanks @jhncls, that's helpful! I agree that a boxplot of booleans does not make a lot of sense, but the most local place to fix this (by casting to float) would be within `matplotlib.cbook.boxplot_stats`.

**Comment by mwaskom** [comment] 2022-02-10 12:34
Gonna close this as I don't think it's worth putting in a dedicated fix in boxplot (since boolean boxplots don't really make much sense), but we're gradually moving towards a consistent internal float representation of coordinate data that's used in all functions, so I do expect that this will start "working" at some point in the future.

**Closed by mwaskom** 2022-02-10 12:34 UTC

**Comment by emskiphoto** [comment] 2023-03-06 15:24
Boolean boxplots DO make sense.  A dataframe may be filtered several ways and boolean series within the dataframe are an efficient way to keep track of boolean filters/masks.   Being able to visualize a set of variables according to their True/False classification is very useful.
