### ISSUE TITLE
Seaborn's clustermap uses fastcluster, but not in dependencies

### ISSUE THREAD

**Issue by brunobeltran** [mwaskom/seaborn#1370] opened 2018-02-05 20:16 UTC
Title says it all. Ran `sns.clustermap` earlier and got

```python
Traceback (most recent call last):
  File "/home/users/fgrandi/.miniconda3/lib/python3.6/site-packages/seaborn/matrix.py", line 626, in calculated_linkage
    return self._calculate_linkage_fastcluster()
  File "/home/users/fgrandi/.miniconda3/lib/python3.6/site-packages/seaborn/matrix.py", line 607, in _calculate_linkage_fastcluster
    import fastcluster
ModuleNotFoundError: No module named 'fastcluster'
```
Is there a reason for this or should I submit a PR with that module added to setup.py?

**Comment by mwaskom** [comment] 2018-02-05 20:31
Can you show a full example of what you're doing? If fastcluster is not installed it should just fall back to scipy, potentially issuing a warning if you're trying to cluster a particularly large matrix.

**Comment by mwaskom** [comment] 2018-02-19 17:16
Closing for lack of information.

**Closed by mwaskom** 2018-02-19 17:16 UTC

**Comment by mwaskom** [comment] 2018-06-01 18:35
`ModuleNotFoundError` is a subclass of `ImportError` and so should be caught: https://airbrake.io/blog/python/importerror-and-modulenotfounderror

I've just confirmed that on my system I can use clustermap with no problems in a Python 3.6 environment that does not have fastcluster installed (trying to import raises a `ModuleNotFoundError`) so if this problem exists it's not general.

**Comment by cdanielmachado** [comment] 2018-10-01 13:14
I also found this error. Could only fix it by installing the fastcluster package.

**Comment by MollieBakal** [comment] 2019-06-18 14:43
I have the same error, with fastcluster throwing a ModuleNotFoundError and not falling back to scipy. Downloading fastcluster as well.

**Comment by monchin** [comment] 2019-09-18 03:07
If we need `fastcluster` for `clustermap`, should this package be added into `requirements.txt`?

**Comment by johanovic** [comment] 2019-12-19 12:08
Can confirm the issue on Ubuntu 18.04 in a virtualenv.

**Comment by mwaskom** [comment] 2019-12-19 12:27
I suspect that people are getting errors during clustering and seeing the fastcluster exception because it is part of the stack trace (it gets caught and then the code moves on  to use scipy), but it is not the actual cause of their problem. However, nobody has provided sufficient information to provide help beyond speculation.

**Comment by johanovic** [comment] 2019-12-20 08:05
I got this error when running sns.clustermap out of the box. It did *not* result in a graph, just the error. Was in a jupyter notebook. sns.heatmap worked just fine. As far as I can see it does not fall back to scipy.

**Comment by xfooo** [comment] 2020-01-09 01:56
Encountered this error message and at least in my case, the error is trigger when the data matrix has one or more column(s) or row(s) full of zeros. Here's the trace and how to reproduce:

Trace back:
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in calculated_linkage(self)
    625         try:
--> 626             return self._calculate_linkage_fastcluster()
    627         except ImportError:

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in _calculate_linkage_fastcluster(self)
    606     def _calculate_linkage_fastcluster(self):
--> 607         import fastcluster
    608         # Fastcluster has a memory-saving vectorized version, but only

ModuleNotFoundError: No module named 'fastcluster'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-38-c511c9022b7c> in <module>
      1 matrix = np.random.rand(10, 100)
      2 matrix[0, :] = 0
----> 3 sns.clustermap(matrix, metric='cosine', method='single')
      4 plt.show()

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in clustermap(data, pivot_kws, method, metric, z_score, standard_scale, figsize, cbar_kws, row_cluster, col_cluster, row_linkage, col_linkage, row_colors, col_colors, mask, **kwargs)
   1299                         row_cluster=row_cluster, col_cluster=col_cluster,
   1300                         row_linkage=row_linkage, col_linkage=col_linkage,
-> 1301                         **kwargs)

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in plot(self, metric, method, colorbar_kws, row_cluster, col_cluster, row_linkage, col_linkage, **kws)
   1126         colorbar_kws = {} if colorbar_kws is None else colorbar_kws
   1127         self.plot_dendrograms(row_cluster, col_cluster, metric, method,
-> 1128                               row_linkage=row_linkage, col_linkage=col_linkage)
   1129         try:
   1130             xind = self.dendrogram_col.reordered_ind

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in plot_dendrograms(self, row_cluster, col_cluster, metric, method, row_linkage, col_linkage)
   1019             self.dendrogram_row = dendrogram(
   1020                 self.data2d, metric=metric, method=method, label=False, axis=0,
-> 1021                 ax=self.ax_row_dendrogram, rotate=True, linkage=row_linkage)
   1022         else:
   1023             self.ax_row_dendrogram.set_xticks([])

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in dendrogram(data, linkage, axis, label, metric, method, rotate, ax)
    745     plotter = _DendrogramPlotter(data, linkage=linkage, axis=axis,
    746                                  metric=metric, method=method,
--> 747                                  label=label, rotate=rotate)
    748     if ax is None:
    749         ax = plt.gca()

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in __init__(self, data, linkage, metric, method, axis, label, rotate)
    562 
    563         if linkage is None:
--> 564             self.linkage = self.calculated_linkage
    565         else:
    566             self.linkage = linkage

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in calculated_linkage(self)
    626             return self._calculate_linkage_fastcluster()
    627         except ImportError:
--> 628             return self._calculate_linkage_scipy()
    629 
    630     def calculate_dendrogram(self):

~/anaconda3/lib/python3.7/site-packages/seaborn/matrix.py in _calculate_linkage_scipy(self)
    601                         '"pip install fastcluster")')
    602         linkage = hierarchy.linkage(self.array, method=self.method,
--> 603                                     metric=self.metric)
    604         return linkage
    605 

~/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py in linkage(y, method, metric, optimal_ordering)
   1107 
   1108     if not np.all(np.isfinite(y)):
-> 1109         raise ValueError("The condensed distance matrix must contain only "
   1110                          "finite values.")
   1111 

ValueError: The condensed distance matrix must contain only finite values.`

To reproduce, simply:
`import numpy as py
import seaborn as np
matrix = np.random.rand(10, 100)
# matrix[0, :] = 0  # unquote this line and it'll throw errors; alternative matrix[:, 0]=0 does the same. 
sns.clustermap(matrix, metric='cosine', method='single')
plt.show()`

**Comment by mwaskom** [comment] 2020-01-09 12:21
Thank you for providing a reproducible example. But the problem here is not the absence of fastcluster. As I said, that is caught and handled, and then you’re getting an exception from inside the scipy clustering code.

**Comment by aydemiro** [comment] 2020-07-29 03:10
I encountered the same error as well. Mine was caused by NaN values in the matrix I was using. Changing that solved the problem. I thought it may help people arriving at this page looking for answers.
