### ISSUE TITLE
Bug in seaborn's PairGrid function when passing an ordered string numeric variable?

### ISSUE THREAD

**Issue by SNRNS** [mwaskom/seaborn#2149] opened 2020-06-26 01:02 UTC
Hi,

I posted the question on [stackoverflow](https://stackoverflow.com/questions/62563504/bug-in-seaborns-pairgrid-function-when-passing-an-ordered-string-numeric-variab).

Is this a bug?

**Comment by mwaskom** [comment] 2020-06-26 01:20
On master, the second plot (string-typed numbers) looks like this. I think this is what you expect.

![image](https://user-images.githubusercontent.com/315810/85810309-a307e580-b728-11ea-95d5-c82653cf1d2d.png)

The behavior that you're seeing is half a bug and half an intentional but controversial API decision that has since been changed (obviating the bug).

To be clear, the issue is in `stripplot` and has nothing to do with `PairGrid`.

Up to v0.10.1, object-typed Series that could be coerced to a float dtype were considered "numeric" and treated as such.  Categorical plots default to sorting the categorical variable if it's numeric. So sorting makes sense (in terms of what is intended to happen), but the bug in that example is that the string-encoded data is getting lexicographically sorted. The correct behavior would have been to sort the numeric representation.

Either way, the API has [changed in the development version](https://github.com/mwaskom/seaborn/pull/2084), for v0.110.0. Now the type inference code introspects the types of the individual objects in an object-typed Series, so numbers encoded as strings are considered categorical, and stripplot uses the default ordering for categorical variables, which is the order they appear in the Series.

In any case, you can always specify the order explicitly with the `order` parameter.

I'm closing as this behavior no longer exists in the development version of seaborn.

**Closed by mwaskom** 2020-06-26 01:20 UTC

**Comment by mwaskom** [comment] 2020-06-26 11:23
Since you dual posted in stackoverflow and github please propagate the answer back to stackoverflow so others who come across it can see it.

**Comment by SNRNS** [comment] 2020-06-26 15:04
Yes, definitely, I was thinking on doing that!

By the way, `seaborn` is such an amazing package I use very often.

Congrats in such great and neat work!!!
