### ISSUE TITLE
PairGrid with hue according to continuous variable

### ISSUE THREAD

**Issue by domgarvir** [mwaskom/seaborn#1406] opened 2018-04-13 12:17 UTC
So, I've been able to find how it was doable before (https://github.com/mwaskom/seaborn/issues/313), but it seems it is no longer possible ...

What is the way to work around this at the moment (if there is one)?
I have not been able to find a solution to this .... 

Thanks a lot

**Comment by mwaskom** [comment] 2018-04-13 13:45
Duplicate of #1301

**Closed by mwaskom** 2018-04-13 13:45 UTC
