### ISSUE TITLE
sharex keyword is ignored in displot, FacetGrid with histplot doesn't show legend

### ISSUE THREAD

**Issue by Zendelo** [mwaskom/seaborn#2472] opened 2021-02-05 09:41 UTC
Trying to create a displot with non-shared axis (both y and x) using the following function call:
```
import seaborn as sns
_df = sns.load_dataset("tips")
sns.displot(data=_df, x='tip', col='day', hue='smoker', stat="density", element='step', facet_kws={'sharex': False, 'sharey': False})
```
The result is, X axis are still shared 
![image](https://user-images.githubusercontent.com/13455948/107016192-c2540e80-67f1-11eb-8a7d-ef94e56011d9.png)

I've tried using FacetGrid with histplot, but then I can't get a legend.
```
g = sns.FacetGrid(_df, col="day", sharex=False, sharey=False)
g.map_dataframe(sns.histplot, x="tip", stat="density", element="step", hue="smoker").add_legend()
```
![image](https://user-images.githubusercontent.com/13455948/107016629-460dfb00-67f2-11eb-9013-e69d13b2184d.png)

matplotlib 3.2.1
seaborn-0.11.0

Also tried upgrading to 
seaborn-0.11.1

same issues

**Comment by mwaskom** [comment] 2021-02-05 13:26
You'll want to add `common_bins=False`; that parameter and `sharex=False` don't programmatically imply each other but you'll need both to get the result that (I think) you want.

**Comment by mwaskom** [comment] 2021-02-05 15:28
@Zendelo closing as I think this is all working as expected (from my end) but ping if that somehow doesn't solve your actual problem

**Closed by mwaskom** 2021-02-05 15:28 UTC
Labels: mod:distributions, question

**Comment by Zendelo** [comment] 2021-02-06 03:54
Thanks for the quick response, adding ` common_bins=False` did solve the issue.
But can you refer to the second method I tried using FacetGrid?
The histograms there were fine, but I couldn't get the legend to show.
Am I missing something there as well, or should it be reported as a bug?

**Comment by mwaskom** [comment] 2021-02-06 15:29
It's not a bug, or at least it's not unexpected on my end. `histplot` doesn't add extra legend artists to the axes so there's nothing for `FacetGrid` to pick up. More context here: https://github.com/mwaskom/seaborn/issues/2231

**Comment by sorenwacker** [comment] 2023-02-14 01:24
Would be a nice feature. Missing it sometimes.

**Comment by mwaskom** [comment] 2023-02-14 01:30
?

**Comment by sorenwacker** [comment] 2023-02-15 18:24
Everyonce in a while I run into this. In general, I would not assume that the distributions of different groups have the same scale. Creating facet plots with displot, at the moment is only useful if that is the case. If that is not the case, instead of adding simply `sharex=False`, which would be consistent with e.g. relplot or catplot, I basically have to go back to matplotlib and create the plot manually. Maybe there is already a better way to do that in seaborn that I don't know? Maybe this should not be reported as 'bug' but more accuarately as a feature request.

**Comment by mwaskom** [comment] 2023-02-15 20:36
I do not understand. Did you read this thread? It provides the solution to your problem.

**Comment by sorenwacker** [comment] 2023-02-15 20:44
> You'll want to add common_bins=False; that parameter and sharex=False don't programmatically imply each other but you'll need both to get the result that (I think) you want.

Got it. I missunderstood you.

**Comment by sencer** [comment] 2023-12-15 16:52
I don't think common_bins exactly solves the problem - or it creates another one: Different histograms on the same plot also ends up having different bins. That is: when you have both `col` and `hue`; and you want different subplots to have different ranges; but within a subplot you want shared bins it doesn't work.

**Comment by zaccharieramzi** [comment] 2024-08-30 15:01
I am facing the same issue as @sencer , is there a remediation?
