### ISSUE TITLE
'LinearSegmentedColormap' object is not iterable for stripplot with palette argument when as_cmap=True

### ISSUE THREAD

**Issue by adamcwatts** [mwaskom/seaborn#3422] opened 2023-07-20 18:03 UTC
I came across this issue when doing a stripplot and setting the `palette` option. The issue arises when using a palette with `as_cmap=True`. When you set it,  `as_cmap=False`, the plot properly works. 

I believe this is a bug, if this is the normal behavior, the error it produces doesn't explain the problem.

```
import seaborn as sns
import pandas as pd
import numpy as np
from scipy.stats import norm
from random import choices

N = 100

fruits = ['Apples', 'Oranges', 'Pears']
farms = ['Farm A', 'Farm B']

VarY  = np.arange(1, N + 1) + norm.rvs(size=N)

VarX = choices(fruits, k=N)
VarHue = choices(farms, k=N)

myDict = {'Fruits': VarX, 'Farms':VarHue, 'VarY':VarY}


df = pd.DataFrame.from_dict(myDict)

PAL = sns.blend_palette(['#9EDDE6', '#0D2C31'], as_cmap=True)

sns.stripplot(data=df, x="Fruits", y="VarY", hue="Farms", palette=PAL,  # Issue with palette when as_cmap=True
              dodge=True,   s=5, jitter=0.3, linewidth=0.1, marker='D')
```

**Comment by mwaskom** [comment] 2023-07-20 22:44
Duplicate of #2694

**Closed by mwaskom** 2023-07-20 22:44 UTC
