### ISSUE TITLE
`FacetGrid` data no longer contains all columns from original input dataframe

### ISSUE THREAD

**Issue by SWu** [mwaskom/seaborn#2622] opened 2021-07-26 19:11 UTC
After recently upgrading from seaborn 0.9.1 to 0.11.1, I noticed that after using `relplot` on a dataframe, the returned `FacetGrid` object only contains a transformed dataframe which makes `FacetGrid.facet_data()` return a lot less useful for additional plot manipulation using information from the original dataframe. A minimal repro:

```
>>> import seaborn as sns
>>> import pandas as pd
>>> import numpy as np
>>> data = pd.DataFrame(np.random.randint(0,3,size=(15, 7)), columns=list('ABCDEFG'))
>>> data.columns
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')
>>> g = sns.relplot(x='A', y='B', row='C', col='D', hue='E', data=data)
>>> g.data.columns
Index(['x', 'y', 'hue', 'size', 'style', 'units', 'C', 'D'], dtype='object')
>>> for (i, j, k), data_ijk in g.facet_data():
...     data_ijk.F  # this no longer works
```

Previously, `g.data` would contain all of the original dataframe columns, and I was relying on that so that I could use `g.facet_data()` to augment plots with additional information from the original dataframe.

Is there a way to get back that functionality?

**Comment by mwaskom** [comment] 2021-07-26 22:25
This is a bug that was partially fixed in https://github.com/mwaskom/seaborn/pull/2581. I say partially because the current solution preserves only the columns that are actually used in the relplot (but with their original names, if present).  The problem was caused (and the solution made more complicated) when relplot was enhanced to plot wide-form data or vectors that are not in the input dataframe. There may be a better solution for the normal case of long input data with named vectors.

In the meantime, I think if you just reassign your input dataframe to the `g.data` attribute, the rest of your operations should work as expected.

**Comment by SWu** [comment] 2021-07-26 23:50
Thanks. I did figure out that workaround to reassign back to `g.data`, which I can use for now.

I'm not sure of all the implications of the changes to support wide-form data, but I wonder if there's a better fix here to store separate attributes for the manipulated dataframes used internally by plotting functionality, while exposing the original data in the `.data` FacetGrid attribute.

**Comment by mwaskom** [comment] 2021-07-27 12:39
This for the reproducible report. See https://github.com/mwaskom/seaborn/pull/2623 for a fix. Would be great if you have a chance to test it out with your actual usecase.

**Closed** 2021-08-02 00:02 UTC
Labels: bug
