### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by eginina** [mwaskom/seaborn#1422] opened 2018-05-08 08:42 UTC
I looked at the other similar issues but haven't solved my problem yet. 
Here is the output & Thank you for the help!
##########################
![mypic](https://user-images.githubusercontent.com/37146676/39746975-42c9b06e-52ac-11e8-9607-13132acd7930.png)

**Comment by mwaskom** [comment] 2018-05-08 14:05
This is a duplicate of #1103

**Closed by mwaskom** 2018-05-08 14:05 UTC
