### ISSUE TITLE
Factorplot with col_wrap=1 only prints the first plot

### ISSUE THREAD

**Issue by tlgs** [mwaskom/seaborn#1250] opened 2017-07-28 15:44 UTC
Relevant [StackOverflow question](https://stackoverflow.com/questions/23258353/seaborn-facetgrid-col-wrap-wide-to-long-plotting-issue/45377449#45377449) (which I actually just posted to).

I understand this isn't a showstopper but actually made me research a while before realizing there was also a `row` parameter that was meant to be used. Perhaps a error message could be displayed? 

If you tell me what the intended behavior is I can try and make a pull request fixing it. 😄

**Comment by mwaskom** [comment] 2017-07-28 15:50
Duplicate of #890

**Closed by mwaskom** 2017-07-28 15:50 UTC

**Comment by mwaskom** [comment] 2018-06-13 22:00
Fixed with https://github.com/mwaskom/seaborn/pull/1453
