### ISSUE TITLE
Feature request: Add statistical annotations to barplots

### ISSUE THREAD

**Issue by javadnoorb** [mwaskom/seaborn#1636] opened 2019-01-03 21:16 UTC
It is a common practice in scientific plottings that a barplot (or violinplot/swarmplot) has statistical annotations such as p-values marked with horizontal lines connecting the bars. There is already an implementation of this as a separate project:
https://github.com/webermarcolivier/statannot

but having such a feature incorporated into seaborn would be very handy. Is there any interest to pursue this? -Thanks

**Comment by mmagnuski** [comment] 2019-01-04 16:50
This is a duplicate of #828. You can see there that this feature won't be implemented in seaborn. The maintainer of the package, @mwaskom has good reasons for not including such features: seaborn is a visualisation and not a statistical package and adding this would be similar to opening a pandora box of other issues (depending on the tests and corrections you use and personal preferences you might want different annotations and probably even a different API).
BTW thanks for the project link. :)

**Comment by mwaskom** [comment] 2019-01-04 19:41
Thanks @javadnoorb  — this has come up a few times and if you dig through the issues you can find longer explanations (which is why, by the 800th issue, I had started giving a shorter, final answer).

There are many implementational/API concerns that make this not at all trivial and something that's probably best handled externally, like in the linked package. But at root, I have what you might call moral objections to these kind of statistical annotations, so I'm not going to stick firm to my decision not to support them.

**Closed by mwaskom** 2019-01-04 19:41 UTC

**Comment by javadnoorb** [comment] 2019-01-07 16:34
Thanks @mmagnuski and @mwaskom. This makes total sense. Apologies for posting a duplicate.
