### ISSUE TITLE
Some screwy stripplot behavior after matplotlib 1.5.0 upgrade

### ISSUE THREAD

**Issue by chubukov** [mwaskom/seaborn#753] opened 2015-11-06 08:54 UTC
Seems like passing both `x` and `hue` to stripplot causes something strange to happen with the color cycling. Only observed after recent matplotlib upgrade. Tried both stable 0.6 and 0.7.0.dev0 version of seaborn.

```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns

df=pd.DataFrame(columns=['x','t','y'])
df['t']=np.repeat([1,2,3,4],9)
df['x']=np.tile(['a','b','c'],12)
df['y']=np.random.normal(size=(36,1))

sns.stripplot(data=df,x='t',hue='x',y='y')
```
produces
![image](https://cloud.githubusercontent.com/assets/13080968/10992984/27333616-8420-11e5-96a2-b04f6a087591.png)

Edit after further playing around: this only seems to happen when there are exactly three points. Changing the above to 

```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns

df=pd.DataFrame(columns=['x','t','y'])
df['t']=np.repeat([1,2,3,4],12)
df['x']=np.tile(['a','b','c'],16)
df['y']=np.random.normal(size=(48,1))

sns.stripplot(data=df,x='t',hue='x',y='y')
```
works fine
![image](https://cloud.githubusercontent.com/assets/13080968/10993356/0c268578-8423-11e5-90c6-c7c2790ce256.png)

**Comment by mwaskom** [comment] 2015-11-06 15:15
I think I have seen this kind of thing before, where sometimes `ax.scatter` thinks that what you have passed to `c` are scalar values to be colormapped rather than RGB codes for each point. Thanks for reporting. I'm not 100% certain what the way to avoid it is, though. I feel like Pandas has dealt with this before, maybe @TomAugspurger has some insight or can point me to a Pandas PR?

**Comment by mwaskom** [comment] 2015-11-06 15:16
If it really did just break in with 1.5, it's also possibly a matplotlib bug.

**Comment by TomAugspurger** [comment] 2015-11-06 15:26
I don't recall seeing anything exactly like this before, but I may be misremembering. `c` being mistaken as scalar values is a good guess.

**Comment by mwaskom** [comment] 2015-11-06 15:28
Here's at least one relevant pandas issue: https://github.com/pydata/pandas/issues/9724

**Comment by TomAugspurger** [comment] 2015-11-06 15:31
Hah, ok I have a bad memory. That one's from March it doesn't seem like matplotlib 1.5 is the culprit.

**Comment by mwaskom** [comment] 2015-11-06 15:38
Here is the relevant matplotlib code: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L3839

I think this might be a matplotlib bug:

```

        # After this block, c_array will be None unless
        # c is an array for mapping.  The potential ambiguity
        # with a sequence of 3 or 4 numbers is resolved in
        # favor of mapping, not rgb or rgba.
        try:
            c_array = np.asanyarray(c, dtype=float)
            if c_array.size == x.size:
                c = np.ma.ravel(c_array)
            else:
                # Wrong size; it must not be intended for mapping.
                c_array = None
        except ValueError:
            # Failed to make a floating-point array; c must be color specs.
            c_array = None

        if c_array is None:
            colors = c     # must be acceptable as PathCollection facecolors
        else:
            colors = None  # use cmap, norm after collection is created
```

The problem is that `array.size` gives the number of elements in an array, not the length of the first dimension. `x` is always a vector of size `n`, but if `c` is a list of RGB values (which it generally will be inside `stripplot` if `seaborn.color_palette` is used) then its size will be `n * 3` and matplotlib will think you have passed scalar values, not color codes.

It's still early here, so can someone check my logic before I kick this up the chain to matplotlib? In the meantime, a easy workaround in seaborn would be to use the `as_hex` method of the color palette before passing colors to `ax.scatter`, which should avoid this behavior.

**Comment by TomAugspurger** [comment] 2015-11-06 15:59
Haven't looked closely, but that sounds about right.

**Comment by chubukov** [comment] 2015-11-17 01:17
I think that this is probably correct, and I just wanted to note that the workaround @mwaskom suggested does not seem to work. Passing `palette=sns.color_palette('deep',3).as_hex()` in the call to stripplot results in the same behavior. It looks like in `_CategoricalPlotter.establish_colors()` the colors get converted right back to rgb for some further processing. https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L294

**Comment by mwaskom** [comment] 2015-11-17 01:20
Sorry, I meant that is a workaround that needs to be implemented *in seaborn*.

**Comment by mwaskom** [comment] 2015-11-17 01:57
BTW I can confirm that the behavior described in the original issue posting does not occur on matplotlib 1.4.

**Closed** 2015-12-12 18:36 UTC
