### ISSUE TITLE
avoiding lineplot filling in missing values

### ISSUE THREAD

**Issue by itarec1988** [mwaskom/seaborn#2120] opened 2020-06-03 10:32 UTC
Hello,

I am using sns.lineplot for time-series data. I realize that lineplot automatically fills in missing data and I want to avoid this. Is there a way of avoiding this in sns.lineplot. 

I attach some screenshots that briefly explain my issue.

Thanks,

![Screen Shot 2020-06-03 at 12 29 40 PM](https://user-images.githubusercontent.com/28057910/83626669-12f5d680-a596-11ea-897b-3d2b8b22df69.png)

![Screen Shot 2020-06-03 at 12 30 30 PM](https://user-images.githubusercontent.com/28057910/83626704-2012c580-a596-11ea-9e87-dcb01eb83519.png)

**Comment by mwaskom** [comment] 2020-06-03 11:20
This is a duplicate of https://github.com/mwaskom/seaborn/issues/1552 so I am going to close. I agree that it would be good to have a clear way to get what you want. Because your plot is simple, the easiest thing for you to do is probably to use matploltib directly. In more complicated situations where you are taking advantages of seaborn features, you could define a `units` variable to plot each segment separately.

**Closed by mwaskom** 2020-06-03 11:20 UTC
