### ISSUE TITLE
Regplot does automatically update axes limits of the wrong plot when no color is provided

### ISSUE THREAD

**Issue by AKuederle** [mwaskom/seaborn#1609] opened 2018-11-14 12:07 UTC
Ok this is an odd one:

If you have a matplotlib figure with multiple subplots and try to plot a regplot inside one of the the axes, regplot will update the axes limits of the last axes of the subplot.

The cause for this is pretty simple. in [this line](https://github.com/mwaskom/seaborn/blob/29d1075cd56878ad2ba71f537df2cd73170ad847/seaborn/regression.py#L327) the regplot function calls `plt.plot` instead of `ax.plot`. Hence the currently active axes (meaning the last subplot) is targeted by this line, automatically updating its limits.

**Comment by AKuederle** [comment] 2018-11-14 12:31
After some testing: This will change the way the color cycle will be exhausted. Before, the global colorcycle was queried. Now only the colorcycle of the current axes is queried. I am not sure if anything else depends on this functionality

**Comment by AKuederle** [comment] 2018-11-14 12:46
Ok, I find a solution, which does not require to plot anything, which seems to preserve the original functionality, while still solving this bug

**Comment by mwaskom** [comment] 2018-11-19 15:42
Thanks for raising; this is a duplicate of #1568

**Closed by mwaskom** 2018-11-19 15:42 UTC
