### ISSUE TITLE
Annotation in heatmaps are not showing up

### ISSUE THREAD

**Issue by gkunter** [mwaskom/seaborn#830] opened 2016-01-21 18:14 UTC
In my installation (seaborn 0.6.0, matplotlib 1.5.1 with Qt2 back end under Linux Mint, Python 3.5), the annotation feature of heatmaps doesn't work. When I run the "Annotated heatmap" example from the [project website](https://stanford.edu/~mwaskom/software/seaborn/examples/heatmap_annotation.html), only the cell in the lower left corner has an annotation (in a wrong color):

![image](https://cloud.githubusercontent.com/assets/12086562/12489905/04f63956-c073-11e5-82e6-4cd10927a5c6.png)

The same issue also occurs with other data sets:
```python
sns.heatmap(
    pd.DataFrame({
        'wanna': {'ACAD': 53, 'MAG': 490, 'NEWS': 249}, 
        'gonna': {'ACAD': 202, 'MAG': 1974, 'NEWS': 1207}}), 
    annot=True)
```

![image](https://cloud.githubusercontent.com/assets/12086562/12489884/e62750fa-c072-11e5-9d8c-b6c6649427e2.png)

**Comment by mwaskom** [comment] 2016-01-21 18:51
Duplicate of #619

**Closed by mwaskom** 2016-01-21 18:51 UTC
