### ISSUE TITLE
raise LinAlgError("singular matrix") numpy.linalg.LinAlgError: singular matrix

### ISSUE THREAD

**Issue by Rakiba291** [mwaskom/seaborn#2264] opened 2020-09-10 06:23 UTC
Hi there,
 I am new to python and machine learning. I am facing the problem for the following code. Can anybody suggest me what should be done to remove the error. Thanks in advance .
Seaborn version:0.9.0
Python: 3.6.0
Code:
-------------------------------------------
sns.distplot(d_p,color="skyblue", label="Distribution of neighbour image distances in route produced with GD")
    # plt.savefig('dis_p.png')#distribution of distance of neighbour images(real frames) in route
    sns.distplot(d_m,color="red", label="Distribution of neighbour image distances in route manually sellected")
    plt.legend()
    plt.savefig('disroute.png')#distribution of distance of neighbour images(real frames) in manually selected route
    plt.clf()
    sns.distplot(d_p_latent,color="skyblue", label="Distribution of neighbour pair distances in path produced with GD")
    plt.savefig('distance_p_latent.png')#
    plt.clf()
    sns.distplot(d_m_latent,color="red", label="Distribution of neighbour pair distances in path w.r.t. manually selected route")
    plt.legend(loc=2, fontsize = 'x-small')
    plt.savefig('dis_m_lnt.png')
------------------------------------------------
Error:
#########
ile "C:\VAE_learning-a-representation-for-navigation-master\navigation_function.py", line 546, in evaluate
    sns.distplot(d_p,color="skyblue", label="Distribution of neighbour image distances in route produced with GD")
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\seaborn\distributions.py", line 231, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\seaborn\distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\seaborn\distributions.py", line 294, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\seaborn\distributions.py", line 366, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\scipy\stats\kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\scipy\stats\kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\scipy\stats\kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "C:\Users\Anaconda3\envs\reti\lib\site-packages\scipy\linalg\basic.py", line 975, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.LinAlgError: singular matrix

**Comment by mwaskom** [comment] 2020-09-10 15:21
This is a duplicate of https://github.com/mwaskom/seaborn/issues/1502, and several other issues.

When you get an error message, it can be helpful to try searching some of the specific text from it before opening a new issue, as it will often help you get a faster answer than if you have to wait for someone to respond.

**Closed by mwaskom** 2020-09-10 15:21 UTC
