### ISSUE TITLE
repeat legends with sns.histplot

### ISSUE THREAD

**Issue by johnjim0816** [mwaskom/seaborn#3129] opened 2022-11-08 08:43 UTC
```Python
import seaborn as sns;sns.set()
import matplotlib.pyplot as plt
penguins = sns.load_dataset("penguins")
# sns.displot(data=penguins, x="flipper_length_mm",label='policy_0',kind="hist")
sns.histplot(data=penguins, x="flipper_length_mm",label='policy_1')
plt.legend()
plt.savefig("test.png")
```
By running belowing codes, I got a figure like:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/39483938/200516845-de61003e-becf-4459-8872-90a675ffb631.png">

It seems to repeat the legends, could you fixed it soon? It will be pretty nice of you!

**Comment by johnjim0816** [comment] 2022-11-08 08:45
I donot use `sns.displot`, because I want to use `fig,ax=plt.subplots`, and ` sns.displot` does not accept `ax` as input parameters

**Comment by mwaskom** [comment] 2022-11-08 11:35
Duplicate of #3115

**Closed by mwaskom** 2022-11-08 11:35 UTC
