### ISSUE TITLE
Marker 'o' irregular shape

### ISSUE THREAD

**Issue by tritemio** [mwaskom/seaborn#557] opened 2015-05-12 17:56 UTC
Hi,

After importing seaborn using the `'o'` marker resutls in non-round marker shape. For example:

    plt.plot([1,2,3,4], [3,1,2,4], 'o')

Gives this in pure matplotlib:

![image](https://cloud.githubusercontent.com/assets/4156237/7594442/78914c8a-f895-11e4-92c0-1f4ae3751425.png)

And this after importing seaborn:
![image](https://cloud.githubusercontent.com/assets/4156237/7594450/7faa36c6-f895-11e4-9a4c-c4415db9236a.png)

**Comment by mwaskom** [comment] 2015-05-12 18:30
I think this is caused by seaborn slightly increasing the default `lines.markersize` param. You can reproduce it in pure matplotlib with

```python
plt.plot([1,2,3,4], [3,1,2,4], 'o', markersize=7)
```

The root cause here is really the IPython notebook decreasing the DPI of inline plots, though.

**Comment by tritemio** [comment] 2015-05-12 19:04
Thanks, I'll report to the matplotlib and ipython folks then. This is annoying because it is the default style of seaborn in a notebook. I end up using `'h'` and `H` most of the time for this reason.

**Comment by mwaskom** [comment] 2015-05-12 19:06
I agree it's annoying -- I typically use `plt.scatter` to draw these kind of plots because the circle marker used by that function doesn't suffer from the same issue. You could also just pass `ms=6` to `plt.plot` I guess.

**Comment by mwaskom** [comment] 2015-05-12 19:07
But anyway the broader point is that if you actually save the figure I think the markers will look normal.

**Comment by tritemio** [comment] 2015-05-12 19:08
But last time I tried scatter does not use seaborn palette, right?

**Comment by mwaskom** [comment] 2015-05-12 19:10
Correct, although a [recent PR](https://github.com/mwaskom/seaborn/pull/554) makes that work somewhat better.

**Comment by tritemio** [comment] 2015-05-12 19:13
Unfortunately, the irregular shape appears also in the saved png.

**Comment by mwaskom** [comment] 2015-05-12 19:15
Hm you're right, I guess I was thinking of pdf output, which doesn't have this issue. But pdfs cannot be used everywhere.

Anyway, maybe worth kicking up the chain to the matplotlib folks. It certainly is an annoyance.

**Comment by mwaskom** [comment] 2015-05-13 23:39
Closing as it looks like this was fixed upstream. Thanks for bringing it up.

**Closed** 2015-05-15 04:37 UTC
