### ISSUE TITLE
`g.map_dataframe` seems to remove axes labels set by displot

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2560] opened 2021-04-20 19:48 UTC
Tested both with 0.11.1 and recent dev version:
```python
import matplotlib.pyplot as plt
import seaborn as sns

def show_counts(color, data):
    ax = plt.gca()
    ax.text(0.5, 0.95, f'Count: {len(data)}', ha='center', color=color, transform=ax.transAxes)

penguins = sns.load_dataset("penguins")
g = sns.displot(data=penguins, x="flipper_length_mm", y="bill_length_mm", col="species", height=3)
g.map_dataframe(show_counts)
plt.tight_layout()
```
Without calling `map_dataframe` the outer x and y labels are set to the x and y column names used in `displot`. After calling `map_dataframe` the labels are empty.

(Apart from that, the function `g.set_axis_labels()` doesn't seem to be documented, although it appears in the `displot` and `FacetGrid` examples.)

**Comment by mwaskom** [comment] 2021-04-20 20:29
Duplicate of #2456 I believe.

Not all `FacetGrid` methods appear in the main API index, but they are documented at the bottom of [this page](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html).

**Closed** 2021-04-22 00:46 UTC

**Comment by jhncls** [comment] 2021-04-22 04:50
Indeed, it is the same surprising behavior.

Would it be possible that functions such as `g.set_axis_labels()` get a permalink at that page?
