### ISSUE TITLE
histplot - manually scaling desired colors to account for default saturation when using hue and palette

### ISSUE THREAD

**Issue by pmodv** [mwaskom/seaborn#2471] opened 2021-02-04 21:52 UTC
For histplot, you are unable to directly control saturation, and so you can very easily, as I did, end up with colors not matching between the legend and the actual plot, itself.  

To solve this, I used the following manual solution:  I scaled each of the (R,G,B) tuples within my palette to match the default 0.75 saturation.  

This scaling, done manually within the list colors tuples in the palette list, solved my color-coordination issue between my legend and my plot.

**Comment by mwaskom** [comment] 2021-02-04 22:42
Can you please provide a [reproducible example](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) that illustrates the problem you are talking about? It's very hard to understand an issue about pictures that have been produced by code from a verbal description.

**Comment by pmodv** [comment] 2021-02-04 22:56
```
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt



#df_vac = pd.read_csv('covid19_vaccinations_in_the_united_states.csv',delimiter=',',skiprows=2)

df_vac = pd.DataFrame({'State/Territory/Federal Entity':['NY','CT','RI','MA','NH','TX','VA','CA'], 'Distributed per 100K':[12,9,4,7,13,21,2,25]})


top5states = df_vac.sort_values(by='Distributed per 100K',ascending=False).iloc[0:5,0]

# default for all regions before checking in top 5
df_vac['top_five'] = 'no'

df_vac.loc[df_vac['State/Territory/Federal Entity'].isin(top5states),'top_five']='yes'

g = sns.histplot(x="State/Territory/Federal Entity",y='Distributed per 100K',data = df_vac,hue='top_five',palette=[(0.51,0,0),(0,0,0.51)])



for (top_five, tickcolor) in zip(df_vac['top_five'], g.xaxis.get_ticklabels()):
    tickcolor.set_color((0.51,0,0) if top_five == 'yes' else (0,0,0.51))

plt.setp(g.get_xticklabels(),rotation=90)


plt.show()


```

**Comment by mwaskom** [comment] 2021-02-04 23:03
I don't have the `covid19_vaccinations_in_the_united_states.csv` file; so I [cannot run your script](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) to see an image that would help me understand you issue.

**Comment by pmodv** [comment] 2021-02-04 23:07
I made a mock table in the code.  Just C&P.

**Comment by mwaskom** [comment] 2021-02-04 23:10
ok, here is the image i see

![image](https://user-images.githubusercontent.com/315810/106966870-21dbec80-6714-11eb-80c6-929abb27679d.png)

now, please, as requested in the [bug report guidelines]()https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) that I've linked to, provide "a clear explanation of why you think something is wrong".

**Comment by pmodv** [comment] 2021-02-04 23:18
The issue is the following:  my original values were (1,0,0) for red and (0,0,1) for blue, in the following line:
`
g = sns.histplot(x="State/Territory/Federal Entity",y='Distributed per 100K',data = df_vac,hue='top_five',palette=[(1,0,0),(0,0,1)])`
Using these tuples resulted in color mis-match between the legend and the plot.  Only after manually scaling the colors, did I get a match, using the following code:

`g = sns.histplot(x="State/Territory/Federal Entity",y='Distributed per 100K',data = df_vac,hue='top_five',palette=[(0.51,0,0),(0,0,.51)])`

**Comment by mwaskom** [comment] 2021-02-04 23:38
I see.

A bivariate histogram is a [heatmap](http://seaborn.pydata.org/tutorial/distributions.html#visualizing-bivariate-distributions). The `palette` parameter does not set colors directly, but rather sets the seed color for a colormap gradient  that has fixed changes in luminance and saturation to represent a quantity.

While you are only sharing a toy example, I am not sure that a bivariate histogram is the best way to represent what you are trying to show if you have only a single observation for each of your `x` values. Wouldn't it be more conventional to show, e.g. a scatter or bar plot?

In any case, I am going to close the issue, because this isn't a bug in seaborn.

**Closed by mwaskom** 2021-02-04 23:38 UTC

**Comment by pmodv** [comment] 2021-02-04 23:40
The barplot had the necessary argument for saturation, but in my real data, it was a very crowded x-axis, and I preferred the much less busy look of the histogram (especially when presenting before an audience).

**Comment by mwaskom** [comment] 2021-02-05 01:19
Just bear in mind that the histogram view is going to throw away a lot of information, and arguably actively mislead ... i.e. your plot makes it look like NY and CT have the same vaccination rate, but true value for NY is 33% higher, and you're losing a lot of precision because all you can say for each datapoint is that its value is somewhere within each bin range. Worth thinking about ...
