### ISSUE TITLE
Histogram gaps

### ISSUE THREAD

**Issue by Kornel** [mwaskom/seaborn#1021] opened 2016-09-25 19:46 UTC
I have generated a million binomial numbers using `scipy.stats.binom.rvs(n = 100, p = 0.5, size = 1000000)` , and certainly did not expected a histogram to have 'gaps':

<img width="524" alt="histogram" src="https://cloud.githubusercontent.com/assets/628457/18817744/7a9f35be-8368-11e6-96ea-6035a6e3252e.png">

The funny thing is, that does not happen always. As I don't have the seed I generated these values with, I've attached the particular data causing this issue here: [observations.txt.gz](https://github.com/mwaskom/seaborn/files/491852/observations.txt.gz)

```
import seaborn as sb
import pandas as pd

my_data = pd.read_csv('/tmp/observations.txt.gz')
sb.distplot(my_data, kde = False)
```

The versions I'm using are:

```
>>> import seaborn as sb
>>> sb.__version__
'0.7.1'
>>> import matplotlib as mpl
>>> mpl.__version__
'1.5.1'
```

The histogram is correct in a sense that all bins have their 'mass', however visually (without ticks for each value) it looks a bit off / misleading. 

You can verify all values are present using e.g. `pd.Series(my_data).value_counts()`. I've noticed these gaps do not depend on the size of the plot.

**Comment by mwaskom** [comment] 2016-09-25 22:43
This is a duplicate of https://github.com/mwaskom/seaborn/issues/327. The answer is essentially that if you want to make a histogram for a discrete dataset you'll have to supply sensible integer bins yourself.

**Closed by mwaskom** 2016-09-25 22:43 UTC

**Comment by Kornel** [comment] 2016-09-26 03:55
Makes sense, thanks.
