### ISSUE TITLE
Force color mapping of hue to be qualitative instead of sequential for numeric data

### ISSUE THREAD

**Issue by Zythyr** [mwaskom/seaborn#1982] opened 2020-03-06 23:58 UTC
How can I force color mapping of hue to be qualitative instead of sequential when the data is numeric? 

Below is example of what I am trying to graph. I want the `Stage `data to be plotted with the `hue`. However, the seaborn interprets the Stage data as numeric thus resulting in sequential color mapping. I want the colors to be mapped to qualitative.

```

import matplotlib as mpl 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib widget

# https://elitedatascience.com/wp-content/uploads/2017/04/Pokemon.csv
# https://elitedatascience.com/python-seaborn-tutorial 
df = pd.read_csv(u'Pokemon.csv')

# Drop any pokemon without type 2
df.dropna(axis='rows', subset=['Type 2'], how='any', inplace=True)

# Drop few type 2 for example because when using style='Type 2', there aren't enough markers 
df = df.loc[ ( (df['Type 2'] != 'Ice') &  (df['Type 2'] != 'Water') &  (df['Type 2'] != 'Rock') )]

df.head()

sns.relplot(x='HP', y='Attack', hue='Stage', style='Type 2', legend='full', data=df)

```

![alt text](https://i.imgur.com/59IHtil.png)

If I try to convert the Stage data to string before plotting, I get an error:

```
df["Stage"] = df["Stage"].astype(str)
sns.relplot(x='HP', y='Attack', hue='Stage', style='Type 2', legend='full', data=df)

```
Error I get is: `AttributeError: 'str' object has no attribute 'view'`

However, if I append the Stage after converting to string with another string, I have no issues: 
`
```
df["Stage"] = df["Stage"].astype(str)
df["Stage"] = df["Stage"] + ' | '
```
![alt text](https://imgur.com/vExOyiz.png)

Related topics: 
https://stackoverflow.com/questions/52884736/why-is-seaborn-creating-an-extra-category-in-my-data 
https://stackoverflow.com/questions/51525284/the-hue-parameter-in-seaborn-relplot-skips-an-integer-when-given-numerical-d

**Comment by mwaskom** [comment] 2020-03-07 00:21
Duplicate of #1515

**Closed by mwaskom** 2020-03-07 00:21 UTC

**Comment by Zythyr** [comment] 2020-03-07 05:20
@mwaskom 

1) Thanks for pointing out the duplicate. I updated to v0.10.0 and I don't get error if I convert my pandas series to string. 

2) However, the problem still remains. How can I force seaborn to use qualitative color map instead of sequential? In a previous comment (https://github.com/mwaskom/seaborn/issues/1515#issuecomment-408436200), you said to provide explicit colors values to the palette. Is this the only work around? 

Are there any future plans for seaborn to allow users to disable defaulting to sequential color map if hue variables are numeric? For example a feature something like this: `sns.set(hue_force_numeric_to_categorical=True)`

**Comment by mwaskom** [comment] 2020-03-07 13:40
I’d suggest reading the release notes for the version you updated to. I put a lot of time into writing them so that people can understand what changes have been made.

**Comment by Zythyr** [comment] 2020-03-08 20:33
@mwaskom Thank you for pointing this out. I didn't know this feature was implemented. Thank you very much. 

For those looking for a solution to the issue I posted, below is excerpt of the release notes and solution to forcing categorical interpretation of the hue parameter: 

https://seaborn.pydata.org/whatsnew.html#v0-9-1-january-2020 

> It is now possible to force a categorical interpretation of the hue varaible in a relational plot by passing the name of a categorical palette (e.g. "deep", or "Set2"). This complements the (previously supported) option of passig a list/dict of colors.
