### ISSUE TITLE
matrix.py::class ClusterGrid(Grid) [bug]

### ISSUE THREAD

**Issue by oligilo** [mwaskom/seaborn#1550] opened 2018-08-26 18:17 UTC
I think the lines
`774: self._preprocess_colors(data, row_colors, axis=0)`
`776: self._preprocess_colors(data, col_colors, axis=1)`
should be changed to
`774: self._preprocess_colors(self.data, row_colors, axis=0)`
`776: self._preprocess_colors(self.data, col_colors, axis=1)`
Error is raised when either of `row_colors` and `col_colors` is `not None` and `data` is a `numpy.ndarray` object.

**Comment by mwaskom** [comment] 2018-08-26 19:57
Thanks, a reproducible example that is copy-pastable would be most helpful, though.

**Comment by oligilo** [comment] 2018-08-27 00:30
Sorry, I corrected the source on my machine and I'm currently running code in batch mode based on that change, so I won't be able to reproduce the error on my end until later. But I can explain the bug in logic:

The `_preprocess_colors` routine on line 815 which is called on lines 774 and 776 that I mentioned above,
`815: def _preprocess_colors(self, data, colors, axis):`
is assuming `data` is a pandas DataFrame object on the following lines:
`823: colors = colors.loc[data.index]`
`825: colors = colors.loc[data.columns]`
When `data` is not a DataFrame, correcting the lines 774 and 776 as above, and given the construction
`761: self.data = pd.DataFrame(data)`
would account for when `data` is, in turn, a numpy ndarray object.

**Comment by mwaskom** [comment] 2018-08-27 00:47
Yes but saving me time of having to cook an up an example that can reproduce the problem you are seeing will mean I will likely get to fixing it sooner.

**Comment by mwaskom** [comment] 2018-08-27 01:15
And because often verbal descriptions of bugs are inexact.

e.g. you say "Error is raised when either of row_colors and col_colors is not None and data is aa numpy.ndarray object."

But I have no problem doing

```python
x = np.random.randn(10, 15)
c = np.random.rand(10, 3)
sns.clustermap(x, row_colors=c)
```

but some annoyance at having taken the time and not being able to reproduce your issue.

**Comment by oligilo** [comment] 2018-08-27 02:12
You're right; I should have said (that particular) error is raised when either of row_colors and col_colors is an instance of pandas DataFrame or Series. Here is an example:

```
import numpy as np
import matplotlib as mpl
mpl.use('Agg')
import seaborn as sns
import pandas as pd

sz = 10
sz2 = sz // 2
cmap = "RdYlBu_r"

lbl = [0 if (i < sz2) else 1 for i in range(sz)]

network_pal = sns.color_palette(cmap, max(lbl)+1)
network_lut = dict(zip(map(str,sorted(set(lbl))), network_pal))
network_colors = pd.Series(map(str,lbl)).map(network_lut)

dst = np.random.rand(sz,sz)

sns.clustermap(dst, row_colors=network_colors, col_colors=network_colors)
```

**Comment by mwaskom** [comment] 2018-08-27 14:08
Right, so I wouldn't call this a bug. Docs for clustermap say:

> {row,col}_colors : list-like or pandas DataFrame/Series, optional
>> List of colors to label for either the rows or columns. Useful to evaluate whether samples within a group are clustered together. Can use nested lists or DataFrame for multiple color levels of labeling. If given as a DataFrame or Series, labels for the colors are extracted from the DataFrames column names or from the name of the Series. **DataFrame/Series colors are also matched to the data by their index, ensuring colors are drawn in the correct order.**

If the data doesn't have an index/columns, the color annotations can't be matched to it, and naively matching against the numeric index assigned to an array-typed data matrix won't always work.

So your proposed change can't be implemented. To th extent anything needs to change, the function should just raise earlier when the color annotations are pandas objects but the data matrix isn't with a more informative message.

**Closed** 2020-10-29 12:12 UTC
Labels: annoyance, mod:matrix
