### ISSUE TITLE
violinplot: edges of plot using wrong colors

### ISSUE THREAD

**Issue by jbradt** [mwaskom/seaborn#564] opened 2015-05-15 15:42 UTC
With Matplotlib 1.4.3 and Seaborn 0.5.1, the edges of the distributions produced by `violinplot` seem to be using the standard plotting color cycle. 

I tried to reproduce one of the sample plots from [the documentation](http://stanford.edu/~mwaskom/software/seaborn/tutorial/plotting_distributions.html#comparing-distributions-boxplot-and-violinplot) just to check, and it looked like this:

![bad_colors](https://cloud.githubusercontent.com/assets/4149299/7656087/3b57b8c8-faf6-11e4-8937-9151d80abdfa.png)

I used this code (copied from the docs) to produce that plot:
```python
sns.set_palette("deep", desat=.6)
sns.set_context(rc={"figure.figsize": (8, 4)})
np.random.seed(9221999)

y = np.random.randn(200)
g = np.random.choice(list("abcdef"), 200)
for i, l in enumerate("abcdef"):
    y[g == l] += i // 2
df = pd.DataFrame(dict(score=y, group=g))

sns.violinplot(df.score, df.group, color="Paired", bw=1);
```

In the documentation, the sides of the distributions are black or maybe gray, but not multicolored.

Am I missing something, or is this a bug? 

Thanks!

**Comment by mwaskom** [comment] 2015-05-15 16:22
That's super weird, but this code has been completely rewritten since 0.5.1 and I don't see this on my system with the new violinplot.

With that said, I also can't reproduce this on tmpnb.org, which is running the same versions as you. So I'm not sure.

The new code uses patch edges for outlines, rather than drawing additional lines on top of the plot, so it's highly unlikely this would reappear. But I don't really understand why you're seeing it, so who knows.

Note that if you want to upgrade to avoid this, there have been [larger changes](http://stanford.edu/~mwaskom/software/seaborn-dev/whatsnew.html#v0-6-0-unreleased) in `violinplot` that you should be aware of.

**Comment by jbradt** [comment] 2015-05-15 17:49
Stranger yet: I just tried it a few times on tmpnb.org too, and sometimes it makes the dark gray lines like it should, and sometimes the lines are colored like above. If you restart the kernel in between runs, it's like it picks randomly what to do...

This was the total content of the notebook I ran on tmpnb.org:
```python
%matplotlib inline
import numpy as np
from numpy.random import randn
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_palette("deep", desat=.6)
sns.set_context(rc={"figure.figsize": (8, 4)})
np.random.seed(9221999)

y = np.random.randn(200)
g = np.random.choice(list("abcdef"), 200)
for i, l in enumerate("abcdef"):
    y[g == l] += i // 2
df = pd.DataFrame(dict(score=y, group=g))

sns.violinplot(df.score, df.group, color="Paired", bw=1);
```

That being said, if this has already been rewritten anyway, I could probably work around it by changing the color palette to one shade of grey temporarily.

Thanks for the response, though!

**Comment by mwaskom** [comment] 2015-05-15 17:53
Ah, you know, that kind of randomness makes me think it could be related https://github.com/mwaskom/seaborn/issues/519, and while the issue there was described as "disappearing edges" that's what it would look like if the edges were actually following the color cycle.

**Comment by jbradt** [comment] 2015-05-15 18:17
Incidentally, I just remembered that something similar also happened to me in `coefplot` the other day, and I was able to reproduce it using the "tips" dataset:

![coefs](https://cloud.githubusercontent.com/assets/4149299/7658797/36c83b9c-fb0b-11e4-8b93-e387c6c4ef2d.png)

Produced with:
```python
tips = sns.load_dataset('tips')
sns.coefplot("tip ~ scale(total_bill) + size + time + sex + smoker", tips)
```

I tried both plots in the same notebook several times, but there doesn't seem to be a relation between the two.

**Comment by mwaskom** [comment] 2015-06-29 03:28
Closing as 0.6 is going out (and I suspect this is a matplotlib issue anyway) but open a new issue if you see this behavior again.

**Closed by mwaskom** 2015-06-29 03:28 UTC
