### ISSUE TITLE
kde overlay on histplot uses wrong data when the multiple='stack' option is used

### ISSUE THREAD

**Issue by mathman33** [mwaskom/seaborn#2882] opened 2022-06-28 03:04 UTC
I think the KDE plots for the following lines should be identical.
`sns.histplot(data=d, x='var1', hue='var2', kde=True)`
`sns.histplot(data=d, x='var1', hue='var2', kde=True, multiple='stack')`

When the stack option is used, the KDE treats the stacked height as the data.

**Comment by mwaskom** [comment] 2022-06-28 10:32
Please provide a reproducible example.

**Comment by mathman33** [comment] 2022-06-28 13:56
```
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

a = np.random.normal(0,1,1000)
b = np.random.normal(3,1,1000)
var2 = np.random.choice([0,1], 1000)
var1 = a + var2*b
d = pd.DataFrame({'var1':var1, 'var2':var2})

sns.histplot(data=d, x='var1', hue='var2', kde=True)
plt.show();plt.close()
sns.histplot(data=d, x='var1', hue='var2', kde=True, multiple='stack')
plt.show();plt.close()
```

**Comment by mwaskom** [comment] 2022-06-28 21:14
Thanks, but can you please read the link with what you need to supply when reporting a bug, specifically the part about showing the plot you are looking at and clearly articulating why you think something is wrong? With you example I see

![image](https://user-images.githubusercontent.com/315810/176289059-31e74bfe-91f7-49f5-be39-b003728e5399.png)

Which is what I expect.

The reason there are guidelines for how to report a bug is to prevent back-and-forths that aren't a good use of anyone's time.

**Comment by mathman33** [comment] 2022-06-28 23:01
Apologies for not following the directions.  The blue curve in the second plot is not what I expect - it is showing an estimate of the sum of the two `var2` categories `0` and `1`.  Because the data are the same between the plots, and the only thing that is changing is how they are displayed, I expect the overlaid curves to be identical in the two plots.  Again, sorry if this is not clear.

**Comment by mwaskom** [comment] 2022-06-28 23:08
I'm still not following. If you are stacking the histograms, why would you not expect the densities to stack too?

**Comment by mwaskom** [comment] 2022-07-05 22:32
Closing as this is, as far as I can see, operating as expected.

**Closed by mwaskom** 2022-07-05 22:32 UTC
