### ISSUE TITLE
Unable to parallise Facetgrid or plot facets in a loop

### ISSUE THREAD

**Issue by stydodt** [mwaskom/seaborn#2380] opened 2020-12-11 14:05 UTC
When trying to parallelise seaborn Facetgrid my script recieved a memory violation kill signal from the OS as two threads attempted to make and access the same Facetgrid object simultaneously. I identified just this line is sufficient to cause the signal when run on parallel threads or in a loop (please see [SO question](https://stackoverflow.com/questions/65127041/parallelising-seaborn-facetgrid-using-dask-delayed-memory-error) for full reproducible code):
```python
g = sns.FacetGrid(plot_df, col="feature")
```
On further investigation I discovered it is actually a (depreciated) functionality of matplotlib as shown in [this question](https://stackoverflow.com/questions/46933824/matplotlib-adding-an-axes-using-the-same-arguments-as-a-previous-axes#46933922) by another user which causes this behaviour.

**Comment by mwaskom** [comment] 2020-12-11 16:58
I'm not sure what the question is here. The link to the StackOverflow question  that you say provides an answer is just a generic point about the object-oriented interface and doesn't seem to have anything to do with parallelization.

I'm not sure how dask parallelization works, but I wouldn't expect `FacetGrid` to work with thread-wise parallelization. Process-wise should be fine.

**Comment by mwaskom** [comment] 2020-12-18 13:33
I'm not convinced that what you want to do is possible. Matplotlib's docs [explicitly claim](https://matplotlib.org/3.1.0/faq/howto_faq.html#working-with-threads) that it's not thread-safe, and I am able to reproduce your problem with a pure matplotlib examplle that instantiates subplots and calls `Figure.tight_layout`.

That said, this issue did make the think of a change that could be made to allow seaborn (if not matpltolib) to work better in a parallel context: #2388, and that is probably a good idea anyway.

But I don't think it helps here

**Comment by mwaskom** [comment] 2020-12-19 19:31
I'm going to close this because the root problem seems to be in matplotlib. I am open to making seaborn work better with dask, if there is a clear proposal about what should be done.l

For now, I have had success parallelizing plots with multiprocessing-based solutions such as joblib.

**Closed by mwaskom** 2020-12-19 19:31 UTC
Labels: upstream

**Comment by stydodt** [comment] 2021-01-18 13:48
My sincere apologies for not commenting after my initial report - GitHub for some reason failed to notify me of the updates. Thank you for taking the time to look into this issue. 

#2388 looks like a good addition and could help my other applications, but for now I agree with your investigation that it is a matplotlib error and have worked around the problem by avoiding directly parallelising seaborn with Dask.
